
// Generated by Cadence Genus(TM) Synthesis Solution 18.10-p003_1
// Generated on: Dec  8 2022 12:43:30 +0530 (Dec  8 2022 07:13:30 UTC)

// Verification Directory fv/uart_top 

module rx_buffer_WORD_SIZE8_NO_OF_WORDS1(clk, reset, data_serial_wr_en,
     data_serial_in, data_parallel_rd_enable, data_parallel_out,
     buffer_full);
  input clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable;
  output [7:0] data_parallel_out;
  output buffer_full;
  wire clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable;
  wire [7:0] data_parallel_out;
  wire buffer_full;
  wire [4:0] buffer_full_counter;
  wire [7:0] memory;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_36, n_37, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47;
  AND2X6 g236(.A (n_45), .B (n_46), .Y (n_47));
  NOR2BX1 g237(.AN (buffer_full_counter[3]), .B
       (buffer_full_counter[2]), .Y (n_46));
  NOR2XL g238(.A (buffer_full_counter[0]), .B (buffer_full_counter[1]),
       .Y (n_45));
  CLKBUFX20 drc_bufs(.A (n_47), .Y (buffer_full));
  DFFHQX1 \buffer_full_counter_reg[2] (.CK (clk), .D (n_34), .Q
       (buffer_full_counter[2]));
  DFFHQX1 \buffer_full_counter_reg[1] (.CK (clk), .D (n_32), .Q
       (buffer_full_counter[1]));
  NOR2X1 g555(.A (reset), .B (n_31), .Y (n_34));
  DFFHQX1 \buffer_full_counter_reg[3] (.CK (clk), .D (n_33), .Q
       (buffer_full_counter[3]));
  NOR2X1 g557(.A (reset), .B (n_29), .Y (n_33));
  DFFHQX1 \buffer_full_counter_reg[0] (.CK (clk), .D (n_30), .Q
       (buffer_full_counter[0]));
  NOR2X1 g559(.A (reset), .B (n_28), .Y (n_32));
  AOI22X1 g560(.A0 (buffer_full_counter[2]), .A1 (n_26), .B0
       (buffer_full_counter[1]), .B1 (n_25), .Y (n_31));
  NOR2X1 g561(.A (reset), .B (n_27), .Y (n_30));
  AOI22X1 g562(.A0 (buffer_full_counter[1]), .A1 (n_23), .B0
       (buffer_full_counter[3]), .B1 (n_12), .Y (n_29));
  MX2X1 g563(.A (n_11), .B (n_19), .S0 (buffer_full_counter[1]), .Y
       (n_28));
  DFFHQX8 \data_parallel_out_reg[7] (.CK (clk), .D (n_14), .Q (n_44));
  DFFHQX8 \data_parallel_out_reg[0] (.CK (clk), .D (n_22), .Q (n_36));
  DFFHQX8 \data_parallel_out_reg[1] (.CK (clk), .D (n_21), .Q (n_37));
  DFFHQX8 \data_parallel_out_reg[2] (.CK (clk), .D (n_20), .Q (n_39));
  DFFHQX8 \data_parallel_out_reg[3] (.CK (clk), .D (n_18), .Q (n_40));
  DFFHQX8 \data_parallel_out_reg[4] (.CK (clk), .D (n_17), .Q (n_41));
  DFFHQX8 \data_parallel_out_reg[5] (.CK (clk), .D (n_16), .Q (n_42));
  DFFHQX8 \data_parallel_out_reg[6] (.CK (clk), .D (n_15), .Q (n_43));
  DFFHQX1 \memory_reg[0] (.CK (clk), .D (n_24), .Q (memory[0]));
  AOI21X1 g573(.A0 (buffer_full_counter[0]), .A1 (n_12), .B0 (n_13), .Y
       (n_27));
  OAI21X1 g574(.A0 (buffer_full_counter[1]), .A1 (n_0), .B0 (n_19), .Y
       (n_26));
  SDFFQX1 \memory_reg[2] (.CK (clk), .D (memory[3]), .SI (memory[2]),
       .SE (n_1), .Q (memory[2]));
  SDFFQX1 \memory_reg[5] (.CK (clk), .D (memory[6]), .SI (memory[5]),
       .SE (n_1), .Q (memory[5]));
  SDFFQX1 \memory_reg[6] (.CK (clk), .D (memory[7]), .SI (memory[6]),
       .SE (n_1), .Q (memory[6]));
  SDFFQX1 \memory_reg[7] (.CK (clk), .D (data_serial_in), .SI
       (memory[7]), .SE (n_1), .Q (memory[7]));
  SDFFQX1 \memory_reg[3] (.CK (clk), .D (memory[4]), .SI (memory[3]),
       .SE (n_1), .Q (memory[3]));
  SDFFQX1 \memory_reg[1] (.CK (clk), .D (memory[2]), .SI (memory[1]),
       .SE (n_1), .Q (memory[1]));
  SDFFQX1 \memory_reg[4] (.CK (clk), .D (memory[5]), .SI (memory[4]),
       .SE (n_1), .Q (memory[4]));
  NOR2X1 g582(.A (buffer_full_counter[2]), .B (n_11), .Y (n_25));
  NOR2X1 g583(.A (reset), .B (n_2), .Y (n_24));
  NOR2BX1 g584(.AN (buffer_full_counter[2]), .B (n_11), .Y (n_23));
  NOR2X1 g585(.A (reset), .B (n_9), .Y (n_22));
  NOR2X1 g586(.A (reset), .B (n_10), .Y (n_21));
  NOR2X1 g587(.A (reset), .B (n_8), .Y (n_20));
  NOR2X1 g588(.A (reset), .B (n_7), .Y (n_18));
  NOR2X1 g589(.A (reset), .B (n_6), .Y (n_17));
  NOR2X1 g590(.A (reset), .B (n_5), .Y (n_16));
  NOR2X1 g591(.A (reset), .B (n_4), .Y (n_15));
  NOR2X1 g592(.A (reset), .B (n_3), .Y (n_14));
  NOR2X1 g593(.A (n_13), .B (n_12), .Y (n_19));
  MXI2XL g594(.A (n_37), .B (memory[1]), .S0 (data_parallel_rd_enable),
       .Y (n_10));
  MXI2XL g595(.A (n_36), .B (memory[0]), .S0 (data_parallel_rd_enable),
       .Y (n_9));
  MXI2XL g596(.A (n_39), .B (memory[2]), .S0 (data_parallel_rd_enable),
       .Y (n_8));
  NOR2X1 g597(.A (buffer_full_counter[0]), .B (n_0), .Y (n_13));
  NOR2BX1 g598(.AN (n_0), .B (data_parallel_rd_enable), .Y (n_12));
  NAND2BX1 g599(.AN (n_0), .B (buffer_full_counter[0]), .Y (n_11));
  MXI2XL g600(.A (n_40), .B (memory[3]), .S0 (data_parallel_rd_enable),
       .Y (n_7));
  MXI2XL g601(.A (n_41), .B (memory[4]), .S0 (data_parallel_rd_enable),
       .Y (n_6));
  MXI2XL g602(.A (n_42), .B (memory[5]), .S0 (data_parallel_rd_enable),
       .Y (n_5));
  MXI2XL g603(.A (n_43), .B (memory[6]), .S0 (data_parallel_rd_enable),
       .Y (n_4));
  MXI2XL g604(.A (n_44), .B (memory[7]), .S0 (data_parallel_rd_enable),
       .Y (n_3));
  MXI2XL g605(.A (memory[0]), .B (memory[1]), .S0 (data_serial_wr_en),
       .Y (n_2));
  NAND2BX4 g606(.AN (reset), .B (data_serial_wr_en), .Y (n_1));
  NAND2BX2 g607(.AN (buffer_full_counter[3]), .B (data_serial_wr_en),
       .Y (n_0));
  CLKBUFX20 drc_bufs610(.A (n_44), .Y (data_parallel_out[7]));
  CLKBUFX20 drc_bufs613(.A (n_43), .Y (data_parallel_out[6]));
  CLKBUFX20 drc_bufs616(.A (n_41), .Y (data_parallel_out[4]));
  CLKBUFX20 drc_bufs619(.A (n_36), .Y (data_parallel_out[0]));
  CLKBUFX20 drc_bufs622(.A (n_37), .Y (data_parallel_out[1]));
  CLKBUFX20 drc_bufs625(.A (n_39), .Y (data_parallel_out[2]));
  CLKBUFX20 drc_bufs628(.A (n_40), .Y (data_parallel_out[3]));
  CLKBUFX20 drc_bufs631(.A (n_42), .Y (data_parallel_out[5]));
endmodule

module
     rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1(clk,
     reset, sampling_tick_middle, sampling_tick_end, tick_start,
     rx_data, data_out_to_buffer, data_valid_to_buffer, parity_error,
     stop_bit_error);
  input clk, reset, sampling_tick_middle, sampling_tick_end, rx_data;
  output tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire clk, reset, sampling_tick_middle, sampling_tick_end, rx_data;
  wire tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire [3:0] state;
  wire [2:0] data_bit_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, parity;
  DFFHQX1 \state_reg[0] (.CK (clk), .D (n_59), .Q (state[0]));
  DFFHQX8 parity_error_reg(.CK (clk), .D (n_57), .Q (n_61));
  AOI2BB1X1 g2546(.A0N (n_31), .A1N (n_55), .B0 (reset), .Y (n_59));
  DFFHQX8 stop_bit_error_reg(.CK (clk), .D (n_58), .Q (n_60));
  NOR2X1 g2548(.A (reset), .B (n_56), .Y (n_58));
  OAI33X1 g2549(.A0 (reset), .A1 (n_4), .A2 (n_49), .B0 (n_19), .B1
       (reset), .B2 (n_27), .Y (n_57));
  DFFHQX1 \data_bit_counter_reg[2] (.CK (clk), .D (n_53), .Q
       (data_bit_counter[2]));
  DFFHQX1 \data_bit_counter_reg[0] (.CK (clk), .D (n_52), .Q
       (data_bit_counter[0]));
  DFFQX2 \state_reg[1] (.CK (clk), .D (n_50), .Q (state[1]));
  AOI22X1 g2553(.A0 (n_60), .A1 (n_42), .B0 (n_2), .B1 (n_38), .Y
       (n_56));
  OAI221X1 g2554(.A0 (n_1), .A1 (n_18), .B0 (n_8), .B1 (n_39), .C0
       (n_15), .Y (n_55));
  DFFHQX1 data_valid_to_buffer_reg(.CK (clk), .D (n_54), .Q
       (data_valid_to_buffer));
  DFFHQX1 \data_bit_counter_reg[1] (.CK (clk), .D (n_51), .Q
       (data_bit_counter[1]));
  AOI21X1 g2557(.A0 (n_25), .A1 (n_40), .B0 (reset), .Y (n_54));
  DFFHQX1 tick_start_reg(.CK (clk), .D (n_45), .Q (tick_start));
  DFFHQX1 data_out_to_buffer_reg(.CK (clk), .D (n_47), .Q
       (data_out_to_buffer));
  DFFHQX1 parity_reg(.CK (clk), .D (n_48), .Q (parity));
  DFFQX1 \state_reg[2] (.CK (clk), .D (n_46), .Q (state[2]));
  AOI21X1 g2562(.A0 (n_6), .A1 (n_37), .B0 (reset), .Y (n_53));
  NOR2BX1 g2563(.AN (n_43), .B (reset), .Y (n_52));
  NOR2X1 g2564(.A (reset), .B (n_44), .Y (n_51));
  NOR2X1 g2565(.A (reset), .B (n_41), .Y (n_50));
  NOR4X1 g2566(.A (n_11), .B (n_26), .C (n_21), .D (n_29), .Y (n_49));
  NOR2X1 g2567(.A (reset), .B (n_36), .Y (n_48));
  NOR2X1 g2568(.A (reset), .B (n_35), .Y (n_47));
  AOI31X1 g2569(.A0 (n_5), .A1 (n_20), .A2 (n_27), .B0 (reset), .Y
       (n_46));
  AOI2BB1X1 g2570(.A0N (tick_start), .A1N (n_31), .B0 (reset), .Y
       (n_45));
  AOI21X1 g2571(.A0 (data_bit_counter[1]), .A1 (n_28), .B0 (n_30), .Y
       (n_44));
  OAI221X1 g2572(.A0 (data_bit_counter[0]), .A1 (n_25), .B0 (n_13), .B1
       (n_6), .C0 (n_34), .Y (n_43));
  OAI211X1 g2573(.A0 (n_14), .A1 (n_12), .B0 (n_7), .C0 (n_33), .Y
       (n_42));
  AOI22X1 g2574(.A0 (n_11), .A1 (n_18), .B0 (state[1]), .B1 (n_32), .Y
       (n_41));
  OAI21X1 g2575(.A0 (n_11), .A1 (n_22), .B0 (data_valid_to_buffer), .Y
       (n_40));
  OA21X1 g2576(.A0 (state[0]), .A1 (n_23), .B0 (n_12), .Y (n_39));
  AO21X1 g2577(.A0 (n_0), .A1 (n_26), .B0 (n_21), .Y (n_38));
  AOI2BB2X1 g2578(.A0N (n_13), .A1N (n_25), .B0 (n_10), .B1
       (data_bit_counter[2]), .Y (n_37));
  AOI22X1 g2579(.A0 (n_19), .A1 (n_24), .B0 (parity), .B1 (n_17), .Y
       (n_36));
  AOI22X1 g2580(.A0 (rx_data), .A1 (n_24), .B0 (data_out_to_buffer),
       .B1 (n_17), .Y (n_35));
  NAND2X1 g2581(.A (data_bit_counter[0]), .B (n_17), .Y (n_34));
  NAND2X1 g2582(.A (state[1]), .B (n_20), .Y (n_33));
  NAND2X1 g2583(.A (state[0]), .B (n_18), .Y (n_32));
  NOR3BX1 g2584(.AN (data_bit_counter[0]), .B (data_bit_counter[1]), .C
       (n_25), .Y (n_30));
  OAI22X1 g2585(.A0 (sampling_tick_middle), .A1 (n_7), .B0 (state[0]),
       .B1 (n_0), .Y (n_29));
  OAI211X1 g2586(.A0 (data_bit_counter[0]), .A1 (n_0), .B0 (n_6), .C0
       (n_16), .Y (n_28));
  NOR3X1 g2587(.A (rx_data), .B (state[1]), .C (n_10), .Y (n_31));
  INVX1 g2588(.A (n_25), .Y (n_24));
  NAND2BX1 g2589(.AN (n_13), .B (data_bit_counter[2]), .Y (n_23));
  AND2X1 g2590(.A (n_14), .B (state[2]), .Y (n_22));
  OR2X1 g2591(.A (n_8), .B (n_7), .Y (n_27));
  NOR2X1 g2592(.A (n_1), .B (n_9), .Y (n_26));
  OR2X1 g2593(.A (n_8), .B (n_10), .Y (n_25));
  INVX1 g2594(.A (n_16), .Y (n_17));
  NAND2X1 g2595(.A (state[2]), .B (n_11), .Y (n_15));
  NOR2BX1 g2596(.AN (sampling_tick_middle), .B (n_12), .Y (n_21));
  OAI2BB1X1 g2597(.A0N (sampling_tick_end), .A1N (state[0]), .B0
       (state[2]), .Y (n_20));
  XNOR2X1 g2598(.A (parity), .B (n_2), .Y (n_19));
  OAI2BB1X1 g2599(.A0N (sampling_tick_middle), .A1N (n_3), .B0 (n_9),
       .Y (n_18));
  AOI2BB1X1 g2600(.A0N (sampling_tick_middle), .A1N (n_0), .B0 (n_10),
       .Y (n_16));
  OR2X1 g2601(.A (sampling_tick_middle), .B (state[1]), .Y (n_14));
  NAND2X1 g2602(.A (data_bit_counter[1]), .B (data_bit_counter[0]), .Y
       (n_13));
  NAND2X1 g2603(.A (state[2]), .B (n_1), .Y (n_12));
  NOR2X1 g2604(.A (state[1]), .B (n_1), .Y (n_11));
  OR2X1 g2605(.A (state[2]), .B (state[0]), .Y (n_10));
  NAND2X1 g2606(.A (state[2]), .B (n_0), .Y (n_5));
  NAND2X1 g2607(.A (sampling_tick_end), .B (state[2]), .Y (n_9));
  NAND2X1 g2608(.A (sampling_tick_middle), .B (state[1]), .Y (n_8));
  NAND2X1 g2609(.A (state[0]), .B (n_3), .Y (n_7));
  NAND2X1 g2610(.A (data_bit_counter[2]), .B (state[1]), .Y (n_6));
  INVX1 g2611(.A (n_61), .Y (n_4));
  INVX1 g2612(.A (state[2]), .Y (n_3));
  INVX1 g2613(.A (rx_data), .Y (n_2));
  INVX2 g2614(.A (state[0]), .Y (n_1));
  INVX1 g2615(.A (state[1]), .Y (n_0));
  CLKBUFX20 drc_bufs2618(.A (n_61), .Y (parity_error));
  CLKBUFX20 drc_bufs2621(.A (n_60), .Y (stop_bit_error));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100(clk, reset,
     start, tick_16_8, tick_16_16);
  input clk, reset, start;
  output tick_16_8, tick_16_16;
  wire clk, reset, start;
  wire tick_16_8, tick_16_16;
  wire [10:0] counter;
  wire n_0, n_1, n_2, n_4, n_5, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_45, n_46, n_88, n_89, n_91, n_95, n_96;
  wire n_97;
  DFFHQX1 tick_16_16_reg(.CK (clk), .D (n_43), .Q (tick_16_16));
  NOR3X1 g472(.A (reset), .B (n_88), .C (n_42), .Y (n_43));
  NOR2X1 g473(.A (n_88), .B (n_42), .Y (n_89));
  NAND3BX2 g475(.AN (n_41), .B (counter[8]), .C (counter[9]), .Y
       (n_42));
  AOI31X1 g476(.A0 (counter[5]), .A1 (counter[6]), .A2 (n_40), .B0
       (counter[7]), .Y (n_41));
  NOR2X1 g477(.A (n_91), .B (n_46), .Y (n_45));
  OR3X1 g478(.A (counter[3]), .B (counter[2]), .C (counter[4]), .Y
       (n_40));
  NAND2X1 g479(.A (counter[5]), .B (counter[4]), .Y (n_46));
  INVX1 g482(.A (counter[6]), .Y (n_91));
  INVX1 g484(.A (start), .Y (n_88));
  DFFHQX1 \counter_reg[9] (.CK (clk), .D (n_39), .Q (counter[9]));
  NOR3X1 g980(.A (reset), .B (n_4), .C (n_37), .Y (n_39));
  DFFHQX1 \counter_reg[8] (.CK (clk), .D (n_38), .Q (counter[8]));
  NOR3BX1 g982(.AN (n_36), .B (reset), .C (n_4), .Y (n_38));
  XNOR2X1 g983(.A (counter[9]), .B (n_35), .Y (n_37));
  ADDHX1 g984(.A (counter[8]), .B (n_31), .CO (n_35), .S (n_36));
  DFFHQX1 \counter_reg[6] (.CK (clk), .D (n_34), .Q (counter[6]));
  DFFHQX1 \counter_reg[5] (.CK (clk), .D (n_33), .Q (counter[5]));
  NOR3BX1 g987(.AN (n_30), .B (reset), .C (n_4), .Y (n_34));
  DFFHQX1 \counter_reg[7] (.CK (clk), .D (n_32), .Q (counter[7]));
  NOR2BX1 g989(.AN (n_26), .B (reset), .Y (n_33));
  DFFHQX1 \counter_reg[4] (.CK (clk), .D (n_28), .Q (counter[4]));
  NOR2X1 g991(.A (reset), .B (n_27), .Y (n_32));
  AND2X1 g992(.A (n_29), .B (counter[7]), .Y (n_31));
  ADDHX1 g993(.A (counter[6]), .B (n_20), .CO (n_29), .S (n_30));
  NOR2BX1 g994(.AN (n_24), .B (reset), .Y (n_28));
  AOI31X1 g995(.A0 (n_2), .A1 (n_45), .A2 (n_0), .B0 (n_25), .Y (n_27));
  OAI32X1 g996(.A0 (counter[5]), .A1 (n_1), .A2 (n_21), .B0 (n_23), .B1
       (n_4), .Y (n_26));
  DFFHQX1 \counter_reg[3] (.CK (clk), .D (n_22), .Q (counter[3]));
  AOI211X1 g998(.A0 (n_45), .A1 (n_19), .B0 (n_2), .C0 (n_4), .Y
       (n_25));
  OAI32X1 g999(.A0 (n_1), .A1 (n_19), .A2 (n_4), .B0 (counter[4]), .B1
       (n_21), .Y (n_24));
  OAI2BB1X1 g1000(.A0N (counter[4]), .A1N (n_19), .B0 (counter[5]), .Y
       (n_23));
  NOR3BX1 g1001(.AN (n_18), .B (reset), .C (n_4), .Y (n_22));
  DFFHQX1 tick_16_8_reg(.CK (clk), .D (n_17), .Q (tick_16_8));
  NAND2X1 g1004(.A (n_19), .B (n_95), .Y (n_21));
  NOR2BX1 g1005(.AN (n_19), .B (n_46), .Y (n_20));
  ADDHX1 g1006(.A (counter[3]), .B (n_13), .CO (n_19), .S (n_18));
  DFFHQX1 \counter_reg[2] (.CK (clk), .D (n_16), .Q (counter[2]));
  NOR2X1 g1008(.A (reset), .B (n_15), .Y (n_17));
  NOR3BX1 g1009(.AN (n_14), .B (reset), .C (n_4), .Y (n_16));
  AOI22X1 g1010(.A0 (n_8), .A1 (n_12), .B0 (tick_16_8), .B1 (n_89), .Y
       (n_15));
  ADDHX1 g1011(.A (counter[2]), .B (n_9), .CO (n_13), .S (n_14));
  DFFHQX1 \counter_reg[1] (.CK (clk), .D (n_11), .Q (counter[1]));
  NOR4BBX1 g1013(.AN (counter[1]), .BN (counter[5]), .C (n_88), .D
       (n_97), .Y (n_12));
  NOR3BX1 g1014(.AN (n_10), .B (reset), .C (n_4), .Y (n_11));
  ADDHX1 g1015(.A (counter[1]), .B (counter[0]), .CO (n_9), .S (n_10));
  DFFQXL \counter_reg[0] (.CK (clk), .D (n_5), .Q (counter[0]));
  NOR4BX1 g1017(.AN (counter[8]), .B (counter[0]), .C (n_2), .D (n_1),
       .Y (n_8));
  NOR3X1 g1020(.A (reset), .B (counter[0]), .C (n_4), .Y (n_5));
  INVX2 g1021(.A (n_95), .Y (n_4));
  INVX1 g1025(.A (counter[7]), .Y (n_2));
  INVX1 g1026(.A (counter[4]), .Y (n_1));
  INVX1 drc_bufs1028(.A (n_21), .Y (n_0));
  NOR2BX1 g1030(.AN (n_42), .B (n_88), .Y (n_95));
  INVXL g3(.A (n_96), .Y (n_97));
  NOR4BX1 g1031(.AN (n_91), .B (counter[3]), .C (counter[2]), .D
       (counter[9]), .Y (n_96));
endmodule

module
     rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100(clk,
     reset, rx_data, data_parallel_out, data_parallel_rd_enable,
     rx_buffer_full, parity_error, stop_bit_error);
  input clk, reset, rx_data, data_parallel_rd_enable;
  output [7:0] data_parallel_out;
  output rx_buffer_full, parity_error, stop_bit_error;
  wire clk, reset, rx_data, data_parallel_rd_enable;
  wire [7:0] data_parallel_out;
  wire rx_buffer_full, parity_error, stop_bit_error;
  wire data_out_to_buffer, data_valid_to_buffer, sampling_tick_end,
       sampling_tick_middle, tick_start;
  rx_buffer_WORD_SIZE8_NO_OF_WORDS1 ins_rx_buffer(.clk (clk), .reset
       (reset), .data_serial_wr_en (data_valid_to_buffer),
       .data_serial_in (data_out_to_buffer), .data_parallel_rd_enable
       (data_parallel_rd_enable), .data_parallel_out
       (data_parallel_out), .buffer_full (rx_buffer_full));
  rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1
       ins_rx_fsm(.clk (clk), .reset (reset), .sampling_tick_middle
       (sampling_tick_middle), .sampling_tick_end (sampling_tick_end),
       .tick_start (tick_start), .rx_data (rx_data),
       .data_out_to_buffer (data_out_to_buffer), .data_valid_to_buffer
       (data_valid_to_buffer), .parity_error (parity_error),
       .stop_bit_error (stop_bit_error));
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (sampling_tick_end));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_1(clk, reset,
     start, tick_16_8, tick_16_16);
  input clk, reset, start;
  output tick_16_8, tick_16_16;
  wire clk, reset, start;
  wire tick_16_8, tick_16_16;
  wire [10:0] counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37;
  DFFHQX1 \counter_reg[9] (.CK (clk), .D (n_37), .Q (counter[9]));
  DFFQXL \counter_reg[8] (.CK (clk), .D (n_36), .Q (counter[8]));
  NOR3X1 g1027(.A (reset), .B (n_0), .C (n_35), .Y (n_37));
  NOR3BX1 g1028(.AN (n_34), .B (reset), .C (n_0), .Y (n_36));
  NOR2X1 g1029(.A (counter[9]), .B (n_33), .Y (n_35));
  ADDHX1 g1030(.A (counter[8]), .B (n_30), .CO (n_33), .S (n_34));
  DFFQXL \counter_reg[7] (.CK (clk), .D (n_32), .Q (counter[7]));
  NOR3BX1 g1032(.AN (n_31), .B (reset), .C (n_0), .Y (n_32));
  DFFHQX1 \counter_reg[5] (.CK (clk), .D (n_29), .Q (counter[5]));
  ADDHX1 g1034(.A (counter[7]), .B (n_23), .CO (n_30), .S (n_31));
  DFFQXL \counter_reg[6] (.CK (clk), .D (n_27), .Q (counter[6]));
  NOR3X1 g1036(.A (reset), .B (n_25), .C (n_0), .Y (n_29));
  DFFHQX1 tick_16_8_reg(.CK (clk), .D (n_28), .Q (tick_16_8));
  DFFHQX1 \counter_reg[4] (.CK (clk), .D (n_26), .Q (counter[4]));
  NOR3BX1 g1039(.AN (start), .B (reset), .C (n_22), .Y (n_28));
  NOR3BX1 g1040(.AN (n_24), .B (reset), .C (n_0), .Y (n_27));
  NOR3BX1 g1041(.AN (n_21), .B (reset), .C (n_0), .Y (n_26));
  XNOR2X1 g1042(.A (counter[5]), .B (n_20), .Y (n_25));
  ADDHX1 g1043(.A (counter[6]), .B (n_17), .CO (n_23), .S (n_24));
  AOI22X1 g1044(.A0 (counter[8]), .A1 (n_19), .B0 (tick_16_8), .B1
       (n_10), .Y (n_22));
  ADDHX1 g1045(.A (counter[4]), .B (n_16), .CO (n_20), .S (n_21));
  DFFHQX1 \counter_reg[3] (.CK (clk), .D (n_18), .Q (counter[3]));
  NOR4BX1 g1047(.AN (counter[7]), .B (counter[0]), .C (counter[6]), .D
       (n_11), .Y (n_19));
  NOR3BX1 g1048(.AN (n_15), .B (reset), .C (n_0), .Y (n_18));
  DFFHQX1 \counter_reg[1] (.CK (clk), .D (n_13), .Q (counter[1]));
  DFFHQX1 \counter_reg[2] (.CK (clk), .D (n_12), .Q (counter[2]));
  NOR2BX1 g1051(.AN (n_16), .B (n_3), .Y (n_17));
  DFFQXL \counter_reg[0] (.CK (clk), .D (n_14), .Q (counter[0]));
  ADDHX1 g1053(.A (counter[3]), .B (n_8), .CO (n_16), .S (n_15));
  NOR3X1 g1054(.A (reset), .B (counter[0]), .C (n_0), .Y (n_14));
  NOR3BX1 g1055(.AN (n_6), .B (reset), .C (n_0), .Y (n_13));
  NOR3BX1 g1056(.AN (n_9), .B (reset), .C (n_0), .Y (n_12));
  OR4X1 g1058(.A (n_1), .B (n_3), .C (n_2), .D (n_10), .Y (n_11));
  AND3XL g1059(.A (counter[9]), .B (counter[8]), .C (n_7), .Y (n_10));
  ADDHX1 g1060(.A (counter[2]), .B (n_5), .CO (n_8), .S (n_9));
  AO21X1 g1061(.A0 (counter[6]), .A1 (n_4), .B0 (counter[7]), .Y (n_7));
  ADDHX1 g1062(.A (counter[1]), .B (counter[0]), .CO (n_5), .S (n_6));
  OAI2BB1X1 g1063(.A0N (counter[5]), .A1N (n_2), .B0 (n_3), .Y (n_4));
  NAND2X1 g1064(.A (counter[4]), .B (counter[5]), .Y (n_3));
  OR2X1 g1065(.A (counter[3]), .B (counter[2]), .Y (n_2));
  INVX1 g1067(.A (counter[1]), .Y (n_1));
  NAND2BX4 g2(.AN (n_10), .B (start), .Y (n_0));
endmodule

module tx_buffer_WORD_SIZE8_NO_OF_WORDS1(clk, reset, data_parallel_in,
     data_parallel_wr_enable, data_serial_rd_enable, data_serial_out,
     empty);
  input clk, reset, data_parallel_wr_enable, data_serial_rd_enable;
  input [7:0] data_parallel_in;
  output data_serial_out, empty;
  wire clk, reset, data_parallel_wr_enable, data_serial_rd_enable;
  wire [7:0] data_parallel_in;
  wire data_serial_out, empty;
  wire [4:0] buffer_empty_counter;
  wire [7:0] memory;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38;
  NOR3X2 g386(.A (buffer_empty_counter[0]), .B
       (buffer_empty_counter[1]), .C (n_38), .Y (empty));
  OR3X1 g387(.A (buffer_empty_counter[2]), .B
       (buffer_empty_counter[3]), .C (buffer_empty_counter[4]), .Y
       (n_38));
  DFFHQX1 \buffer_empty_counter_reg[4] (.CK (clk), .D (n_37), .Q
       (buffer_empty_counter[4]));
  DFFHQX1 \buffer_empty_counter_reg[3] (.CK (clk), .D (n_36), .Q
       (buffer_empty_counter[3]));
  NOR3X1 g908(.A (reset), .B (n_35), .C (data_parallel_wr_enable), .Y
       (n_37));
  OR4X1 g909(.A (reset), .B (n_33), .C (n_32), .D
       (data_parallel_wr_enable), .Y (n_36));
  DFFHQX1 \buffer_empty_counter_reg[2] (.CK (clk), .D (n_34), .Q
       (buffer_empty_counter[2]));
  XNOR2X1 g911(.A (buffer_empty_counter[4]), .B (n_32), .Y (n_35));
  NOR3X1 g912(.A (reset), .B (n_30), .C (data_parallel_wr_enable), .Y
       (n_34));
  NOR2BX1 g913(.AN (buffer_empty_counter[3]), .B (n_29), .Y (n_33));
  NOR2BX1 g914(.AN (n_29), .B (buffer_empty_counter[3]), .Y (n_32));
  DFFHQX1 \buffer_empty_counter_reg[1] (.CK (clk), .D (n_31), .Q
       (buffer_empty_counter[1]));
  NOR3X1 g916(.A (reset), .B (n_27), .C (data_parallel_wr_enable), .Y
       (n_31));
  AOI21X1 g917(.A0 (buffer_empty_counter[2]), .A1 (n_26), .B0 (n_29),
       .Y (n_30));
  NOR2X1 g918(.A (buffer_empty_counter[2]), .B (n_26), .Y (n_29));
  DFFHQX1 \buffer_empty_counter_reg[0] (.CK (clk), .D (n_28), .Q
       (buffer_empty_counter[0]));
  DFFHQX1 \memory_reg[1] (.CK (clk), .D (n_23), .Q (memory[1]));
  DFFHQX1 \memory_reg[2] (.CK (clk), .D (n_24), .Q (memory[2]));
  DFFHQX1 \memory_reg[5] (.CK (clk), .D (n_21), .Q (memory[5]));
  NOR3X1 g923(.A (reset), .B (n_12), .C (data_parallel_wr_enable), .Y
       (n_28));
  XNOR2X1 g924(.A (buffer_empty_counter[1]), .B (n_7), .Y (n_27));
  DFFHQX1 \memory_reg[7] (.CK (clk), .D (n_22), .Q (memory[7]));
  DFFHQX1 \memory_reg[3] (.CK (clk), .D (n_20), .Q (memory[3]));
  DFFHQX1 \memory_reg[0] (.CK (clk), .D (n_19), .Q (memory[0]));
  DFFHQX1 \memory_reg[6] (.CK (clk), .D (n_15), .Q (memory[6]));
  DFFHQX1 \memory_reg[4] (.CK (clk), .D (n_18), .Q (memory[4]));
  OAI2BB1X1 g930(.A0N (data_parallel_in[2]), .A1N (n_2), .B0 (n_17), .Y
       (n_24));
  OAI2BB1X1 g931(.A0N (data_parallel_in[1]), .A1N (n_2), .B0 (n_16), .Y
       (n_23));
  AO22X1 g932(.A0 (n_13), .A1 (memory[7]), .B0 (data_parallel_in[7]),
       .B1 (n_2), .Y (n_22));
  OAI2BB1X1 g933(.A0N (data_parallel_in[5]), .A1N (n_2), .B0 (n_14), .Y
       (n_21));
  NAND2BX1 g934(.AN (buffer_empty_counter[1]), .B (n_7), .Y (n_26));
  OAI2BB1X1 g935(.A0N (n_0), .A1N (memory[3]), .B0 (n_9), .Y (n_20));
  OAI2BB1X1 g936(.A0N (n_0), .A1N (memory[0]), .B0 (n_10), .Y (n_19));
  OAI2BB1X1 g937(.A0N (n_0), .A1N (memory[4]), .B0 (n_11), .Y (n_18));
  SDFFQX1 data_serial_out_reg(.CK (clk), .D (n_5), .SI (memory[0]), .SE
       (data_serial_rd_enable), .Q (data_serial_out));
  AOI22X1 g939(.A0 (n_0), .A1 (memory[2]), .B0 (memory[3]), .B1
       (data_serial_rd_enable), .Y (n_17));
  AOI22X1 g940(.A0 (n_0), .A1 (memory[1]), .B0 (memory[2]), .B1
       (data_serial_rd_enable), .Y (n_16));
  OAI2BB1X1 g941(.A0N (n_0), .A1N (memory[6]), .B0 (n_8), .Y (n_15));
  AOI22X1 g942(.A0 (n_0), .A1 (memory[5]), .B0 (memory[6]), .B1
       (data_serial_rd_enable), .Y (n_14));
  OAI21X1 g943(.A0 (reset), .A1 (n_1), .B0 (n_6), .Y (n_13));
  AOI21X1 g944(.A0 (buffer_empty_counter[0]), .A1 (n_3), .B0 (n_7), .Y
       (n_12));
  AOI22X1 g945(.A0 (data_parallel_in[4]), .A1 (n_2), .B0 (memory[5]),
       .B1 (data_serial_rd_enable), .Y (n_11));
  AOI22X1 g946(.A0 (data_parallel_in[0]), .A1 (n_2), .B0 (memory[1]),
       .B1 (data_serial_rd_enable), .Y (n_10));
  AOI22X1 g947(.A0 (data_parallel_in[3]), .A1 (n_2), .B0 (memory[4]),
       .B1 (data_serial_rd_enable), .Y (n_9));
  AOI22X1 g948(.A0 (data_parallel_in[6]), .A1 (n_2), .B0 (memory[7]),
       .B1 (data_serial_rd_enable), .Y (n_8));
  NOR2X1 g949(.A (buffer_empty_counter[0]), .B (n_3), .Y (n_7));
  INVX1 g950(.A (n_0), .Y (n_6));
  NOR2BX1 g952(.AN (data_serial_out), .B (reset), .Y (n_5));
  NOR2X1 g953(.A (reset), .B (data_serial_rd_enable), .Y (n_4));
  OR2X1 g954(.A (n_1), .B (empty), .Y (n_3));
  AND2X1 g955(.A (data_parallel_wr_enable), .B (n_1), .Y (n_2));
  INVX1 g960(.A (data_serial_rd_enable), .Y (n_1));
  NOR2BX2 g2(.AN (n_4), .B (data_parallel_wr_enable), .Y (n_0));
endmodule

module
     tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1(clk,
     reset, empty, sampling_tick_middle, sampling_tick_end, tick_start,
     data_parallel_wr_enable, tx_busy, tx_data, buffer_rd_enable,
     buffer_data);
  input clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data;
  output tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data;
  wire tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire [2:0] data_bit_counter;
  wire [3:0] state;
  wire delay_data_parallel_wr_enable, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, parity, tem_buffer_data;
  DFFQX2 buffer_rd_enable_reg(.CK (clk), .D (n_63), .Q
       (buffer_rd_enable));
  DFFHQX1 \data_bit_counter_reg[0] (.CK (clk), .D (n_70), .Q
       (data_bit_counter[0]));
  DFFHQX1 \data_bit_counter_reg[1] (.CK (clk), .D (n_76), .Q
       (data_bit_counter[1]));
  DFFHQX1 \data_bit_counter_reg[2] (.CK (clk), .D (n_68), .Q
       (data_bit_counter[2]));
  DFFHQX1 delay_data_parallel_wr_enable_reg(.CK (clk), .D
       (data_parallel_wr_enable), .Q (delay_data_parallel_wr_enable));
  DFFHQX1 parity_reg(.CK (clk), .D (n_78), .Q (parity));
  DFFHQX1 \state_reg[0] (.CK (clk), .D (n_77), .Q (state[0]));
  DFFHQX1 \state_reg[1] (.CK (clk), .D (n_71), .Q (state[1]));
  DFFQX2 \state_reg[2] (.CK (clk), .D (n_75), .Q (state[2]));
  DFFQX1 \state_reg[3] (.CK (clk), .D (n_51), .Q (state[3]));
  DFFHQX1 tem_buffer_data_reg(.CK (clk), .D (n_74), .Q
       (tem_buffer_data));
  DFFHQX1 tick_start_reg(.CK (clk), .D (n_66), .Q (tick_start));
  DFFHQX8 tx_busy_reg(.CK (clk), .D (n_61), .Q (n_79));
  DFFHQX1 tx_data_reg(.CK (clk), .D (n_72), .Q (tx_data));
  NOR2X1 g2035(.A (reset), .B (n_73), .Y (n_78));
  OAI22X1 g2036(.A0 (reset), .A1 (n_69), .B0 (reset), .B1 (n_30), .Y
       (n_77));
  AOI21X1 g2041(.A0 (n_48), .A1 (n_64), .B0 (reset), .Y (n_76));
  AOI31X1 g2042(.A0 (n_26), .A1 (n_37), .A2 (n_58), .B0 (reset), .Y
       (n_75));
  AOI21X1 g2043(.A0 (n_42), .A1 (n_67), .B0 (reset), .Y (n_74));
  MX2X1 g2044(.A (n_42), .B (n_65), .S0 (parity), .Y (n_73));
  NAND3X1 g2048(.A (n_60), .B (n_31), .C (n_35), .Y (n_72));
  AOI31X1 g2049(.A0 (n_12), .A1 (n_36), .A2 (n_47), .B0 (reset), .Y
       (n_71));
  NOR2X1 g2050(.A (reset), .B (n_62), .Y (n_70));
  AOI221X1 g2051(.A0 (n_0), .A1 (n_52), .B0 (n_20), .B1 (n_34), .C0
       (n_39), .Y (n_69));
  NOR2X1 g2052(.A (reset), .B (n_56), .Y (n_68));
  NAND2X1 g2053(.A (tem_buffer_data), .B (n_59), .Y (n_67));
  AOI31X1 g2054(.A0 (n_45), .A1 (n_35), .A2 (n_46), .B0 (reset), .Y
       (n_66));
  AOI2BB1X1 g2056(.A0N (buffer_data), .A1N (n_3), .B0 (n_59), .Y
       (n_65));
  OAI2BB1X1 g2057(.A0N (n_16), .A1N (n_55), .B0 (data_bit_counter[1]),
       .Y (n_64));
  NOR2X1 g2058(.A (reset), .B (n_57), .Y (n_63));
  AOI222X1 g2059(.A0 (n_4), .A1 (n_34), .B0 (state[2]), .B1 (n_20), .C0
       (data_bit_counter[0]), .C1 (n_54), .Y (n_62));
  AOI21X1 g2060(.A0 (n_44), .A1 (n_46), .B0 (reset), .Y (n_61));
  AOI211X1 g2061(.A0 (tx_data), .A1 (n_22), .B0 (reset), .C0 (n_50), .Y
       (n_60));
  OA21X1 g2063(.A0 (state[0]), .A1 (n_10), .B0 (n_49), .Y (n_58));
  AOI221X1 g2064(.A0 (n_19), .A1 (n_34), .B0 (buffer_rd_enable), .B1
       (n_21), .C0 (n_43), .Y (n_57));
  AOI31X1 g2065(.A0 (data_bit_counter[0]), .A1 (data_bit_counter[1]),
       .A2 (n_34), .B0 (n_53), .Y (n_56));
  OR3X1 g2066(.A (state[2]), .B (n_25), .C (n_41), .Y (n_59));
  INVX1 g2067(.A (n_54), .Y (n_55));
  OA21X1 g2068(.A0 (n_8), .A1 (n_33), .B0 (data_bit_counter[2]), .Y
       (n_53));
  NAND2X1 g2069(.A (n_21), .B (n_38), .Y (n_52));
  NOR2X1 g2070(.A (reset), .B (n_40), .Y (n_51));
  NAND3X2 g2071(.A (n_3), .B (n_26), .C (n_32), .Y (n_54));
  OAI33X1 g2072(.A0 (state[0]), .A1 (n_14), .A2 (n_15), .B0 (n_13), .B1
       (parity), .B2 (n_24), .Y (n_50));
  OAI211X1 g2073(.A0 (state[0]), .A1 (n_20), .B0 (n_3), .C0 (state[2]),
       .Y (n_49));
  NAND3BX1 g2074(.AN (data_bit_counter[1]), .B (data_bit_counter[0]),
       .C (n_34), .Y (n_48));
  AOI221X1 g2075(.A0 (n_19), .A1 (n_27), .B0 (state[1]), .B1 (n_0), .C0
       (n_23), .Y (n_47));
  NAND2X1 g2076(.A (tick_start), .B (n_31), .Y (n_45));
  NAND2X1 g2077(.A (n_79), .B (n_31), .Y (n_44));
  NOR2X1 g2078(.A (state[2]), .B (n_36), .Y (n_43));
  NAND2BX1 g2079(.AN (n_31), .B (delay_data_parallel_wr_enable), .Y
       (n_46));
  OAI211X1 g2080(.A0 (state[0]), .A1 (n_6), .B0 (n_12), .C0 (n_5), .Y
       (n_41));
  AOI22X1 g2081(.A0 (state[3]), .A1 (n_17), .B0 (state[0]), .B1 (n_18),
       .Y (n_40));
  OAI22X1 g2082(.A0 (sampling_tick_middle), .A1 (n_24), .B0 (n_0), .B1
       (n_26), .Y (n_39));
  AOI31X1 g2083(.A0 (delay_data_parallel_wr_enable), .A1 (n_2), .A2
       (n_1), .B0 (n_29), .Y (n_38));
  NAND2BX1 g2084(.AN (n_37), .B (buffer_data), .Y (n_42));
  OR2X1 g2085(.A (n_0), .B (n_21), .Y (n_37));
  NAND2X1 g2086(.A (sampling_tick_middle), .B (n_25), .Y (n_36));
  OR2X1 g2087(.A (n_8), .B (n_28), .Y (n_35));
  AND2X1 g2088(.A (n_27), .B (n_0), .Y (n_34));
  INVX1 g2089(.A (n_32), .Y (n_33));
  OA21X1 g2090(.A0 (n_0), .A1 (n_12), .B0 (n_28), .Y (n_30));
  NOR3BX1 g2091(.AN (sampling_tick_middle), .B (n_2), .C (n_8), .Y
       (n_29));
  MX2X1 g2092(.A (n_11), .B (n_0), .S0 (n_2), .Y (n_32));
  OR3X1 g2093(.A (state[2]), .B (state[0]), .C (n_7), .Y (n_31));
  INVX1 g2094(.A (n_25), .Y (n_24));
  NOR2X1 g2095(.A (sampling_tick_middle), .B (n_10), .Y (n_23));
  NAND2X1 g2096(.A (sampling_tick_middle), .B (n_6), .Y (n_22));
  NAND2X1 g2097(.A (state[3]), .B (n_11), .Y (n_28));
  NOR2X1 g2098(.A (n_13), .B (n_7), .Y (n_27));
  NAND2X2 g2099(.A (state[2]), .B (n_14), .Y (n_26));
  NOR2X1 g2100(.A (n_0), .B (n_7), .Y (n_25));
  INVX1 g2101(.A (n_20), .Y (n_19));
  NOR2X1 g2102(.A (n_3), .B (n_13), .Y (n_18));
  OR2X1 g2103(.A (n_0), .B (n_8), .Y (n_17));
  OAI21X1 g2104(.A0 (data_bit_counter[2]), .A1 (n_4), .B0 (state[2]),
       .Y (n_16));
  AOI21X1 g2105(.A0 (tem_buffer_data), .A1 (state[2]), .B0 (n_9), .Y
       (n_15));
  OR3X1 g2106(.A (state[2]), .B (n_3), .C (state[3]), .Y (n_21));
  AND3XL g2107(.A (data_bit_counter[2]), .B (data_bit_counter[1]), .C
       (data_bit_counter[0]), .Y (n_20));
  NAND2X1 g2109(.A (sampling_tick_middle), .B (n_2), .Y (n_14));
  NAND2X1 g2110(.A (state[2]), .B (sampling_tick_middle), .Y (n_13));
  NAND2X1 g2111(.A (state[1]), .B (state[3]), .Y (n_12));
  INVX1 g2112(.A (n_9), .Y (n_10));
  INVX1 g2113(.A (n_7), .Y (n_6));
  NAND2X1 g2114(.A (state[3]), .B (empty), .Y (n_5));
  NOR2X1 g2115(.A (n_0), .B (empty), .Y (n_11));
  NOR2X1 g2116(.A (n_3), .B (n_1), .Y (n_9));
  OR2X1 g2117(.A (state[2]), .B (state[1]), .Y (n_8));
  OR2X1 g2118(.A (state[3]), .B (state[1]), .Y (n_7));
  INVX1 g2119(.A (data_bit_counter[0]), .Y (n_4));
  INVX1 g2120(.A (state[1]), .Y (n_3));
  INVX1 g2121(.A (state[3]), .Y (n_2));
  INVX1 g2122(.A (state[2]), .Y (n_1));
  INVX2 g2123(.A (state[0]), .Y (n_0));
  CLKBUFX20 drc_bufs2126(.A (n_79), .Y (tx_busy));
endmodule

module
     tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100(clk,
     reset, data_parallel_in, data_parallel_wr_enable, tx_busy,
     tx_data);
  input clk, reset, data_parallel_wr_enable;
  input [7:0] data_parallel_in;
  output tx_busy, tx_data;
  wire clk, reset, data_parallel_wr_enable;
  wire [7:0] data_parallel_in;
  wire tx_busy, tx_data;
  wire UNCONNECTED_HIER_Z, data_serial_out, data_serial_rd_enable,
       empty, sampling_tick_end, sampling_tick_middle, tick_start;
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_1
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (sampling_tick_end));
  tx_buffer_WORD_SIZE8_NO_OF_WORDS1 ins_tx_buffer(.clk (clk), .reset
       (reset), .data_parallel_in (data_parallel_in),
       .data_parallel_wr_enable (data_parallel_wr_enable),
       .data_serial_rd_enable (data_serial_rd_enable), .data_serial_out
       (data_serial_out), .empty (empty));
  tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1
       ins_tx_fsm(.clk (clk), .reset (reset), .empty (empty),
       .sampling_tick_middle (sampling_tick_middle), .sampling_tick_end
       (UNCONNECTED_HIER_Z), .tick_start (tick_start),
       .data_parallel_wr_enable (data_parallel_wr_enable), .tx_busy
       (tx_busy), .tx_data (tx_data), .buffer_rd_enable
       (data_serial_rd_enable), .buffer_data (data_serial_out));
endmodule

module
     uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1(clk,
     reset, uart_hw_rx_pin, uart_hw_tx_pin, tx_parallel_data_in,
     tx_data_wr_enable_in, tx_busy_out, rx_full, rx_parallel_data_out,
     rx_data_rd_enable_in, rx_parity_error, rx_stop_bit_error);
  input clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in;
  input [7:0] tx_parallel_data_in;
  output uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error;
  output [7:0] rx_parallel_data_out;
  wire clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in;
  wire [7:0] tx_parallel_data_in;
  wire uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error;
  wire [7:0] rx_parallel_data_out;
  rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100
       ins_rx_wrapper(.clk (clk), .reset (reset), .rx_data
       (uart_hw_rx_pin), .data_parallel_out (rx_parallel_data_out),
       .data_parallel_rd_enable (rx_data_rd_enable_in), .rx_buffer_full
       (rx_full), .parity_error (rx_parity_error), .stop_bit_error
       (rx_stop_bit_error));
  tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100
       ins_tx_wrapper(.clk (clk), .reset (reset), .data_parallel_in
       (tx_parallel_data_in), .data_parallel_wr_enable
       (tx_data_wr_enable_in), .tx_busy (tx_busy_out), .tx_data
       (uart_hw_tx_pin));
endmodule

module rx_buffer_WORD_SIZE8_NO_OF_WORDS1_1(clk, reset,
     data_serial_wr_en, data_serial_in, data_parallel_rd_enable,
     data_parallel_out, buffer_full);
  input clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable;
  output [7:0] data_parallel_out;
  output buffer_full;
  wire clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable;
  wire [7:0] data_parallel_out;
  wire buffer_full;
  wire [4:0] buffer_full_counter;
  wire [7:0] memory;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_36, n_37, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47;
  AND2X6 g236(.A (n_45), .B (n_46), .Y (n_47));
  NOR2BX1 g237(.AN (buffer_full_counter[3]), .B
       (buffer_full_counter[2]), .Y (n_46));
  NOR2XL g238(.A (buffer_full_counter[0]), .B (buffer_full_counter[1]),
       .Y (n_45));
  CLKBUFX20 drc_bufs(.A (n_47), .Y (buffer_full));
  DFFHQX1 \buffer_full_counter_reg[2] (.CK (clk), .D (n_34), .Q
       (buffer_full_counter[2]));
  DFFHQX1 \buffer_full_counter_reg[1] (.CK (clk), .D (n_32), .Q
       (buffer_full_counter[1]));
  NOR2X1 g555(.A (reset), .B (n_31), .Y (n_34));
  DFFHQX1 \buffer_full_counter_reg[3] (.CK (clk), .D (n_33), .Q
       (buffer_full_counter[3]));
  NOR2X1 g557(.A (reset), .B (n_29), .Y (n_33));
  DFFHQX1 \buffer_full_counter_reg[0] (.CK (clk), .D (n_30), .Q
       (buffer_full_counter[0]));
  NOR2X1 g559(.A (reset), .B (n_28), .Y (n_32));
  AOI22X1 g560(.A0 (buffer_full_counter[2]), .A1 (n_26), .B0
       (buffer_full_counter[1]), .B1 (n_25), .Y (n_31));
  NOR2X1 g561(.A (reset), .B (n_27), .Y (n_30));
  AOI22X1 g562(.A0 (buffer_full_counter[1]), .A1 (n_23), .B0
       (buffer_full_counter[3]), .B1 (n_12), .Y (n_29));
  MX2X1 g563(.A (n_11), .B (n_19), .S0 (buffer_full_counter[1]), .Y
       (n_28));
  DFFHQX8 \data_parallel_out_reg[7] (.CK (clk), .D (n_14), .Q (n_44));
  DFFHQX8 \data_parallel_out_reg[0] (.CK (clk), .D (n_22), .Q (n_36));
  DFFHQX8 \data_parallel_out_reg[1] (.CK (clk), .D (n_21), .Q (n_37));
  DFFHQX8 \data_parallel_out_reg[2] (.CK (clk), .D (n_20), .Q (n_39));
  DFFHQX8 \data_parallel_out_reg[3] (.CK (clk), .D (n_18), .Q (n_40));
  DFFHQX8 \data_parallel_out_reg[4] (.CK (clk), .D (n_17), .Q (n_41));
  DFFHQX8 \data_parallel_out_reg[5] (.CK (clk), .D (n_16), .Q (n_42));
  DFFHQX8 \data_parallel_out_reg[6] (.CK (clk), .D (n_15), .Q (n_43));
  DFFHQX1 \memory_reg[0] (.CK (clk), .D (n_24), .Q (memory[0]));
  AOI21X1 g573(.A0 (buffer_full_counter[0]), .A1 (n_12), .B0 (n_13), .Y
       (n_27));
  OAI21X1 g574(.A0 (buffer_full_counter[1]), .A1 (n_0), .B0 (n_19), .Y
       (n_26));
  SDFFQX1 \memory_reg[2] (.CK (clk), .D (memory[3]), .SI (memory[2]),
       .SE (n_1), .Q (memory[2]));
  SDFFQX1 \memory_reg[5] (.CK (clk), .D (memory[6]), .SI (memory[5]),
       .SE (n_1), .Q (memory[5]));
  SDFFQX1 \memory_reg[6] (.CK (clk), .D (memory[7]), .SI (memory[6]),
       .SE (n_1), .Q (memory[6]));
  SDFFQX1 \memory_reg[7] (.CK (clk), .D (data_serial_in), .SI
       (memory[7]), .SE (n_1), .Q (memory[7]));
  SDFFQX1 \memory_reg[3] (.CK (clk), .D (memory[4]), .SI (memory[3]),
       .SE (n_1), .Q (memory[3]));
  SDFFQX1 \memory_reg[1] (.CK (clk), .D (memory[2]), .SI (memory[1]),
       .SE (n_1), .Q (memory[1]));
  SDFFQX1 \memory_reg[4] (.CK (clk), .D (memory[5]), .SI (memory[4]),
       .SE (n_1), .Q (memory[4]));
  NOR2X1 g582(.A (buffer_full_counter[2]), .B (n_11), .Y (n_25));
  NOR2X1 g583(.A (reset), .B (n_2), .Y (n_24));
  NOR2BX1 g584(.AN (buffer_full_counter[2]), .B (n_11), .Y (n_23));
  NOR2X1 g585(.A (reset), .B (n_9), .Y (n_22));
  NOR2X1 g586(.A (reset), .B (n_10), .Y (n_21));
  NOR2X1 g587(.A (reset), .B (n_8), .Y (n_20));
  NOR2X1 g588(.A (reset), .B (n_7), .Y (n_18));
  NOR2X1 g589(.A (reset), .B (n_6), .Y (n_17));
  NOR2X1 g590(.A (reset), .B (n_5), .Y (n_16));
  NOR2X1 g591(.A (reset), .B (n_4), .Y (n_15));
  NOR2X1 g592(.A (reset), .B (n_3), .Y (n_14));
  NOR2X1 g593(.A (n_13), .B (n_12), .Y (n_19));
  MXI2XL g594(.A (n_37), .B (memory[1]), .S0 (data_parallel_rd_enable),
       .Y (n_10));
  MXI2XL g595(.A (n_36), .B (memory[0]), .S0 (data_parallel_rd_enable),
       .Y (n_9));
  MXI2XL g596(.A (n_39), .B (memory[2]), .S0 (data_parallel_rd_enable),
       .Y (n_8));
  NOR2X1 g597(.A (buffer_full_counter[0]), .B (n_0), .Y (n_13));
  NOR2BX1 g598(.AN (n_0), .B (data_parallel_rd_enable), .Y (n_12));
  NAND2BX1 g599(.AN (n_0), .B (buffer_full_counter[0]), .Y (n_11));
  MXI2XL g600(.A (n_40), .B (memory[3]), .S0 (data_parallel_rd_enable),
       .Y (n_7));
  MXI2XL g601(.A (n_41), .B (memory[4]), .S0 (data_parallel_rd_enable),
       .Y (n_6));
  MXI2XL g602(.A (n_42), .B (memory[5]), .S0 (data_parallel_rd_enable),
       .Y (n_5));
  MXI2XL g603(.A (n_43), .B (memory[6]), .S0 (data_parallel_rd_enable),
       .Y (n_4));
  MXI2XL g604(.A (n_44), .B (memory[7]), .S0 (data_parallel_rd_enable),
       .Y (n_3));
  MXI2XL g605(.A (memory[0]), .B (memory[1]), .S0 (data_serial_wr_en),
       .Y (n_2));
  NAND2BX4 g606(.AN (reset), .B (data_serial_wr_en), .Y (n_1));
  NAND2BX2 g607(.AN (buffer_full_counter[3]), .B (data_serial_wr_en),
       .Y (n_0));
  CLKBUFX20 drc_bufs610(.A (n_44), .Y (data_parallel_out[7]));
  CLKBUFX20 drc_bufs613(.A (n_43), .Y (data_parallel_out[6]));
  CLKBUFX20 drc_bufs616(.A (n_41), .Y (data_parallel_out[4]));
  CLKBUFX20 drc_bufs619(.A (n_36), .Y (data_parallel_out[0]));
  CLKBUFX20 drc_bufs622(.A (n_37), .Y (data_parallel_out[1]));
  CLKBUFX20 drc_bufs625(.A (n_39), .Y (data_parallel_out[2]));
  CLKBUFX20 drc_bufs628(.A (n_40), .Y (data_parallel_out[3]));
  CLKBUFX20 drc_bufs631(.A (n_42), .Y (data_parallel_out[5]));
endmodule

module
     rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1(clk,
     reset, sampling_tick_middle, sampling_tick_end, tick_start,
     rx_data, data_out_to_buffer, data_valid_to_buffer, parity_error,
     stop_bit_error);
  input clk, reset, sampling_tick_middle, sampling_tick_end, rx_data;
  output tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire clk, reset, sampling_tick_middle, sampling_tick_end, rx_data;
  wire tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire [3:0] state;
  wire [2:0] data_bit_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, parity;
  DFFHQX1 \state_reg[0] (.CK (clk), .D (n_59), .Q (state[0]));
  DFFHQX8 parity_error_reg(.CK (clk), .D (n_57), .Q (n_61));
  AOI2BB1X1 g2546(.A0N (n_31), .A1N (n_55), .B0 (reset), .Y (n_59));
  DFFHQX8 stop_bit_error_reg(.CK (clk), .D (n_58), .Q (n_60));
  NOR2X1 g2548(.A (reset), .B (n_56), .Y (n_58));
  OAI33X1 g2549(.A0 (reset), .A1 (n_4), .A2 (n_49), .B0 (n_19), .B1
       (reset), .B2 (n_27), .Y (n_57));
  DFFHQX1 \data_bit_counter_reg[2] (.CK (clk), .D (n_53), .Q
       (data_bit_counter[2]));
  DFFHQX1 \data_bit_counter_reg[0] (.CK (clk), .D (n_52), .Q
       (data_bit_counter[0]));
  DFFQX2 \state_reg[1] (.CK (clk), .D (n_50), .Q (state[1]));
  AOI22X1 g2553(.A0 (n_60), .A1 (n_42), .B0 (n_2), .B1 (n_38), .Y
       (n_56));
  OAI221X1 g2554(.A0 (n_1), .A1 (n_18), .B0 (n_8), .B1 (n_39), .C0
       (n_15), .Y (n_55));
  DFFHQX1 data_valid_to_buffer_reg(.CK (clk), .D (n_54), .Q
       (data_valid_to_buffer));
  DFFHQX1 \data_bit_counter_reg[1] (.CK (clk), .D (n_51), .Q
       (data_bit_counter[1]));
  AOI21X1 g2557(.A0 (n_25), .A1 (n_40), .B0 (reset), .Y (n_54));
  DFFHQX1 tick_start_reg(.CK (clk), .D (n_45), .Q (tick_start));
  DFFHQX1 data_out_to_buffer_reg(.CK (clk), .D (n_47), .Q
       (data_out_to_buffer));
  DFFHQX1 parity_reg(.CK (clk), .D (n_48), .Q (parity));
  DFFQX1 \state_reg[2] (.CK (clk), .D (n_46), .Q (state[2]));
  AOI21X1 g2562(.A0 (n_6), .A1 (n_37), .B0 (reset), .Y (n_53));
  NOR2BX1 g2563(.AN (n_43), .B (reset), .Y (n_52));
  NOR2X1 g2564(.A (reset), .B (n_44), .Y (n_51));
  NOR2X1 g2565(.A (reset), .B (n_41), .Y (n_50));
  NOR4X1 g2566(.A (n_11), .B (n_26), .C (n_21), .D (n_29), .Y (n_49));
  NOR2X1 g2567(.A (reset), .B (n_36), .Y (n_48));
  NOR2X1 g2568(.A (reset), .B (n_35), .Y (n_47));
  AOI31X1 g2569(.A0 (n_5), .A1 (n_20), .A2 (n_27), .B0 (reset), .Y
       (n_46));
  AOI2BB1X1 g2570(.A0N (tick_start), .A1N (n_31), .B0 (reset), .Y
       (n_45));
  AOI21X1 g2571(.A0 (data_bit_counter[1]), .A1 (n_28), .B0 (n_30), .Y
       (n_44));
  OAI221X1 g2572(.A0 (data_bit_counter[0]), .A1 (n_25), .B0 (n_13), .B1
       (n_6), .C0 (n_34), .Y (n_43));
  OAI211X1 g2573(.A0 (n_14), .A1 (n_12), .B0 (n_7), .C0 (n_33), .Y
       (n_42));
  AOI22X1 g2574(.A0 (n_11), .A1 (n_18), .B0 (state[1]), .B1 (n_32), .Y
       (n_41));
  OAI21X1 g2575(.A0 (n_11), .A1 (n_22), .B0 (data_valid_to_buffer), .Y
       (n_40));
  OA21X1 g2576(.A0 (state[0]), .A1 (n_23), .B0 (n_12), .Y (n_39));
  AO21X1 g2577(.A0 (n_0), .A1 (n_26), .B0 (n_21), .Y (n_38));
  AOI2BB2X1 g2578(.A0N (n_13), .A1N (n_25), .B0 (n_10), .B1
       (data_bit_counter[2]), .Y (n_37));
  AOI22X1 g2579(.A0 (n_19), .A1 (n_24), .B0 (parity), .B1 (n_17), .Y
       (n_36));
  AOI22X1 g2580(.A0 (rx_data), .A1 (n_24), .B0 (data_out_to_buffer),
       .B1 (n_17), .Y (n_35));
  NAND2X1 g2581(.A (data_bit_counter[0]), .B (n_17), .Y (n_34));
  NAND2X1 g2582(.A (state[1]), .B (n_20), .Y (n_33));
  NAND2X1 g2583(.A (state[0]), .B (n_18), .Y (n_32));
  NOR3BX1 g2584(.AN (data_bit_counter[0]), .B (data_bit_counter[1]), .C
       (n_25), .Y (n_30));
  OAI22X1 g2585(.A0 (sampling_tick_middle), .A1 (n_7), .B0 (state[0]),
       .B1 (n_0), .Y (n_29));
  OAI211X1 g2586(.A0 (data_bit_counter[0]), .A1 (n_0), .B0 (n_6), .C0
       (n_16), .Y (n_28));
  NOR3X1 g2587(.A (rx_data), .B (state[1]), .C (n_10), .Y (n_31));
  INVX1 g2588(.A (n_25), .Y (n_24));
  NAND2BX1 g2589(.AN (n_13), .B (data_bit_counter[2]), .Y (n_23));
  AND2X1 g2590(.A (n_14), .B (state[2]), .Y (n_22));
  OR2X1 g2591(.A (n_8), .B (n_7), .Y (n_27));
  NOR2X1 g2592(.A (n_1), .B (n_9), .Y (n_26));
  OR2X1 g2593(.A (n_8), .B (n_10), .Y (n_25));
  INVX1 g2594(.A (n_16), .Y (n_17));
  NAND2X1 g2595(.A (state[2]), .B (n_11), .Y (n_15));
  NOR2BX1 g2596(.AN (sampling_tick_middle), .B (n_12), .Y (n_21));
  OAI2BB1X1 g2597(.A0N (sampling_tick_end), .A1N (state[0]), .B0
       (state[2]), .Y (n_20));
  XNOR2X1 g2598(.A (parity), .B (n_2), .Y (n_19));
  OAI2BB1X1 g2599(.A0N (sampling_tick_middle), .A1N (n_3), .B0 (n_9),
       .Y (n_18));
  AOI2BB1X1 g2600(.A0N (sampling_tick_middle), .A1N (n_0), .B0 (n_10),
       .Y (n_16));
  OR2X1 g2601(.A (sampling_tick_middle), .B (state[1]), .Y (n_14));
  NAND2X1 g2602(.A (data_bit_counter[1]), .B (data_bit_counter[0]), .Y
       (n_13));
  NAND2X1 g2603(.A (state[2]), .B (n_1), .Y (n_12));
  NOR2X1 g2604(.A (state[1]), .B (n_1), .Y (n_11));
  OR2X1 g2605(.A (state[2]), .B (state[0]), .Y (n_10));
  NAND2X1 g2606(.A (state[2]), .B (n_0), .Y (n_5));
  NAND2X1 g2607(.A (sampling_tick_end), .B (state[2]), .Y (n_9));
  NAND2X1 g2608(.A (sampling_tick_middle), .B (state[1]), .Y (n_8));
  NAND2X1 g2609(.A (state[0]), .B (n_3), .Y (n_7));
  NAND2X1 g2610(.A (data_bit_counter[2]), .B (state[1]), .Y (n_6));
  INVX1 g2611(.A (n_61), .Y (n_4));
  INVX1 g2612(.A (state[2]), .Y (n_3));
  INVX1 g2613(.A (rx_data), .Y (n_2));
  INVX2 g2614(.A (state[0]), .Y (n_1));
  INVX1 g2615(.A (state[1]), .Y (n_0));
  CLKBUFX20 drc_bufs2618(.A (n_61), .Y (parity_error));
  CLKBUFX20 drc_bufs2621(.A (n_60), .Y (stop_bit_error));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_2(clk, reset,
     start, tick_16_8, tick_16_16);
  input clk, reset, start;
  output tick_16_8, tick_16_16;
  wire clk, reset, start;
  wire tick_16_8, tick_16_16;
  wire [10:0] counter;
  wire n_0, n_1, n_2, n_4, n_5, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_45, n_46, n_88, n_89, n_91, n_95, n_96;
  wire n_97;
  DFFHQX1 tick_16_16_reg(.CK (clk), .D (n_43), .Q (tick_16_16));
  NOR3X1 g472(.A (reset), .B (n_88), .C (n_42), .Y (n_43));
  NOR2X1 g473(.A (n_88), .B (n_42), .Y (n_89));
  NAND3BX2 g475(.AN (n_41), .B (counter[8]), .C (counter[9]), .Y
       (n_42));
  AOI31X1 g476(.A0 (counter[5]), .A1 (counter[6]), .A2 (n_40), .B0
       (counter[7]), .Y (n_41));
  NOR2X1 g477(.A (n_91), .B (n_46), .Y (n_45));
  OR3X1 g478(.A (counter[3]), .B (counter[2]), .C (counter[4]), .Y
       (n_40));
  NAND2X1 g479(.A (counter[5]), .B (counter[4]), .Y (n_46));
  INVX1 g482(.A (counter[6]), .Y (n_91));
  INVX1 g484(.A (start), .Y (n_88));
  DFFHQX1 \counter_reg[9] (.CK (clk), .D (n_39), .Q (counter[9]));
  NOR3X1 g980(.A (reset), .B (n_4), .C (n_37), .Y (n_39));
  DFFHQX1 \counter_reg[8] (.CK (clk), .D (n_38), .Q (counter[8]));
  NOR3BX1 g982(.AN (n_36), .B (reset), .C (n_4), .Y (n_38));
  XNOR2X1 g983(.A (counter[9]), .B (n_35), .Y (n_37));
  ADDHX1 g984(.A (counter[8]), .B (n_31), .CO (n_35), .S (n_36));
  DFFHQX1 \counter_reg[6] (.CK (clk), .D (n_34), .Q (counter[6]));
  DFFHQX1 \counter_reg[5] (.CK (clk), .D (n_33), .Q (counter[5]));
  NOR3BX1 g987(.AN (n_30), .B (reset), .C (n_4), .Y (n_34));
  DFFHQX1 \counter_reg[7] (.CK (clk), .D (n_32), .Q (counter[7]));
  NOR2BX1 g989(.AN (n_26), .B (reset), .Y (n_33));
  DFFHQX1 \counter_reg[4] (.CK (clk), .D (n_28), .Q (counter[4]));
  NOR2X1 g991(.A (reset), .B (n_27), .Y (n_32));
  AND2X1 g992(.A (n_29), .B (counter[7]), .Y (n_31));
  ADDHX1 g993(.A (counter[6]), .B (n_20), .CO (n_29), .S (n_30));
  NOR2BX1 g994(.AN (n_24), .B (reset), .Y (n_28));
  AOI31X1 g995(.A0 (n_2), .A1 (n_45), .A2 (n_0), .B0 (n_25), .Y (n_27));
  OAI32X1 g996(.A0 (counter[5]), .A1 (n_1), .A2 (n_21), .B0 (n_23), .B1
       (n_4), .Y (n_26));
  DFFHQX1 \counter_reg[3] (.CK (clk), .D (n_22), .Q (counter[3]));
  AOI211X1 g998(.A0 (n_45), .A1 (n_19), .B0 (n_2), .C0 (n_4), .Y
       (n_25));
  OAI32X1 g999(.A0 (n_1), .A1 (n_19), .A2 (n_4), .B0 (counter[4]), .B1
       (n_21), .Y (n_24));
  OAI2BB1X1 g1000(.A0N (counter[4]), .A1N (n_19), .B0 (counter[5]), .Y
       (n_23));
  NOR3BX1 g1001(.AN (n_18), .B (reset), .C (n_4), .Y (n_22));
  DFFHQX1 tick_16_8_reg(.CK (clk), .D (n_17), .Q (tick_16_8));
  NAND2X1 g1004(.A (n_19), .B (n_95), .Y (n_21));
  NOR2BX1 g1005(.AN (n_19), .B (n_46), .Y (n_20));
  ADDHX1 g1006(.A (counter[3]), .B (n_13), .CO (n_19), .S (n_18));
  DFFHQX1 \counter_reg[2] (.CK (clk), .D (n_16), .Q (counter[2]));
  NOR2X1 g1008(.A (reset), .B (n_15), .Y (n_17));
  NOR3BX1 g1009(.AN (n_14), .B (reset), .C (n_4), .Y (n_16));
  AOI22X1 g1010(.A0 (n_8), .A1 (n_12), .B0 (tick_16_8), .B1 (n_89), .Y
       (n_15));
  ADDHX1 g1011(.A (counter[2]), .B (n_9), .CO (n_13), .S (n_14));
  DFFHQX1 \counter_reg[1] (.CK (clk), .D (n_11), .Q (counter[1]));
  NOR4BBX1 g1013(.AN (counter[1]), .BN (counter[5]), .C (n_88), .D
       (n_97), .Y (n_12));
  NOR3BX1 g1014(.AN (n_10), .B (reset), .C (n_4), .Y (n_11));
  ADDHX1 g1015(.A (counter[1]), .B (counter[0]), .CO (n_9), .S (n_10));
  DFFQXL \counter_reg[0] (.CK (clk), .D (n_5), .Q (counter[0]));
  NOR4BX1 g1017(.AN (counter[8]), .B (counter[0]), .C (n_2), .D (n_1),
       .Y (n_8));
  NOR3X1 g1020(.A (reset), .B (counter[0]), .C (n_4), .Y (n_5));
  INVX2 g1021(.A (n_95), .Y (n_4));
  INVX1 g1025(.A (counter[7]), .Y (n_2));
  INVX1 g1026(.A (counter[4]), .Y (n_1));
  INVX1 drc_bufs1028(.A (n_21), .Y (n_0));
  NOR2BX1 g1030(.AN (n_42), .B (n_88), .Y (n_95));
  INVXL g3(.A (n_96), .Y (n_97));
  NOR4BX1 g1031(.AN (n_91), .B (counter[3]), .C (counter[2]), .D
       (counter[9]), .Y (n_96));
endmodule

module
     rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1(clk,
     reset, rx_data, data_parallel_out, data_parallel_rd_enable,
     rx_buffer_full, parity_error, stop_bit_error);
  input clk, reset, rx_data, data_parallel_rd_enable;
  output [7:0] data_parallel_out;
  output rx_buffer_full, parity_error, stop_bit_error;
  wire clk, reset, rx_data, data_parallel_rd_enable;
  wire [7:0] data_parallel_out;
  wire rx_buffer_full, parity_error, stop_bit_error;
  wire data_out_to_buffer, data_valid_to_buffer, sampling_tick_end,
       sampling_tick_middle, tick_start;
  rx_buffer_WORD_SIZE8_NO_OF_WORDS1_1 ins_rx_buffer(.clk (clk), .reset
       (reset), .data_serial_wr_en (data_valid_to_buffer),
       .data_serial_in (data_out_to_buffer), .data_parallel_rd_enable
       (data_parallel_rd_enable), .data_parallel_out
       (data_parallel_out), .buffer_full (rx_buffer_full));
  rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1
       ins_rx_fsm(.clk (clk), .reset (reset), .sampling_tick_middle
       (sampling_tick_middle), .sampling_tick_end (sampling_tick_end),
       .tick_start (tick_start), .rx_data (rx_data),
       .data_out_to_buffer (data_out_to_buffer), .data_valid_to_buffer
       (data_valid_to_buffer), .parity_error (parity_error),
       .stop_bit_error (stop_bit_error));
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_2
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (sampling_tick_end));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_3(clk, reset,
     start, tick_16_8, tick_16_16);
  input clk, reset, start;
  output tick_16_8, tick_16_16;
  wire clk, reset, start;
  wire tick_16_8, tick_16_16;
  wire [10:0] counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37;
  DFFHQX1 \counter_reg[9] (.CK (clk), .D (n_37), .Q (counter[9]));
  DFFQXL \counter_reg[8] (.CK (clk), .D (n_36), .Q (counter[8]));
  NOR3X1 g1027(.A (reset), .B (n_0), .C (n_35), .Y (n_37));
  NOR3BX1 g1028(.AN (n_34), .B (reset), .C (n_0), .Y (n_36));
  NOR2X1 g1029(.A (counter[9]), .B (n_33), .Y (n_35));
  ADDHX1 g1030(.A (counter[8]), .B (n_30), .CO (n_33), .S (n_34));
  DFFQXL \counter_reg[7] (.CK (clk), .D (n_32), .Q (counter[7]));
  NOR3BX1 g1032(.AN (n_31), .B (reset), .C (n_0), .Y (n_32));
  DFFHQX1 \counter_reg[5] (.CK (clk), .D (n_29), .Q (counter[5]));
  ADDHX1 g1034(.A (counter[7]), .B (n_23), .CO (n_30), .S (n_31));
  DFFQXL \counter_reg[6] (.CK (clk), .D (n_27), .Q (counter[6]));
  NOR3X1 g1036(.A (reset), .B (n_25), .C (n_0), .Y (n_29));
  DFFHQX1 tick_16_8_reg(.CK (clk), .D (n_28), .Q (tick_16_8));
  DFFHQX1 \counter_reg[4] (.CK (clk), .D (n_26), .Q (counter[4]));
  NOR3BX1 g1039(.AN (start), .B (reset), .C (n_22), .Y (n_28));
  NOR3BX1 g1040(.AN (n_24), .B (reset), .C (n_0), .Y (n_27));
  NOR3BX1 g1041(.AN (n_21), .B (reset), .C (n_0), .Y (n_26));
  XNOR2X1 g1042(.A (counter[5]), .B (n_20), .Y (n_25));
  ADDHX1 g1043(.A (counter[6]), .B (n_17), .CO (n_23), .S (n_24));
  AOI22X1 g1044(.A0 (counter[8]), .A1 (n_19), .B0 (tick_16_8), .B1
       (n_10), .Y (n_22));
  ADDHX1 g1045(.A (counter[4]), .B (n_16), .CO (n_20), .S (n_21));
  DFFHQX1 \counter_reg[3] (.CK (clk), .D (n_18), .Q (counter[3]));
  NOR4BX1 g1047(.AN (counter[7]), .B (counter[0]), .C (counter[6]), .D
       (n_11), .Y (n_19));
  NOR3BX1 g1048(.AN (n_15), .B (reset), .C (n_0), .Y (n_18));
  DFFHQX1 \counter_reg[1] (.CK (clk), .D (n_13), .Q (counter[1]));
  DFFHQX1 \counter_reg[2] (.CK (clk), .D (n_12), .Q (counter[2]));
  NOR2BX1 g1051(.AN (n_16), .B (n_3), .Y (n_17));
  DFFQXL \counter_reg[0] (.CK (clk), .D (n_14), .Q (counter[0]));
  ADDHX1 g1053(.A (counter[3]), .B (n_8), .CO (n_16), .S (n_15));
  NOR3X1 g1054(.A (reset), .B (counter[0]), .C (n_0), .Y (n_14));
  NOR3BX1 g1055(.AN (n_6), .B (reset), .C (n_0), .Y (n_13));
  NOR3BX1 g1056(.AN (n_9), .B (reset), .C (n_0), .Y (n_12));
  OR4X1 g1058(.A (n_1), .B (n_3), .C (n_2), .D (n_10), .Y (n_11));
  AND3XL g1059(.A (counter[9]), .B (counter[8]), .C (n_7), .Y (n_10));
  ADDHX1 g1060(.A (counter[2]), .B (n_5), .CO (n_8), .S (n_9));
  AO21X1 g1061(.A0 (counter[6]), .A1 (n_4), .B0 (counter[7]), .Y (n_7));
  ADDHX1 g1062(.A (counter[1]), .B (counter[0]), .CO (n_5), .S (n_6));
  OAI2BB1X1 g1063(.A0N (counter[5]), .A1N (n_2), .B0 (n_3), .Y (n_4));
  NAND2X1 g1064(.A (counter[4]), .B (counter[5]), .Y (n_3));
  OR2X1 g1065(.A (counter[3]), .B (counter[2]), .Y (n_2));
  INVX1 g1067(.A (counter[1]), .Y (n_1));
  NAND2BX4 g2(.AN (n_10), .B (start), .Y (n_0));
endmodule

module tx_buffer_WORD_SIZE8_NO_OF_WORDS1_1(clk, reset,
     data_parallel_in, data_parallel_wr_enable, data_serial_rd_enable,
     data_serial_out, empty);
  input clk, reset, data_parallel_wr_enable, data_serial_rd_enable;
  input [7:0] data_parallel_in;
  output data_serial_out, empty;
  wire clk, reset, data_parallel_wr_enable, data_serial_rd_enable;
  wire [7:0] data_parallel_in;
  wire data_serial_out, empty;
  wire [4:0] buffer_empty_counter;
  wire [7:0] memory;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38;
  NOR3X2 g386(.A (buffer_empty_counter[0]), .B
       (buffer_empty_counter[1]), .C (n_38), .Y (empty));
  OR3X1 g387(.A (buffer_empty_counter[2]), .B
       (buffer_empty_counter[3]), .C (buffer_empty_counter[4]), .Y
       (n_38));
  DFFHQX1 \buffer_empty_counter_reg[4] (.CK (clk), .D (n_37), .Q
       (buffer_empty_counter[4]));
  DFFHQX1 \buffer_empty_counter_reg[3] (.CK (clk), .D (n_36), .Q
       (buffer_empty_counter[3]));
  NOR3X1 g908(.A (reset), .B (n_35), .C (data_parallel_wr_enable), .Y
       (n_37));
  OR4X1 g909(.A (reset), .B (n_33), .C (n_32), .D
       (data_parallel_wr_enable), .Y (n_36));
  DFFHQX1 \buffer_empty_counter_reg[2] (.CK (clk), .D (n_34), .Q
       (buffer_empty_counter[2]));
  XNOR2X1 g911(.A (buffer_empty_counter[4]), .B (n_32), .Y (n_35));
  NOR3X1 g912(.A (reset), .B (n_30), .C (data_parallel_wr_enable), .Y
       (n_34));
  NOR2BX1 g913(.AN (buffer_empty_counter[3]), .B (n_29), .Y (n_33));
  NOR2BX1 g914(.AN (n_29), .B (buffer_empty_counter[3]), .Y (n_32));
  DFFHQX1 \buffer_empty_counter_reg[1] (.CK (clk), .D (n_31), .Q
       (buffer_empty_counter[1]));
  NOR3X1 g916(.A (reset), .B (n_27), .C (data_parallel_wr_enable), .Y
       (n_31));
  AOI21X1 g917(.A0 (buffer_empty_counter[2]), .A1 (n_26), .B0 (n_29),
       .Y (n_30));
  NOR2X1 g918(.A (buffer_empty_counter[2]), .B (n_26), .Y (n_29));
  DFFHQX1 \buffer_empty_counter_reg[0] (.CK (clk), .D (n_28), .Q
       (buffer_empty_counter[0]));
  DFFHQX1 \memory_reg[1] (.CK (clk), .D (n_23), .Q (memory[1]));
  DFFHQX1 \memory_reg[2] (.CK (clk), .D (n_24), .Q (memory[2]));
  DFFHQX1 \memory_reg[5] (.CK (clk), .D (n_21), .Q (memory[5]));
  NOR3X1 g923(.A (reset), .B (n_12), .C (data_parallel_wr_enable), .Y
       (n_28));
  XNOR2X1 g924(.A (buffer_empty_counter[1]), .B (n_7), .Y (n_27));
  DFFHQX1 \memory_reg[7] (.CK (clk), .D (n_22), .Q (memory[7]));
  DFFHQX1 \memory_reg[3] (.CK (clk), .D (n_20), .Q (memory[3]));
  DFFHQX1 \memory_reg[0] (.CK (clk), .D (n_19), .Q (memory[0]));
  DFFHQX1 \memory_reg[6] (.CK (clk), .D (n_15), .Q (memory[6]));
  DFFHQX1 \memory_reg[4] (.CK (clk), .D (n_18), .Q (memory[4]));
  OAI2BB1X1 g930(.A0N (data_parallel_in[2]), .A1N (n_2), .B0 (n_17), .Y
       (n_24));
  OAI2BB1X1 g931(.A0N (data_parallel_in[1]), .A1N (n_2), .B0 (n_16), .Y
       (n_23));
  AO22X1 g932(.A0 (n_13), .A1 (memory[7]), .B0 (data_parallel_in[7]),
       .B1 (n_2), .Y (n_22));
  OAI2BB1X1 g933(.A0N (data_parallel_in[5]), .A1N (n_2), .B0 (n_14), .Y
       (n_21));
  NAND2BX1 g934(.AN (buffer_empty_counter[1]), .B (n_7), .Y (n_26));
  OAI2BB1X1 g935(.A0N (n_0), .A1N (memory[3]), .B0 (n_9), .Y (n_20));
  OAI2BB1X1 g936(.A0N (n_0), .A1N (memory[0]), .B0 (n_10), .Y (n_19));
  OAI2BB1X1 g937(.A0N (n_0), .A1N (memory[4]), .B0 (n_11), .Y (n_18));
  SDFFQX1 data_serial_out_reg(.CK (clk), .D (n_5), .SI (memory[0]), .SE
       (data_serial_rd_enable), .Q (data_serial_out));
  AOI22X1 g939(.A0 (n_0), .A1 (memory[2]), .B0 (memory[3]), .B1
       (data_serial_rd_enable), .Y (n_17));
  AOI22X1 g940(.A0 (n_0), .A1 (memory[1]), .B0 (memory[2]), .B1
       (data_serial_rd_enable), .Y (n_16));
  OAI2BB1X1 g941(.A0N (n_0), .A1N (memory[6]), .B0 (n_8), .Y (n_15));
  AOI22X1 g942(.A0 (n_0), .A1 (memory[5]), .B0 (memory[6]), .B1
       (data_serial_rd_enable), .Y (n_14));
  OAI21X1 g943(.A0 (reset), .A1 (n_1), .B0 (n_6), .Y (n_13));
  AOI21X1 g944(.A0 (buffer_empty_counter[0]), .A1 (n_3), .B0 (n_7), .Y
       (n_12));
  AOI22X1 g945(.A0 (data_parallel_in[4]), .A1 (n_2), .B0 (memory[5]),
       .B1 (data_serial_rd_enable), .Y (n_11));
  AOI22X1 g946(.A0 (data_parallel_in[0]), .A1 (n_2), .B0 (memory[1]),
       .B1 (data_serial_rd_enable), .Y (n_10));
  AOI22X1 g947(.A0 (data_parallel_in[3]), .A1 (n_2), .B0 (memory[4]),
       .B1 (data_serial_rd_enable), .Y (n_9));
  AOI22X1 g948(.A0 (data_parallel_in[6]), .A1 (n_2), .B0 (memory[7]),
       .B1 (data_serial_rd_enable), .Y (n_8));
  NOR2X1 g949(.A (buffer_empty_counter[0]), .B (n_3), .Y (n_7));
  INVX1 g950(.A (n_0), .Y (n_6));
  NOR2BX1 g952(.AN (data_serial_out), .B (reset), .Y (n_5));
  NOR2X1 g953(.A (reset), .B (data_serial_rd_enable), .Y (n_4));
  OR2X1 g954(.A (n_1), .B (empty), .Y (n_3));
  AND2X1 g955(.A (data_parallel_wr_enable), .B (n_1), .Y (n_2));
  INVX1 g960(.A (data_serial_rd_enable), .Y (n_1));
  NOR2BX2 g2(.AN (n_4), .B (data_parallel_wr_enable), .Y (n_0));
endmodule

module
     tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1(clk,
     reset, empty, sampling_tick_middle, sampling_tick_end, tick_start,
     data_parallel_wr_enable, tx_busy, tx_data, buffer_rd_enable,
     buffer_data);
  input clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data;
  output tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data;
  wire tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire [2:0] data_bit_counter;
  wire [3:0] state;
  wire delay_data_parallel_wr_enable, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, parity, tem_buffer_data;
  DFFQX2 buffer_rd_enable_reg(.CK (clk), .D (n_63), .Q
       (buffer_rd_enable));
  DFFHQX1 \data_bit_counter_reg[0] (.CK (clk), .D (n_70), .Q
       (data_bit_counter[0]));
  DFFHQX1 \data_bit_counter_reg[1] (.CK (clk), .D (n_76), .Q
       (data_bit_counter[1]));
  DFFHQX1 \data_bit_counter_reg[2] (.CK (clk), .D (n_68), .Q
       (data_bit_counter[2]));
  DFFHQX1 delay_data_parallel_wr_enable_reg(.CK (clk), .D
       (data_parallel_wr_enable), .Q (delay_data_parallel_wr_enable));
  DFFHQX1 parity_reg(.CK (clk), .D (n_78), .Q (parity));
  DFFHQX1 \state_reg[0] (.CK (clk), .D (n_77), .Q (state[0]));
  DFFHQX1 \state_reg[1] (.CK (clk), .D (n_71), .Q (state[1]));
  DFFQX2 \state_reg[2] (.CK (clk), .D (n_75), .Q (state[2]));
  DFFQX1 \state_reg[3] (.CK (clk), .D (n_51), .Q (state[3]));
  DFFHQX1 tem_buffer_data_reg(.CK (clk), .D (n_74), .Q
       (tem_buffer_data));
  DFFHQX1 tick_start_reg(.CK (clk), .D (n_66), .Q (tick_start));
  DFFHQX8 tx_busy_reg(.CK (clk), .D (n_61), .Q (n_79));
  DFFHQX1 tx_data_reg(.CK (clk), .D (n_72), .Q (tx_data));
  NOR2X1 g2035(.A (reset), .B (n_73), .Y (n_78));
  OAI22X1 g2036(.A0 (reset), .A1 (n_69), .B0 (reset), .B1 (n_30), .Y
       (n_77));
  AOI21X1 g2041(.A0 (n_48), .A1 (n_64), .B0 (reset), .Y (n_76));
  AOI31X1 g2042(.A0 (n_26), .A1 (n_37), .A2 (n_58), .B0 (reset), .Y
       (n_75));
  AOI21X1 g2043(.A0 (n_42), .A1 (n_67), .B0 (reset), .Y (n_74));
  MX2X1 g2044(.A (n_42), .B (n_65), .S0 (parity), .Y (n_73));
  NAND3X1 g2048(.A (n_60), .B (n_31), .C (n_35), .Y (n_72));
  AOI31X1 g2049(.A0 (n_12), .A1 (n_36), .A2 (n_47), .B0 (reset), .Y
       (n_71));
  NOR2X1 g2050(.A (reset), .B (n_62), .Y (n_70));
  AOI221X1 g2051(.A0 (n_0), .A1 (n_52), .B0 (n_20), .B1 (n_34), .C0
       (n_39), .Y (n_69));
  NOR2X1 g2052(.A (reset), .B (n_56), .Y (n_68));
  NAND2X1 g2053(.A (tem_buffer_data), .B (n_59), .Y (n_67));
  AOI31X1 g2054(.A0 (n_45), .A1 (n_35), .A2 (n_46), .B0 (reset), .Y
       (n_66));
  AOI2BB1X1 g2056(.A0N (buffer_data), .A1N (n_3), .B0 (n_59), .Y
       (n_65));
  OAI2BB1X1 g2057(.A0N (n_16), .A1N (n_55), .B0 (data_bit_counter[1]),
       .Y (n_64));
  NOR2X1 g2058(.A (reset), .B (n_57), .Y (n_63));
  AOI222X1 g2059(.A0 (n_4), .A1 (n_34), .B0 (state[2]), .B1 (n_20), .C0
       (data_bit_counter[0]), .C1 (n_54), .Y (n_62));
  AOI21X1 g2060(.A0 (n_44), .A1 (n_46), .B0 (reset), .Y (n_61));
  AOI211X1 g2061(.A0 (tx_data), .A1 (n_22), .B0 (reset), .C0 (n_50), .Y
       (n_60));
  OA21X1 g2063(.A0 (state[0]), .A1 (n_10), .B0 (n_49), .Y (n_58));
  AOI221X1 g2064(.A0 (n_19), .A1 (n_34), .B0 (buffer_rd_enable), .B1
       (n_21), .C0 (n_43), .Y (n_57));
  AOI31X1 g2065(.A0 (data_bit_counter[0]), .A1 (data_bit_counter[1]),
       .A2 (n_34), .B0 (n_53), .Y (n_56));
  OR3X1 g2066(.A (state[2]), .B (n_25), .C (n_41), .Y (n_59));
  INVX1 g2067(.A (n_54), .Y (n_55));
  OA21X1 g2068(.A0 (n_8), .A1 (n_33), .B0 (data_bit_counter[2]), .Y
       (n_53));
  NAND2X1 g2069(.A (n_21), .B (n_38), .Y (n_52));
  NOR2X1 g2070(.A (reset), .B (n_40), .Y (n_51));
  NAND3X2 g2071(.A (n_3), .B (n_26), .C (n_32), .Y (n_54));
  OAI33X1 g2072(.A0 (state[0]), .A1 (n_14), .A2 (n_15), .B0 (n_13), .B1
       (parity), .B2 (n_24), .Y (n_50));
  OAI211X1 g2073(.A0 (state[0]), .A1 (n_20), .B0 (n_3), .C0 (state[2]),
       .Y (n_49));
  NAND3BX1 g2074(.AN (data_bit_counter[1]), .B (data_bit_counter[0]),
       .C (n_34), .Y (n_48));
  AOI221X1 g2075(.A0 (n_19), .A1 (n_27), .B0 (state[1]), .B1 (n_0), .C0
       (n_23), .Y (n_47));
  NAND2X1 g2076(.A (tick_start), .B (n_31), .Y (n_45));
  NAND2X1 g2077(.A (n_79), .B (n_31), .Y (n_44));
  NOR2X1 g2078(.A (state[2]), .B (n_36), .Y (n_43));
  NAND2BX1 g2079(.AN (n_31), .B (delay_data_parallel_wr_enable), .Y
       (n_46));
  OAI211X1 g2080(.A0 (state[0]), .A1 (n_6), .B0 (n_12), .C0 (n_5), .Y
       (n_41));
  AOI22X1 g2081(.A0 (state[3]), .A1 (n_17), .B0 (state[0]), .B1 (n_18),
       .Y (n_40));
  OAI22X1 g2082(.A0 (sampling_tick_middle), .A1 (n_24), .B0 (n_0), .B1
       (n_26), .Y (n_39));
  AOI31X1 g2083(.A0 (delay_data_parallel_wr_enable), .A1 (n_2), .A2
       (n_1), .B0 (n_29), .Y (n_38));
  NAND2BX1 g2084(.AN (n_37), .B (buffer_data), .Y (n_42));
  OR2X1 g2085(.A (n_0), .B (n_21), .Y (n_37));
  NAND2X1 g2086(.A (sampling_tick_middle), .B (n_25), .Y (n_36));
  OR2X1 g2087(.A (n_8), .B (n_28), .Y (n_35));
  AND2X1 g2088(.A (n_27), .B (n_0), .Y (n_34));
  INVX1 g2089(.A (n_32), .Y (n_33));
  OA21X1 g2090(.A0 (n_0), .A1 (n_12), .B0 (n_28), .Y (n_30));
  NOR3BX1 g2091(.AN (sampling_tick_middle), .B (n_2), .C (n_8), .Y
       (n_29));
  MX2X1 g2092(.A (n_11), .B (n_0), .S0 (n_2), .Y (n_32));
  OR3X1 g2093(.A (state[2]), .B (state[0]), .C (n_7), .Y (n_31));
  INVX1 g2094(.A (n_25), .Y (n_24));
  NOR2X1 g2095(.A (sampling_tick_middle), .B (n_10), .Y (n_23));
  NAND2X1 g2096(.A (sampling_tick_middle), .B (n_6), .Y (n_22));
  NAND2X1 g2097(.A (state[3]), .B (n_11), .Y (n_28));
  NOR2X1 g2098(.A (n_13), .B (n_7), .Y (n_27));
  NAND2X2 g2099(.A (state[2]), .B (n_14), .Y (n_26));
  NOR2X1 g2100(.A (n_0), .B (n_7), .Y (n_25));
  INVX1 g2101(.A (n_20), .Y (n_19));
  NOR2X1 g2102(.A (n_3), .B (n_13), .Y (n_18));
  OR2X1 g2103(.A (n_0), .B (n_8), .Y (n_17));
  OAI21X1 g2104(.A0 (data_bit_counter[2]), .A1 (n_4), .B0 (state[2]),
       .Y (n_16));
  AOI21X1 g2105(.A0 (tem_buffer_data), .A1 (state[2]), .B0 (n_9), .Y
       (n_15));
  OR3X1 g2106(.A (state[2]), .B (n_3), .C (state[3]), .Y (n_21));
  AND3XL g2107(.A (data_bit_counter[2]), .B (data_bit_counter[1]), .C
       (data_bit_counter[0]), .Y (n_20));
  NAND2X1 g2109(.A (sampling_tick_middle), .B (n_2), .Y (n_14));
  NAND2X1 g2110(.A (state[2]), .B (sampling_tick_middle), .Y (n_13));
  NAND2X1 g2111(.A (state[1]), .B (state[3]), .Y (n_12));
  INVX1 g2112(.A (n_9), .Y (n_10));
  INVX1 g2113(.A (n_7), .Y (n_6));
  NAND2X1 g2114(.A (state[3]), .B (empty), .Y (n_5));
  NOR2X1 g2115(.A (n_0), .B (empty), .Y (n_11));
  NOR2X1 g2116(.A (n_3), .B (n_1), .Y (n_9));
  OR2X1 g2117(.A (state[2]), .B (state[1]), .Y (n_8));
  OR2X1 g2118(.A (state[3]), .B (state[1]), .Y (n_7));
  INVX1 g2119(.A (data_bit_counter[0]), .Y (n_4));
  INVX1 g2120(.A (state[1]), .Y (n_3));
  INVX1 g2121(.A (state[3]), .Y (n_2));
  INVX1 g2122(.A (state[2]), .Y (n_1));
  INVX2 g2123(.A (state[0]), .Y (n_0));
  CLKBUFX20 drc_bufs2126(.A (n_79), .Y (tx_busy));
endmodule

module
     tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1(clk,
     reset, data_parallel_in, data_parallel_wr_enable, tx_busy,
     tx_data);
  input clk, reset, data_parallel_wr_enable;
  input [7:0] data_parallel_in;
  output tx_busy, tx_data;
  wire clk, reset, data_parallel_wr_enable;
  wire [7:0] data_parallel_in;
  wire tx_busy, tx_data;
  wire UNCONNECTED_HIER_Z0, data_serial_out, data_serial_rd_enable,
       empty, sampling_tick_end, sampling_tick_middle, tick_start;
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_3
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (sampling_tick_end));
  tx_buffer_WORD_SIZE8_NO_OF_WORDS1_1 ins_tx_buffer(.clk (clk), .reset
       (reset), .data_parallel_in (data_parallel_in),
       .data_parallel_wr_enable (data_parallel_wr_enable),
       .data_serial_rd_enable (data_serial_rd_enable), .data_serial_out
       (data_serial_out), .empty (empty));
  tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1
       ins_tx_fsm(.clk (clk), .reset (reset), .empty (empty),
       .sampling_tick_middle (sampling_tick_middle), .sampling_tick_end
       (UNCONNECTED_HIER_Z0), .tick_start (tick_start),
       .data_parallel_wr_enable (data_parallel_wr_enable), .tx_busy
       (tx_busy), .tx_data (tx_data), .buffer_rd_enable
       (data_serial_rd_enable), .buffer_data (data_serial_out));
endmodule

module
     uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1_1(clk,
     reset, uart_hw_rx_pin, uart_hw_tx_pin, tx_parallel_data_in,
     tx_data_wr_enable_in, tx_busy_out, rx_full, rx_parallel_data_out,
     rx_data_rd_enable_in, rx_parity_error, rx_stop_bit_error);
  input clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in;
  input [7:0] tx_parallel_data_in;
  output uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error;
  output [7:0] rx_parallel_data_out;
  wire clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in;
  wire [7:0] tx_parallel_data_in;
  wire uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error;
  wire [7:0] rx_parallel_data_out;
  rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1
       ins_rx_wrapper(.clk (clk), .reset (reset), .rx_data
       (uart_hw_rx_pin), .data_parallel_out (rx_parallel_data_out),
       .data_parallel_rd_enable (rx_data_rd_enable_in), .rx_buffer_full
       (rx_full), .parity_error (rx_parity_error), .stop_bit_error
       (rx_stop_bit_error));
  tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1
       ins_tx_wrapper(.clk (clk), .reset (reset), .data_parallel_in
       (tx_parallel_data_in), .data_parallel_wr_enable
       (tx_data_wr_enable_in), .tx_busy (tx_busy_out), .tx_data
       (uart_hw_tx_pin));
endmodule

module uart_top(clk_a, reset_a, tx_parallel_data_in_a,
     tx_data_wr_enable_in_a, tx_busy_out_a, rx_full_a,
     rx_parallel_data_out_a, rx_data_rd_enable_in_a, rx_parity_error_a,
     rx_stop_bit_error_a, clk_b, reset_b, tx_parallel_data_in_b,
     tx_data_wr_enable_in_b, tx_busy_out_b, rx_full_b,
     rx_parallel_data_out_b, rx_data_rd_enable_in_b, rx_parity_error_b,
     rx_stop_bit_error_b);
  input clk_a, reset_a, tx_data_wr_enable_in_a, rx_data_rd_enable_in_a,
       clk_b, reset_b, tx_data_wr_enable_in_b, rx_data_rd_enable_in_b;
  input [7:0] tx_parallel_data_in_a, tx_parallel_data_in_b;
  output tx_busy_out_a, rx_full_a, rx_parity_error_a,
       rx_stop_bit_error_a, tx_busy_out_b, rx_full_b,
       rx_parity_error_b, rx_stop_bit_error_b;
  output [7:0] rx_parallel_data_out_a, rx_parallel_data_out_b;
  wire clk_a, reset_a, tx_data_wr_enable_in_a, rx_data_rd_enable_in_a,
       clk_b, reset_b, tx_data_wr_enable_in_b, rx_data_rd_enable_in_b;
  wire [7:0] tx_parallel_data_in_a, tx_parallel_data_in_b;
  wire tx_busy_out_a, rx_full_a, rx_parity_error_a,
       rx_stop_bit_error_a, tx_busy_out_b, rx_full_b,
       rx_parity_error_b, rx_stop_bit_error_b;
  wire [7:0] rx_parallel_data_out_a, rx_parallel_data_out_b;
  wire w_a_tx_b_rx, w_b_tx_a_rx;
  uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1
       ins_uart_transceiver_A(.clk (clk_a), .reset (reset_a),
       .uart_hw_rx_pin (w_b_tx_a_rx), .uart_hw_tx_pin (w_a_tx_b_rx),
       .tx_parallel_data_in (tx_parallel_data_in_a),
       .tx_data_wr_enable_in (tx_data_wr_enable_in_a), .tx_busy_out
       (tx_busy_out_a), .rx_full (rx_full_a), .rx_parallel_data_out
       (rx_parallel_data_out_a), .rx_data_rd_enable_in
       (rx_data_rd_enable_in_a), .rx_parity_error (rx_parity_error_a),
       .rx_stop_bit_error (rx_stop_bit_error_a));
  uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1_1
       ins_uart_transceiver_B(.clk (clk_b), .reset (reset_b),
       .uart_hw_rx_pin (w_a_tx_b_rx), .uart_hw_tx_pin (w_b_tx_a_rx),
       .tx_parallel_data_in (tx_parallel_data_in_b),
       .tx_data_wr_enable_in (tx_data_wr_enable_in_b), .tx_busy_out
       (tx_busy_out_b), .rx_full (rx_full_b), .rx_parallel_data_out
       (rx_parallel_data_out_b), .rx_data_rd_enable_in
       (rx_data_rd_enable_in_b), .rx_parity_error (rx_parity_error_b),
       .rx_stop_bit_error (rx_stop_bit_error_b));
endmodule

