
// Generated by Cadence Genus(TM) Synthesis Solution 18.10-p003_1
// Generated on: Dec 22 2022 11:42:34 +0530 (Dec 22 2022 06:12:34 UTC)

// Verification Directory fv/uart_top 

module rx_buffer_WORD_SIZE8_NO_OF_WORDS1(clk, reset, data_serial_wr_en,
     data_serial_in, data_parallel_rd_enable, data_parallel_out,
     buffer_full, dft_sdi, dft_sen, dft_sdo);
  input clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable, dft_sdi, dft_sen;
  output [7:0] data_parallel_out;
  output buffer_full, dft_sdo;
  wire clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable, dft_sdi, dft_sen;
  wire [7:0] data_parallel_out;
  wire buffer_full, dft_sdo;
  wire [4:0] buffer_full_counter;
  wire [7:0] memory;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51;
  AND2X6 g480__8780(.A (n_49), .B (n_50), .Y (n_51));
  NOR2BX1 g481__4296(.AN (buffer_full_counter[3]), .B
       (buffer_full_counter[0]), .Y (n_50));
  NOR2XL g482__3772(.A (buffer_full_counter[1]), .B
       (buffer_full_counter[2]), .Y (n_49));
  CLKBUFX20 drc_bufs(.A (n_51), .Y (buffer_full));
  SDFFQX2 \buffer_full_counter_reg[2] (.CK (clk), .D (n_39), .SI
       (buffer_full_counter[1]), .SE (dft_sen), .Q
       (buffer_full_counter[2]));
  SDFFQX1 \buffer_full_counter_reg[3] (.CK (clk), .D (n_40), .SI
       (buffer_full_counter[2]), .SE (dft_sen), .Q
       (buffer_full_counter[3]));
  NOR2X1 g720__1474(.A (reset), .B (n_36), .Y (n_40));
  NOR2X1 g721__4547(.A (reset), .B (n_37), .Y (n_39));
  AOI22X1 g722__9682(.A0 (n_0), .A1 (n_35), .B0
       (buffer_full_counter[2]), .B1 (n_11), .Y (n_37));
  AOI22X1 g723__2683(.A0 (n_0), .A1 (n_34), .B0
       (buffer_full_counter[3]), .B1 (n_11), .Y (n_36));
  SDFFQX2 \buffer_full_counter_reg[1] (.CK (clk), .D (n_33), .SI
       (buffer_full_counter[0]), .SE (dft_sen), .Q
       (buffer_full_counter[1]));
  ADDHX1 g725__1309(.A (buffer_full_counter[2]), .B (n_28), .CO (n_34),
       .S (n_35));
  SDFFQX1 \buffer_full_counter_reg[0] (.CK (clk), .D (n_32), .SI
       (dft_sdi), .SE (dft_sen), .Q (buffer_full_counter[0]));
  NOR2X1 g727__6877(.A (reset), .B (n_31), .Y (n_33));
  NOR2X1 g728__2900(.A (reset), .B (n_30), .Y (n_32));
  AOI22X1 g729__2391(.A0 (n_0), .A1 (n_29), .B0
       (buffer_full_counter[1]), .B1 (n_11), .Y (n_31));
  SDFFHQX8 \data_parallel_out_reg[2] (.CK (clk), .D (n_24), .SI (n_42),
       .SE (dft_sen), .Q (n_43));
  SDFFQX1 \memory_reg[0] (.CK (clk), .D (n_23), .SI (n_48), .SE
       (dft_sen), .Q (memory[0]));
  SDFFHQX8 \data_parallel_out_reg[0] (.CK (clk), .D (n_26), .SI
       (buffer_full_counter[3]), .SE (dft_sen), .Q (n_41));
  SDFFHQX8 \data_parallel_out_reg[1] (.CK (clk), .D (n_25), .SI (n_41),
       .SE (dft_sen), .Q (n_42));
  SDFFHQX8 \data_parallel_out_reg[7] (.CK (clk), .D (n_15), .SI (n_47),
       .SE (dft_sen), .Q (n_48));
  SDFFHQX8 \data_parallel_out_reg[3] (.CK (clk), .D (n_27), .SI (n_43),
       .SE (dft_sen), .Q (n_44));
  SDFFHQX8 \data_parallel_out_reg[4] (.CK (clk), .D (n_22), .SI (n_44),
       .SE (dft_sen), .Q (n_45));
  SDFFHQX8 \data_parallel_out_reg[5] (.CK (clk), .D (n_21), .SI (n_45),
       .SE (dft_sen), .Q (n_46));
  MXI2XL g738__7675(.A (n_0), .B (n_11), .S0 (buffer_full_counter[0]),
       .Y (n_30));
  SDFFHQX8 \data_parallel_out_reg[6] (.CK (clk), .D (n_20), .SI (n_46),
       .SE (dft_sen), .Q (n_47));
  SDFFQX1 \memory_reg[3] (.CK (clk), .D (n_19), .SI (memory[2]), .SE
       (dft_sen), .Q (memory[3]));
  SDFFQX1 \memory_reg[4] (.CK (clk), .D (n_14), .SI (memory[3]), .SE
       (dft_sen), .Q (memory[4]));
  SDFFQX1 \memory_reg[5] (.CK (clk), .D (n_13), .SI (memory[4]), .SE
       (dft_sen), .Q (memory[5]));
  SDFFQX1 \memory_reg[2] (.CK (clk), .D (n_16), .SI (memory[1]), .SE
       (dft_sen), .Q (memory[2]));
  SDFFQX1 \memory_reg[7] (.CK (clk), .D (n_12), .SI (memory[6]), .SE
       (dft_sen), .Q (dft_sdo));
  SDFFQX1 \memory_reg[6] (.CK (clk), .D (n_18), .SI (memory[5]), .SE
       (dft_sen), .Q (memory[6]));
  SDFFQX1 \memory_reg[1] (.CK (clk), .D (n_17), .SI (memory[0]), .SE
       (dft_sen), .Q (memory[1]));
  ADDHX1 g747__7118(.A (buffer_full_counter[1]), .B
       (buffer_full_counter[0]), .CO (n_28), .S (n_29));
  NOR2X1 g748__8757(.A (reset), .B (n_8), .Y (n_27));
  NOR2X1 g749__1786(.A (reset), .B (n_9), .Y (n_26));
  NOR2X1 g750__5953(.A (reset), .B (n_10), .Y (n_25));
  NOR2X1 g751__5703(.A (reset), .B (n_7), .Y (n_24));
  NOR2X1 g752__7114(.A (reset), .B (n_2), .Y (n_23));
  NOR2X1 g753__5266(.A (reset), .B (n_4), .Y (n_22));
  NOR2X1 g754__2250(.A (reset), .B (n_5), .Y (n_21));
  NOR2X1 g755__6083(.A (reset), .B (n_6), .Y (n_20));
  MX2X1 g756__2703(.A (memory[3]), .B (memory[4]), .S0 (n_1), .Y
       (n_19));
  MX2X1 g757__5795(.A (memory[6]), .B (dft_sdo), .S0 (n_1), .Y (n_18));
  MX2X1 g758__7344(.A (memory[1]), .B (memory[2]), .S0 (n_1), .Y
       (n_17));
  MX2X1 g759__1840(.A (memory[2]), .B (memory[3]), .S0 (n_1), .Y
       (n_16));
  NOR2X1 g760__5019(.A (reset), .B (n_3), .Y (n_15));
  MX2X1 g761__1857(.A (memory[4]), .B (memory[5]), .S0 (n_1), .Y
       (n_14));
  MX2X1 g762__9906(.A (memory[5]), .B (memory[6]), .S0 (n_1), .Y
       (n_13));
  MX2X1 g763__8780(.A (dft_sdo), .B (data_serial_in), .S0 (n_1), .Y
       (n_12));
  MXI2XL g764__4296(.A (n_42), .B (memory[1]), .S0
       (data_parallel_rd_enable), .Y (n_10));
  MXI2XL g765__3772(.A (n_41), .B (memory[0]), .S0
       (data_parallel_rd_enable), .Y (n_9));
  MXI2XL g766__1474(.A (n_44), .B (memory[3]), .S0
       (data_parallel_rd_enable), .Y (n_8));
  MXI2XL g767__4547(.A (n_43), .B (memory[2]), .S0
       (data_parallel_rd_enable), .Y (n_7));
  NOR2X1 g768__9682(.A (n_0), .B (data_parallel_rd_enable), .Y (n_11));
  MXI2XL g769__2683(.A (n_47), .B (memory[6]), .S0
       (data_parallel_rd_enable), .Y (n_6));
  MXI2XL g770__1309(.A (n_46), .B (memory[5]), .S0
       (data_parallel_rd_enable), .Y (n_5));
  MXI2XL g771__6877(.A (n_45), .B (memory[4]), .S0
       (data_parallel_rd_enable), .Y (n_4));
  MXI2XL g772__2900(.A (n_48), .B (dft_sdo), .S0
       (data_parallel_rd_enable), .Y (n_3));
  MXI2XL g773__2391(.A (memory[0]), .B (memory[1]), .S0
       (data_serial_wr_en), .Y (n_2));
  NOR2BX2 g774__7675(.AN (data_serial_wr_en), .B (reset), .Y (n_1));
  NOR2BX2 g775__7118(.AN (data_serial_wr_en), .B
       (buffer_full_counter[3]), .Y (n_0));
  CLKBUFX20 drc_bufs778(.A (n_48), .Y (data_parallel_out[7]));
  CLKBUFX20 drc_bufs781(.A (n_41), .Y (data_parallel_out[0]));
  CLKBUFX20 drc_bufs784(.A (n_42), .Y (data_parallel_out[1]));
  CLKBUFX20 drc_bufs787(.A (n_43), .Y (data_parallel_out[2]));
  CLKBUFX20 drc_bufs790(.A (n_44), .Y (data_parallel_out[3]));
  CLKBUFX20 drc_bufs793(.A (n_45), .Y (data_parallel_out[4]));
  CLKBUFX20 drc_bufs796(.A (n_46), .Y (data_parallel_out[5]));
  CLKBUFX20 drc_bufs799(.A (n_47), .Y (data_parallel_out[6]));
endmodule

module
     rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1(clk,
     reset, sampling_tick_middle, sampling_tick_end, tick_start,
     rx_data, data_out_to_buffer, data_valid_to_buffer, parity_error,
     stop_bit_error, dft_sdi, dft_sen);
  input clk, reset, sampling_tick_middle, sampling_tick_end, rx_data,
       dft_sdi, dft_sen;
  output tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire clk, reset, sampling_tick_middle, sampling_tick_end, rx_data,
       dft_sdi, dft_sen;
  wire tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire [3:0] state;
  wire [2:0] data_bit_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, parity;
  SDFFHQX8 parity_error_reg(.CK (clk), .D (n_59), .SI
       (data_valid_to_buffer), .SE (dft_sen), .Q (n_62));
  SDFFHQX4 \state_reg[0] (.CK (clk), .D (n_60), .SI (parity), .SE
       (dft_sen), .Q (state[0]));
  SDFFQX1 \data_bit_counter_reg[2] (.CK (clk), .D (n_57), .SI
       (data_bit_counter[1]), .SE (dft_sen), .Q (data_bit_counter[2]));
  SDFFQX4 stop_bit_error_reg(.CK (clk), .D (n_58), .SI (state[2]), .SE
       (dft_sen), .Q (n_61));
  NOR2X1 g2806__8757(.A (reset), .B (n_55), .Y (n_60));
  OAI33X1 g2807__1786(.A0 (reset), .A1 (n_2), .A2 (n_43), .B0 (n_19),
       .B1 (reset), .B2 (n_29), .Y (n_59));
  SDFFQX1 \data_bit_counter_reg[1] (.CK (clk), .D (n_56), .SI
       (data_bit_counter[0]), .SE (dft_sen), .Q (data_bit_counter[1]));
  NOR2X1 g2809__5953(.A (reset), .B (n_51), .Y (n_58));
  SDFFQX1 \data_bit_counter_reg[0] (.CK (clk), .D (n_53), .SI
       (dft_sdi), .SE (dft_sen), .Q (data_bit_counter[0]));
  NOR2X1 g2811__5703(.A (reset), .B (n_54), .Y (n_57));
  NOR2X1 g2812__7114(.A (reset), .B (n_52), .Y (n_56));
  NOR4BX1 g2813__5266(.AN (n_40), .B (n_17), .C (n_27), .D (n_30), .Y
       (n_55));
  SDFFQX1 data_out_to_buffer_reg(.CK (clk), .D (n_49), .SI
       (data_bit_counter[2]), .SE (dft_sen), .Q (data_out_to_buffer));
  SDFFQX1 data_valid_to_buffer_reg(.CK (clk), .D (n_50), .SI
       (data_out_to_buffer), .SE (dft_sen), .Q (data_valid_to_buffer));
  SDFFQX2 \state_reg[2] (.CK (clk), .D (n_48), .SI (state[1]), .SE
       (dft_sen), .Q (state[2]));
  SDFFHQX4 \state_reg[1] (.CK (clk), .D (n_44), .SI (state[0]), .SE
       (dft_sen), .Q (state[1]));
  AOI31X1 g2818__2250(.A0 (data_bit_counter[1]), .A1
       (data_bit_counter[0]), .A2 (n_14), .B0 (n_46), .Y (n_54));
  NOR2X1 g2819__6083(.A (reset), .B (n_42), .Y (n_53));
  AOI22X1 g2820__2703(.A0 (data_bit_counter[1]), .A1 (n_39), .B0 (n_9),
       .B1 (n_14), .Y (n_52));
  AOI21X1 g2821__5795(.A0 (n_61), .A1 (n_35), .B0 (n_45), .Y (n_51));
  SDFFQX1 parity_reg(.CK (clk), .D (n_47), .SI (n_62), .SE (dft_sen),
       .Q (parity));
  NOR2X1 g2823__7344(.A (reset), .B (n_36), .Y (n_50));
  NOR2X1 g2824__1840(.A (reset), .B (n_38), .Y (n_49));
  AOI31X1 g2825__5019(.A0 (n_5), .A1 (n_15), .A2 (n_29), .B0 (reset),
       .Y (n_48));
  NOR2X1 g2826__1857(.A (reset), .B (n_37), .Y (n_47));
  SDFFQX1 tick_start_reg(.CK (clk), .D (n_41), .SI (n_61), .SE
       (dft_sen), .Q (tick_start));
  OA21X1 g2828__9906(.A0 (state[1]), .A1 (n_34), .B0
       (data_bit_counter[2]), .Y (n_46));
  AOI221X1 g2829__8780(.A0 (n_7), .A1 (n_31), .B0 (n_22), .B1 (n_24),
       .C0 (rx_data), .Y (n_45));
  AOI21X1 g2830__4296(.A0 (n_11), .A1 (n_32), .B0 (reset), .Y (n_44));
  NOR3X1 g2831__3772(.A (n_10), .B (n_6), .C (n_33), .Y (n_43));
  MXI2XL g2832__1474(.A (n_14), .B (n_34), .S0 (data_bit_counter[0]),
       .Y (n_42));
  AOI2BB1X1 g2833__4547(.A0N (tick_start), .A1N (n_27), .B0 (reset), .Y
       (n_41));
  OAI211X1 g2834__9682(.A0 (state[2]), .A1 (n_16), .B0
       (sampling_tick_middle), .C0 (n_10), .Y (n_40));
  AO21X1 g2835__2683(.A0 (n_4), .A1 (state[1]), .B0 (n_34), .Y (n_39));
  AOI22X1 g2836__1309(.A0 (rx_data), .A1 (n_14), .B0
       (data_out_to_buffer), .B1 (n_26), .Y (n_38));
  AOI22X1 g2837__6877(.A0 (n_19), .A1 (n_14), .B0 (parity), .B1 (n_26),
       .Y (n_37));
  AOI21X1 g2838__2900(.A0 (data_valid_to_buffer), .A1 (n_25), .B0
       (n_14), .Y (n_36));
  OAI211X1 g2839__2391(.A0 (state[2]), .A1 (n_11), .B0 (n_21), .C0
       (n_28), .Y (n_35));
  AO21X1 g2840__7675(.A0 (state[1]), .A1 (n_16), .B0 (n_26), .Y (n_34));
  OAI211X1 g2841__7118(.A0 (n_3), .A1 (n_12), .B0 (n_18), .C0 (n_24),
       .Y (n_33));
  MXI2XL g2842__8757(.A (state[1]), .B (n_6), .S0 (n_20), .Y (n_32));
  INVX1 g2843(.A (n_30), .Y (n_31));
  NAND2X1 g2844__1786(.A (state[0]), .B (n_15), .Y (n_28));
  NOR2X1 g2845__5953(.A (n_3), .B (n_15), .Y (n_30));
  OR3X1 g2846__5703(.A (n_3), .B (n_1), .C (n_8), .Y (n_29));
  OR2X1 g2847__7114(.A (n_6), .B (n_23), .Y (n_25));
  NOR4X2 g2848__5266(.A (state[2]), .B (rx_data), .C (state[0]), .D
       (state[1]), .Y (n_27));
  NAND2X1 g2849__2250(.A (n_3), .B (n_13), .Y (n_26));
  NOR2BX1 g2850__6083(.AN (state[2]), .B (n_7), .Y (n_23));
  OR2X1 g2851__2703(.A (state[1]), .B (n_12), .Y (n_22));
  NAND2BX1 g2852__5795(.AN (n_5), .B (n_7), .Y (n_21));
  NAND2BX1 g2853__7344(.AN (n_5), .B (sampling_tick_middle), .Y (n_24));
  NAND2X1 g2854__1840(.A (n_12), .B (n_8), .Y (n_20));
  INVX1 g2855(.A (n_17), .Y (n_18));
  AOI2BB1X1 g2856__5019(.A0N (sampling_tick_middle), .A1N (n_1), .B0
       (state[2]), .Y (n_13));
  CLKXOR2X1 g2857__1857(.A (parity), .B (rx_data), .Y (n_19));
  NOR3X1 g2858__9906(.A (sampling_tick_middle), .B (state[2]), .C
       (n_3), .Y (n_17));
  AND3XL g2859__8780(.A (data_bit_counter[2]), .B
       (data_bit_counter[1]), .C (data_bit_counter[0]), .Y (n_16));
  OAI2BB1X1 g2860__4296(.A0N (sampling_tick_end), .A1N (state[1]), .B0
       (state[2]), .Y (n_15));
  NOR2X2 g2861__3772(.A (n_8), .B (n_11), .Y (n_14));
  INVX1 g2862(.A (n_11), .Y (n_10));
  NOR2X1 g2863__1474(.A (data_bit_counter[1]), .B (n_4), .Y (n_9));
  NAND2X1 g2864__4547(.A (sampling_tick_end), .B (state[2]), .Y (n_12));
  OR2X1 g2865__9682(.A (state[0]), .B (n_1), .Y (n_11));
  NAND2BX2 g2866__2683(.AN (state[2]), .B (sampling_tick_middle), .Y
       (n_8));
  NOR2X1 g2867__1309(.A (sampling_tick_middle), .B (state[1]), .Y
       (n_7));
  NOR2X1 g2868__6877(.A (n_3), .B (state[1]), .Y (n_6));
  NAND2X1 g2869__2900(.A (state[2]), .B (n_3), .Y (n_5));
  INVX1 g2870(.A (data_bit_counter[0]), .Y (n_4));
  INVX1 g2871(.A (state[0]), .Y (n_3));
  INVX1 g2872(.A (n_62), .Y (n_2));
  INVX1 g2873(.A (state[1]), .Y (n_1));
  BUFX6 drc_bufs2876(.A (n_61), .Y (n_0));
  CLKBUFX20 drc_bufs2879(.A (n_62), .Y (parity_error));
  CLKBUFX20 drc_bufs(.A (n_0), .Y (stop_bit_error));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100(clk, reset,
     start, tick_16_8, tick_16_16, dft_sen, dft_sdo, dft_sdi);
  input clk, reset, start, dft_sen, dft_sdi;
  output tick_16_8, tick_16_16, dft_sdo;
  wire clk, reset, start, dft_sen, dft_sdi;
  wire tick_16_8, tick_16_16, dft_sdo;
  wire [10:0] counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_61, n_63, n_64;
  wire n_65;
  SDFFQX1 tick_16_16_reg(.CK (clk), .D (n_36), .SI (tick_16_8), .SE
       (dft_sen), .Q (tick_16_16));
  NAND2BX1 g868__2391(.AN (n_63), .B (start), .Y (n_64));
  NOR3BX1 g869__7675(.AN (start), .B (reset), .C (n_63), .Y (n_36));
  OR2X1 g870__7118(.A (n_33), .B (n_35), .Y (n_63));
  AOI21X1 g871__8757(.A0 (counter[6]), .A1 (n_34), .B0 (counter[7]), .Y
       (n_35));
  OAI2BB1X1 g872__1786(.A0N (counter[5]), .A1N (n_61), .B0 (n_65), .Y
       (n_34));
  NAND2X1 g873__5953(.A (counter[4]), .B (counter[5]), .Y (n_65));
  NAND2X1 g874__5703(.A (dft_sdo), .B (counter[9]), .Y (n_33));
  OR2X1 g875__7114(.A (counter[3]), .B (counter[2]), .Y (n_61));
  SDFFQX1 \counter_reg[9] (.CK (clk), .D (n_32), .SI (dft_sdi), .SE
       (dft_sen), .Q (counter[9]));
  SDFFQX1 \counter_reg[8] (.CK (clk), .D (n_31), .SI (counter[7]), .SE
       (dft_sen), .Q (dft_sdo));
  NOR3X1 g1417__5266(.A (reset), .B (n_1), .C (n_30), .Y (n_32));
  NOR3BX1 g1418__2250(.AN (n_29), .B (reset), .C (n_1), .Y (n_31));
  NOR2X1 g1419__6083(.A (counter[9]), .B (n_28), .Y (n_30));
  ADDHX1 g1420__2703(.A (dft_sdo), .B (n_25), .CO (n_28), .S (n_29));
  SDFFQX1 \counter_reg[7] (.CK (clk), .D (n_27), .SI (counter[6]), .SE
       (dft_sen), .Q (counter[7]));
  NOR3BX1 g1422__5795(.AN (n_26), .B (reset), .C (n_1), .Y (n_27));
  SDFFQX1 \counter_reg[5] (.CK (clk), .D (n_24), .SI (counter[4]), .SE
       (dft_sen), .Q (counter[5]));
  ADDHX1 g1424__7344(.A (counter[7]), .B (n_19), .CO (n_25), .S (n_26));
  SDFFQX1 \counter_reg[6] (.CK (clk), .D (n_23), .SI (counter[5]), .SE
       (dft_sen), .Q (counter[6]));
  NOR3X1 g1426__1840(.A (reset), .B (n_21), .C (n_1), .Y (n_24));
  SDFFQX1 \counter_reg[4] (.CK (clk), .D (n_22), .SI (counter[3]), .SE
       (dft_sen), .Q (counter[4]));
  NOR3BX1 g1428__5019(.AN (n_20), .B (reset), .C (n_1), .Y (n_23));
  NOR3BX1 g1429__1857(.AN (n_18), .B (reset), .C (n_1), .Y (n_22));
  XNOR2X1 g1430__9906(.A (counter[5]), .B (n_17), .Y (n_21));
  ADDHX1 g1431__8780(.A (counter[6]), .B (n_15), .CO (n_19), .S (n_20));
  ADDHX1 g1432__4296(.A (counter[4]), .B (n_14), .CO (n_17), .S (n_18));
  SDFFQX1 \counter_reg[3] (.CK (clk), .D (n_16), .SI (counter[2]), .SE
       (dft_sen), .Q (counter[3]));
  NOR3BX1 g1434__3772(.AN (n_13), .B (reset), .C (n_1), .Y (n_16));
  SDFFQX1 tick_16_8_reg(.CK (clk), .D (n_12), .SI (counter[9]), .SE
       (dft_sen), .Q (tick_16_8));
  NOR2BX1 g1436__1474(.AN (n_14), .B (n_65), .Y (n_15));
  ADDHX1 g1437__4547(.A (counter[3]), .B (n_8), .CO (n_14), .S (n_13));
  SDFFQX1 \counter_reg[2] (.CK (clk), .D (n_10), .SI (counter[1]), .SE
       (dft_sen), .Q (counter[2]));
  NOR2X1 g1439__9682(.A (reset), .B (n_11), .Y (n_12));
  AOI31X1 g1440__2683(.A0 (dft_sdo), .A1 (counter[7]), .A2 (n_7), .B0
       (n_0), .Y (n_11));
  NOR3BX1 g1441__1309(.AN (n_9), .B (reset), .C (n_1), .Y (n_10));
  ADDHX1 g1442__6877(.A (counter[2]), .B (n_4), .CO (n_8), .S (n_9));
  SDFFQX1 \counter_reg[1] (.CK (clk), .D (n_6), .SI (counter[0]), .SE
       (dft_sen), .Q (counter[1]));
  NOR4BBX1 g1444__2900(.AN (counter[1]), .BN (n_3), .C (counter[6]), .D
       (counter[0]), .Y (n_7));
  NOR3BX1 g1445__2391(.AN (n_5), .B (reset), .C (n_1), .Y (n_6));
  ADDHX1 g1446__7675(.A (counter[1]), .B (counter[0]), .CO (n_4), .S
       (n_5));
  SDFFQX1 \counter_reg[0] (.CK (clk), .D (n_2), .SI (start), .SE
       (dft_sen), .Q (counter[0]));
  NOR4BBX1 g1448__7118(.AN (start), .BN (n_64), .C (n_65), .D (n_61),
       .Y (n_3));
  NOR3X1 g1449__8757(.A (reset), .B (counter[0]), .C (n_1), .Y (n_2));
  NAND2X4 g1450__1786(.A (start), .B (n_63), .Y (n_1));
  NOR2BX1 g1451__5953(.AN (tick_16_8), .B (n_64), .Y (n_0));
endmodule

module
     rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100(clk,
     reset, rx_data, data_parallel_out, data_parallel_rd_enable,
     rx_buffer_full, parity_error, stop_bit_error, dft_sdi, dft_sen,
     dft_sdo, dft_sdi_1, dft_sdo_2);
  input clk, reset, rx_data, data_parallel_rd_enable, dft_sdi, dft_sen,
       dft_sdi_1;
  output [7:0] data_parallel_out;
  output rx_buffer_full, parity_error, stop_bit_error, dft_sdo,
       dft_sdo_2;
  wire clk, reset, rx_data, data_parallel_rd_enable, dft_sdi, dft_sen,
       dft_sdi_1;
  wire [7:0] data_parallel_out;
  wire rx_buffer_full, parity_error, stop_bit_error, dft_sdo, dft_sdo_2;
  wire data_out_to_buffer, data_valid_to_buffer, n_17,
       sampling_tick_middle, tick_start;
  rx_buffer_WORD_SIZE8_NO_OF_WORDS1 ins_rx_buffer(.clk (clk), .reset
       (reset), .data_serial_wr_en (data_valid_to_buffer),
       .data_serial_in (data_out_to_buffer), .data_parallel_rd_enable
       (data_parallel_rd_enable), .data_parallel_out
       (data_parallel_out), .buffer_full (rx_buffer_full), .dft_sdi
       (dft_sdi), .dft_sen (dft_sen), .dft_sdo (n_17));
  rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1
       ins_rx_fsm(.clk (clk), .reset (reset), .sampling_tick_middle
       (sampling_tick_middle), .sampling_tick_end (dft_sdo_2),
       .tick_start (tick_start), .rx_data (rx_data),
       .data_out_to_buffer (data_out_to_buffer), .data_valid_to_buffer
       (data_valid_to_buffer), .parity_error (parity_error),
       .stop_bit_error (stop_bit_error), .dft_sdi (n_17), .dft_sen
       (dft_sen));
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (dft_sdo_2), .dft_sen (dft_sen), .dft_sdo (dft_sdo), .dft_sdi
       (dft_sdi_1));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_1(clk, reset,
     start, tick_16_8, tick_16_16, dft_sdi, dft_sen);
  input clk, reset, start, dft_sdi, dft_sen;
  output tick_16_8, tick_16_16;
  wire clk, reset, start, dft_sdi, dft_sen;
  wire tick_16_8, tick_16_16;
  wire [10:0] counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37;
  SDFFQX1 \counter_reg[9] (.CK (clk), .D (n_37), .SI (counter[8]), .SE
       (dft_sen), .Q (counter[9]));
  SDFFQX1 \counter_reg[8] (.CK (clk), .D (n_36), .SI (counter[7]), .SE
       (dft_sen), .Q (counter[8]));
  NOR3X1 g1458__5703(.A (reset), .B (n_0), .C (n_35), .Y (n_37));
  NOR3BX1 g1459__7114(.AN (n_34), .B (reset), .C (n_0), .Y (n_36));
  NOR2X1 g1460__5266(.A (counter[9]), .B (n_33), .Y (n_35));
  ADDHX1 g1461__2250(.A (counter[8]), .B (n_30), .CO (n_33), .S (n_34));
  SDFFQX1 \counter_reg[7] (.CK (clk), .D (n_32), .SI (counter[6]), .SE
       (dft_sen), .Q (counter[7]));
  NOR3BX1 g1463__6083(.AN (n_31), .B (reset), .C (n_0), .Y (n_32));
  SDFFQX1 \counter_reg[5] (.CK (clk), .D (n_29), .SI (counter[4]), .SE
       (dft_sen), .Q (counter[5]));
  ADDHX1 g1465__2703(.A (counter[7]), .B (n_23), .CO (n_30), .S (n_31));
  SDFFQX1 \counter_reg[6] (.CK (clk), .D (n_27), .SI (counter[5]), .SE
       (dft_sen), .Q (counter[6]));
  NOR3X1 g1467__5795(.A (reset), .B (n_25), .C (n_0), .Y (n_29));
  SDFFQX2 tick_16_8_reg(.CK (clk), .D (n_28), .SI (counter[9]), .SE
       (dft_sen), .Q (tick_16_8));
  SDFFQX1 \counter_reg[4] (.CK (clk), .D (n_26), .SI (counter[3]), .SE
       (dft_sen), .Q (counter[4]));
  NOR3BX1 g1470__7344(.AN (start), .B (reset), .C (n_22), .Y (n_28));
  NOR3BX1 g1471__1840(.AN (n_24), .B (reset), .C (n_0), .Y (n_27));
  NOR3BX1 g1472__5019(.AN (n_21), .B (reset), .C (n_0), .Y (n_26));
  XNOR2X1 g1473__1857(.A (counter[5]), .B (n_20), .Y (n_25));
  ADDHX1 g1474__9906(.A (counter[6]), .B (n_17), .CO (n_23), .S (n_24));
  AOI22X1 g1475__8780(.A0 (counter[8]), .A1 (n_19), .B0 (tick_16_8),
       .B1 (n_10), .Y (n_22));
  ADDHX1 g1476__4296(.A (counter[4]), .B (n_16), .CO (n_20), .S (n_21));
  SDFFQX1 \counter_reg[3] (.CK (clk), .D (n_18), .SI (counter[2]), .SE
       (dft_sen), .Q (counter[3]));
  NOR4BX1 g1478__3772(.AN (counter[7]), .B (counter[0]), .C
       (counter[6]), .D (n_11), .Y (n_19));
  NOR3BX1 g1479__1474(.AN (n_15), .B (reset), .C (n_0), .Y (n_18));
  SDFFQX1 \counter_reg[1] (.CK (clk), .D (n_13), .SI (counter[0]), .SE
       (dft_sen), .Q (counter[1]));
  SDFFQX1 \counter_reg[2] (.CK (clk), .D (n_12), .SI (counter[1]), .SE
       (dft_sen), .Q (counter[2]));
  NOR2BX1 g1482__4547(.AN (n_16), .B (n_3), .Y (n_17));
  SDFFQX1 \counter_reg[0] (.CK (clk), .D (n_14), .SI (dft_sdi), .SE
       (dft_sen), .Q (counter[0]));
  ADDHX1 g1484__9682(.A (counter[3]), .B (n_8), .CO (n_16), .S (n_15));
  NOR3X1 g1485__2683(.A (reset), .B (counter[0]), .C (n_0), .Y (n_14));
  NOR3BX1 g1486__1309(.AN (n_6), .B (reset), .C (n_0), .Y (n_13));
  NOR3BX1 g1487__6877(.AN (n_9), .B (reset), .C (n_0), .Y (n_12));
  OR4X1 g1489__2900(.A (n_1), .B (n_3), .C (n_2), .D (n_10), .Y (n_11));
  AND3XL g1490__2391(.A (counter[9]), .B (counter[8]), .C (n_7), .Y
       (n_10));
  ADDHX1 g1491__7675(.A (counter[2]), .B (n_5), .CO (n_8), .S (n_9));
  AO21X1 g1492__7118(.A0 (counter[6]), .A1 (n_4), .B0 (counter[7]), .Y
       (n_7));
  ADDHX1 g1493__8757(.A (counter[1]), .B (counter[0]), .CO (n_5), .S
       (n_6));
  OAI2BB1X1 g1494__1786(.A0N (counter[5]), .A1N (n_2), .B0 (n_3), .Y
       (n_4));
  NAND2X1 g1495__5953(.A (counter[4]), .B (counter[5]), .Y (n_3));
  OR2X1 g1496__5703(.A (counter[3]), .B (counter[2]), .Y (n_2));
  INVX1 g1498(.A (counter[1]), .Y (n_1));
  NAND2BX4 g2__7114(.AN (n_10), .B (start), .Y (n_0));
endmodule

module tx_buffer_WORD_SIZE8_NO_OF_WORDS1(clk, reset, data_parallel_in,
     data_parallel_wr_enable, data_serial_rd_enable, data_serial_out,
     empty, dft_sdi, dft_sen, dft_sdo);
  input clk, reset, data_parallel_wr_enable, data_serial_rd_enable,
       dft_sdi, dft_sen;
  input [7:0] data_parallel_in;
  output data_serial_out, empty, dft_sdo;
  wire clk, reset, data_parallel_wr_enable, data_serial_rd_enable,
       dft_sdi, dft_sen;
  wire [7:0] data_parallel_in;
  wire data_serial_out, empty, dft_sdo;
  wire [4:0] buffer_empty_counter;
  wire [7:0] memory;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_61, n_62;
  NOR2X1 g824__5266(.A (buffer_empty_counter[0]), .B (n_61), .Y
       (empty));
  OR2X1 g825__2250(.A (buffer_empty_counter[1]), .B (n_62), .Y (n_61));
  OR2X1 g826__6083(.A (buffer_empty_counter[3]), .B
       (buffer_empty_counter[2]), .Y (n_62));
  SDFFQX1 \buffer_empty_counter_reg[2] (.CK (clk), .D (n_37), .SI
       (buffer_empty_counter[1]), .SE (dft_sen), .Q
       (buffer_empty_counter[2]));
  SDFFQX1 \buffer_empty_counter_reg[3] (.CK (clk), .D (n_36), .SI
       (buffer_empty_counter[2]), .SE (dft_sen), .Q
       (buffer_empty_counter[3]));
  NOR3X1 g1291__2703(.A (reset), .B (n_31), .C
       (data_parallel_wr_enable), .Y (n_37));
  SDFFQX1 \buffer_empty_counter_reg[1] (.CK (clk), .D (n_35), .SI
       (buffer_empty_counter[0]), .SE (dft_sen), .Q
       (buffer_empty_counter[1]));
  SDFFQX1 \memory_reg[7] (.CK (clk), .D (n_34), .SI (memory[6]), .SE
       (dft_sen), .Q (dft_sdo));
  SDFFQX1 \buffer_empty_counter_reg[0] (.CK (clk), .D (n_33), .SI
       (dft_sdi), .SE (dft_sen), .Q (buffer_empty_counter[0]));
  NAND2BX1 g1295__5795(.AN (data_parallel_wr_enable), .B (n_32), .Y
       (n_36));
  NOR3X1 g1296__7344(.A (reset), .B (n_22), .C
       (data_parallel_wr_enable), .Y (n_35));
  SDFFQX1 \memory_reg[2] (.CK (clk), .D (n_28), .SI (memory[1]), .SE
       (dft_sen), .Q (memory[2]));
  SDFFQX1 \memory_reg[1] (.CK (clk), .D (n_30), .SI (memory[0]), .SE
       (dft_sen), .Q (memory[1]));
  SDFFQX1 \memory_reg[0] (.CK (clk), .D (n_29), .SI (data_serial_out),
       .SE (dft_sen), .Q (memory[0]));
  SDFFQX1 \memory_reg[3] (.CK (clk), .D (n_24), .SI (memory[2]), .SE
       (dft_sen), .Q (memory[3]));
  SDFFQX1 \memory_reg[4] (.CK (clk), .D (n_26), .SI (memory[3]), .SE
       (dft_sen), .Q (memory[4]));
  AO22X1 g1302__1840(.A0 (n_18), .A1 (dft_sdo), .B0
       (data_parallel_in[7]), .B1 (n_2), .Y (n_34));
  NOR3X1 g1303__5019(.A (reset), .B (n_14), .C
       (data_parallel_wr_enable), .Y (n_33));
  AOI21X1 g1304__1857(.A0 (buffer_empty_counter[3]), .A1 (n_21), .B0
       (reset), .Y (n_32));
  AOI22X1 g1305__9906(.A0 (buffer_empty_counter[3]), .A1 (n_20), .B0
       (buffer_empty_counter[2]), .B1 (n_9), .Y (n_31));
  SDFFQX1 \memory_reg[5] (.CK (clk), .D (n_27), .SI (memory[4]), .SE
       (dft_sen), .Q (memory[5]));
  SDFFQX1 \memory_reg[6] (.CK (clk), .D (n_23), .SI (memory[5]), .SE
       (dft_sen), .Q (memory[6]));
  OAI2BB1X1 g1308__8780(.A0N (n_0), .A1N (memory[1]), .B0 (n_17), .Y
       (n_30));
  OAI2BB1X1 g1309__4296(.A0N (n_0), .A1N (memory[0]), .B0 (n_16), .Y
       (n_29));
  OAI2BB1X1 g1310__3772(.A0N (n_0), .A1N (memory[2]), .B0 (n_15), .Y
       (n_28));
  SDFFQX1 data_serial_out_reg(.CK (clk), .D (n_19), .SI
       (buffer_empty_counter[3]), .SE (dft_sen), .Q (data_serial_out));
  OAI2BB1X1 g1312__1474(.A0N (n_0), .A1N (memory[5]), .B0 (n_10), .Y
       (n_27));
  OAI2BB1X1 g1313__4547(.A0N (n_0), .A1N (memory[4]), .B0 (n_12), .Y
       (n_26));
  OAI2BB1X1 g1314__9682(.A0N (n_0), .A1N (memory[3]), .B0 (n_13), .Y
       (n_24));
  OAI2BB1X1 g1315__2683(.A0N (n_0), .A1N (memory[6]), .B0 (n_11), .Y
       (n_23));
  AOI22X1 g1316__1309(.A0 (n_62), .A1 (n_8), .B0
       (buffer_empty_counter[1]), .B1 (n_4), .Y (n_22));
  INVX1 g1317(.A (n_20), .Y (n_21));
  MX2X1 g1318__6877(.A (n_6), .B (memory[0]), .S0
       (data_serial_rd_enable), .Y (n_19));
  OAI21X1 g1319__2900(.A0 (reset), .A1 (n_1), .B0 (n_7), .Y (n_18));
  AOI22X1 g1320__2391(.A0 (data_parallel_in[1]), .A1 (n_2), .B0
       (memory[2]), .B1 (data_serial_rd_enable), .Y (n_17));
  AOI22X1 g1321__7675(.A0 (data_parallel_in[0]), .A1 (n_2), .B0
       (memory[1]), .B1 (data_serial_rd_enable), .Y (n_16));
  NOR2X1 g1322__7118(.A (buffer_empty_counter[2]), .B (n_9), .Y (n_20));
  AOI22X1 g1323__8757(.A0 (data_parallel_in[2]), .A1 (n_2), .B0
       (memory[3]), .B1 (data_serial_rd_enable), .Y (n_15));
  AOI22X1 g1324__1786(.A0 (n_3), .A1 (n_61), .B0
       (buffer_empty_counter[0]), .B1 (n_1), .Y (n_14));
  AOI22X1 g1325__5953(.A0 (data_parallel_in[3]), .A1 (n_2), .B0
       (memory[4]), .B1 (data_serial_rd_enable), .Y (n_13));
  AOI22X1 g1326__5703(.A0 (data_parallel_in[4]), .A1 (n_2), .B0
       (memory[5]), .B1 (data_serial_rd_enable), .Y (n_12));
  AOI22X1 g1327__7114(.A0 (data_parallel_in[6]), .A1 (n_2), .B0
       (dft_sdo), .B1 (data_serial_rd_enable), .Y (n_11));
  AOI22X1 g1328__5266(.A0 (data_parallel_in[5]), .A1 (n_2), .B0
       (memory[6]), .B1 (data_serial_rd_enable), .Y (n_10));
  INVX1 g1329(.A (n_8), .Y (n_9));
  NOR2X1 g1330__2250(.A (buffer_empty_counter[1]), .B (n_4), .Y (n_8));
  INVX1 g1331(.A (n_0), .Y (n_7));
  NOR2BX1 g1333__6083(.AN (data_serial_out), .B (reset), .Y (n_6));
  NOR2X1 g1334__2703(.A (reset), .B (data_serial_rd_enable), .Y (n_5));
  INVX1 g1335(.A (n_3), .Y (n_4));
  NOR2X1 g1336__5795(.A (buffer_empty_counter[0]), .B (n_1), .Y (n_3));
  AND2X1 g1337__7344(.A (data_parallel_wr_enable), .B (n_1), .Y (n_2));
  INVX1 g1343(.A (data_serial_rd_enable), .Y (n_1));
  NOR2BX2 g2__1840(.AN (n_5), .B (data_parallel_wr_enable), .Y (n_0));
endmodule

module
     tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1(clk,
     reset, empty, sampling_tick_middle, sampling_tick_end, tick_start,
     data_parallel_wr_enable, tx_busy, tx_data, buffer_rd_enable,
     buffer_data, dft_sdi, dft_sen);
  input clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data, dft_sdi, dft_sen;
  output tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data, dft_sdi, dft_sen;
  wire tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire [2:0] data_bit_counter;
  wire [3:0] state;
  wire delay_data_parallel_wr_enable, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, parity, tem_buffer_data;
  SDFFHQX4 buffer_rd_enable_reg(.CK (clk), .D (n_68), .SI (dft_sdi),
       .SE (dft_sen), .Q (buffer_rd_enable));
  SDFFQX2 \data_bit_counter_reg[0] (.CK (clk), .D (n_74), .SI
       (buffer_rd_enable), .SE (dft_sen), .Q (data_bit_counter[0]));
  SDFFQX1 \data_bit_counter_reg[1] (.CK (clk), .D (n_77), .SI
       (data_bit_counter[0]), .SE (dft_sen), .Q (data_bit_counter[1]));
  SDFFQX1 \data_bit_counter_reg[2] (.CK (clk), .D (n_67), .SI
       (data_bit_counter[1]), .SE (dft_sen), .Q (data_bit_counter[2]));
  SDFFQX1 delay_data_parallel_wr_enable_reg(.CK (clk), .D
       (data_parallel_wr_enable), .SI (data_bit_counter[2]), .SE
       (dft_sen), .Q (delay_data_parallel_wr_enable));
  SDFFQX1 parity_reg(.CK (clk), .D (n_80), .SI
       (delay_data_parallel_wr_enable), .SE (dft_sen), .Q (parity));
  SDFFHQX4 \state_reg[0] (.CK (clk), .D (n_78), .SI (parity), .SE
       (dft_sen), .Q (state[0]));
  SDFFHQX4 \state_reg[1] (.CK (clk), .D (n_56), .SI (state[0]), .SE
       (dft_sen), .Q (state[1]));
  SDFFHQX4 \state_reg[2] (.CK (clk), .D (n_76), .SI (state[1]), .SE
       (dft_sen), .Q (state[2]));
  SDFFHQX4 \state_reg[3] (.CK (clk), .D (n_53), .SI (state[2]), .SE
       (dft_sen), .Q (state[3]));
  SDFFQX1 tem_buffer_data_reg(.CK (clk), .D (n_79), .SI (state[3]), .SE
       (dft_sen), .Q (tem_buffer_data));
  SDFFQX1 tick_start_reg(.CK (clk), .D (n_71), .SI (tem_buffer_data),
       .SE (dft_sen), .Q (tick_start));
  SDFFHQX8 tx_busy_reg(.CK (clk), .D (n_63), .SI (tick_start), .SE
       (dft_sen), .Q (n_81));
  SDFFQX1 tx_data_reg(.CK (clk), .D (n_73), .SI (n_81), .SE (dft_sen),
       .Q (tx_data));
  NOR2X1 g2725__5019(.A (reset), .B (n_75), .Y (n_80));
  AOI21X1 g2728__1857(.A0 (n_48), .A1 (n_70), .B0 (reset), .Y (n_79));
  OAI221X1 g2731__9906(.A0 (reset), .A1 (n_30), .B0 (n_62), .B1
       (state[0]), .C0 (n_72), .Y (n_78));
  AOI21X1 g2732__8780(.A0 (n_51), .A1 (n_69), .B0 (reset), .Y (n_77));
  AOI31X1 g2733__4296(.A0 (n_28), .A1 (n_38), .A2 (n_58), .B0 (reset),
       .Y (n_76));
  MX2X1 g2734__3772(.A (n_48), .B (n_66), .S0 (parity), .Y (n_75));
  NOR2X1 g2737__1474(.A (reset), .B (n_65), .Y (n_74));
  NAND3X1 g2738__4547(.A (n_64), .B (n_32), .C (n_37), .Y (n_73));
  NAND2BX1 g2740__9682(.AN (reset), .B (n_57), .Y (n_72));
  AOI31X1 g2741__2683(.A0 (n_46), .A1 (n_37), .A2 (n_47), .B0 (reset),
       .Y (n_71));
  NAND2X1 g2742__1309(.A (tem_buffer_data), .B (n_60), .Y (n_70));
  OAI2BB1X1 g2745__6877(.A0N (n_17), .A1N (n_55), .B0
       (data_bit_counter[1]), .Y (n_69));
  NOR2X1 g2746__2900(.A (reset), .B (n_59), .Y (n_68));
  NOR2X1 g2747__2391(.A (reset), .B (n_61), .Y (n_67));
  AOI2BB1X1 g2748__7675(.A0N (buffer_data), .A1N (n_1), .B0 (n_60), .Y
       (n_66));
  AOI222X1 g2749__7118(.A0 (n_5), .A1 (n_35), .B0 (state[2]), .B1
       (n_21), .C0 (data_bit_counter[0]), .C1 (n_54), .Y (n_65));
  AOI211X1 g2750__8757(.A0 (tx_data), .A1 (n_24), .B0 (reset), .C0
       (n_49), .Y (n_64));
  AOI21X1 g2751__1786(.A0 (n_45), .A1 (n_47), .B0 (reset), .Y (n_63));
  AO21X1 g2752__5953(.A0 (n_22), .A1 (n_39), .B0 (reset), .Y (n_62));
  AOI31X1 g2753__5703(.A0 (data_bit_counter[0]), .A1
       (data_bit_counter[1]), .A2 (n_35), .B0 (n_52), .Y (n_61));
  AOI222X1 g2755__7114(.A0 (n_20), .A1 (n_35), .B0 (buffer_rd_enable),
       .B1 (n_22), .C0 (n_3), .C1 (n_36), .Y (n_59));
  OA21X1 g2756__5266(.A0 (state[0]), .A1 (n_9), .B0 (n_50), .Y (n_58));
  OAI221X1 g2757__2250(.A0 (n_2), .A1 (n_28), .B0
       (sampling_tick_middle), .B1 (n_27), .C0 (n_44), .Y (n_57));
  OAI22X1 g2758__6083(.A0 (reset), .A1 (n_40), .B0 (reset), .B1 (n_41),
       .Y (n_56));
  OR3X1 g2759__2703(.A (state[2]), .B (n_0), .C (n_43), .Y (n_60));
  INVX1 g2760(.A (n_54), .Y (n_55));
  NOR2X1 g2761__5795(.A (reset), .B (n_42), .Y (n_53));
  OA21X1 g2762__7344(.A0 (n_7), .A1 (n_34), .B0 (data_bit_counter[2]),
       .Y (n_52));
  NAND3X2 g2763__1840(.A (n_1), .B (n_28), .C (n_33), .Y (n_54));
  NAND3BX1 g2764__5019(.AN (data_bit_counter[1]), .B
       (data_bit_counter[0]), .C (n_35), .Y (n_51));
  OAI211X1 g2765__1857(.A0 (state[0]), .A1 (n_21), .B0 (n_1), .C0
       (state[2]), .Y (n_50));
  OAI33X1 g2766__9906(.A0 (state[0]), .A1 (n_16), .A2 (n_18), .B0
       (n_15), .B1 (parity), .B2 (n_27), .Y (n_49));
  NAND2X1 g2767__8780(.A (tick_start), .B (n_32), .Y (n_46));
  NAND2X1 g2768__4296(.A (n_81), .B (n_32), .Y (n_45));
  NAND2X1 g2769__3772(.A (n_21), .B (n_35), .Y (n_44));
  NAND2BX1 g2770__1474(.AN (n_38), .B (buffer_data), .Y (n_48));
  NAND2BX1 g2771__4547(.AN (n_32), .B (delay_data_parallel_wr_enable),
       .Y (n_47));
  OAI211X1 g2772__9682(.A0 (state[0]), .A1 (n_14), .B0 (n_11), .C0
       (n_6), .Y (n_43));
  AOI22X1 g2773__2683(.A0 (state[3]), .A1 (n_19), .B0 (state[0]), .B1
       (n_26), .Y (n_42));
  AOI211X1 g2774__1309(.A0 (state[1]), .A1 (n_2), .B0 (n_10), .C0
       (n_25), .Y (n_41));
  AOI21X1 g2775__6877(.A0 (n_20), .A1 (n_23), .B0 (n_36), .Y (n_40));
  AOI31X1 g2776__2900(.A0 (delay_data_parallel_wr_enable), .A1 (n_4),
       .A2 (n_3), .B0 (n_31), .Y (n_39));
  OR2X1 g2777__2391(.A (n_2), .B (n_22), .Y (n_38));
  OR2X1 g2778__7675(.A (n_7), .B (n_29), .Y (n_37));
  AND2X1 g2779__7118(.A (n_0), .B (sampling_tick_middle), .Y (n_36));
  AND2X1 g2780__8757(.A (n_23), .B (n_2), .Y (n_35));
  INVX1 g2781(.A (n_33), .Y (n_34));
  NOR3BX1 g2782__1786(.AN (sampling_tick_middle), .B (n_4), .C (n_7),
       .Y (n_31));
  OA21X1 g2783__5953(.A0 (n_2), .A1 (n_11), .B0 (n_29), .Y (n_30));
  MX2X1 g2784__5703(.A (n_12), .B (n_2), .S0 (n_4), .Y (n_33));
  OR3X1 g2785__7114(.A (state[0]), .B (state[2]), .C (n_13), .Y (n_32));
  NOR2X1 g2787__5266(.A (n_1), .B (n_15), .Y (n_26));
  NOR2X1 g2788__2250(.A (sampling_tick_middle), .B (n_9), .Y (n_25));
  NAND2X1 g2789__6083(.A (sampling_tick_middle), .B (n_14), .Y (n_24));
  NAND2X1 g2790__2703(.A (state[3]), .B (n_12), .Y (n_29));
  NAND2X2 g2791__5795(.A (state[2]), .B (n_16), .Y (n_28));
  NAND2X1 g2792__7344(.A (state[0]), .B (n_14), .Y (n_27));
  INVX1 g2793(.A (n_21), .Y (n_20));
  OR2X1 g2794__1840(.A (n_2), .B (n_7), .Y (n_19));
  AOI21X1 g2795__5019(.A0 (tem_buffer_data), .A1 (state[2]), .B0 (n_8),
       .Y (n_18));
  OAI21X1 g2796__1857(.A0 (data_bit_counter[2]), .A1 (n_5), .B0
       (state[2]), .Y (n_17));
  NOR2X1 g2797__9906(.A (n_15), .B (n_13), .Y (n_23));
  OR3X1 g2798__8780(.A (n_1), .B (state[3]), .C (state[2]), .Y (n_22));
  AND3XL g2799__4296(.A (data_bit_counter[2]), .B
       (data_bit_counter[1]), .C (data_bit_counter[0]), .Y (n_21));
  INVX1 g2800(.A (n_14), .Y (n_13));
  NAND2X1 g2801__3772(.A (sampling_tick_middle), .B (n_4), .Y (n_16));
  NAND2X1 g2803__1474(.A (sampling_tick_middle), .B (state[2]), .Y
       (n_15));
  AND2X1 g2804__4547(.A (n_4), .B (n_1), .Y (n_14));
  INVX1 g2805(.A (n_11), .Y (n_10));
  INVX1 g2806(.A (n_8), .Y (n_9));
  NAND2X1 g2807__9682(.A (state[3]), .B (empty), .Y (n_6));
  NOR2X1 g2808__2683(.A (n_2), .B (empty), .Y (n_12));
  NAND2X1 g2809__1309(.A (state[1]), .B (state[3]), .Y (n_11));
  NOR2X1 g2810__6877(.A (n_1), .B (n_3), .Y (n_8));
  OR2X1 g2811__2900(.A (state[1]), .B (state[2]), .Y (n_7));
  INVX1 g2812(.A (data_bit_counter[0]), .Y (n_5));
  INVX1 g2813(.A (state[3]), .Y (n_4));
  INVX1 g2814(.A (state[2]), .Y (n_3));
  INVX1 g2815(.A (state[0]), .Y (n_2));
  INVX1 g2816(.A (state[1]), .Y (n_1));
  CLKBUFX20 drc_bufs2819(.A (n_81), .Y (tx_busy));
  INVX1 drc_bufs2825(.A (n_27), .Y (n_0));
endmodule

module
     tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100(clk,
     reset, data_parallel_in, data_parallel_wr_enable, tx_busy,
     tx_data, dft_sdi, dft_sen);
  input clk, reset, data_parallel_wr_enable, dft_sdi, dft_sen;
  input [7:0] data_parallel_in;
  output tx_busy, tx_data;
  wire clk, reset, data_parallel_wr_enable, dft_sdi, dft_sen;
  wire [7:0] data_parallel_in;
  wire tx_busy, tx_data;
  wire UNCONNECTED_HIER_Z, data_serial_out, data_serial_rd_enable,
       empty, n_15, sampling_tick_end, sampling_tick_middle, tick_start;
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_1
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (sampling_tick_end), .dft_sdi (dft_sdi), .dft_sen (dft_sen));
  tx_buffer_WORD_SIZE8_NO_OF_WORDS1 ins_tx_buffer(.clk (clk), .reset
       (reset), .data_parallel_in (data_parallel_in),
       .data_parallel_wr_enable (data_parallel_wr_enable),
       .data_serial_rd_enable (data_serial_rd_enable), .data_serial_out
       (data_serial_out), .empty (empty), .dft_sdi
       (sampling_tick_middle), .dft_sen (dft_sen), .dft_sdo (n_15));
  tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1
       ins_tx_fsm(.clk (clk), .reset (reset), .empty (empty),
       .sampling_tick_middle (sampling_tick_middle), .sampling_tick_end
       (UNCONNECTED_HIER_Z), .tick_start (tick_start),
       .data_parallel_wr_enable (data_parallel_wr_enable), .tx_busy
       (tx_busy), .tx_data (tx_data), .buffer_rd_enable
       (data_serial_rd_enable), .buffer_data (data_serial_out),
       .dft_sdi (n_15), .dft_sen (dft_sen));
endmodule

module
     uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1(clk,
     reset, uart_hw_rx_pin, uart_hw_tx_pin, tx_parallel_data_in,
     tx_data_wr_enable_in, tx_busy_out, rx_full, rx_parallel_data_out,
     rx_data_rd_enable_in, rx_parity_error, rx_stop_bit_error, dft_sdi,
     dft_sen, dft_sdo, dft_sdi_1);
  input clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in, dft_sdi, dft_sen, dft_sdi_1;
  input [7:0] tx_parallel_data_in;
  output uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error, dft_sdo;
  output [7:0] rx_parallel_data_out;
  wire clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in, dft_sdi, dft_sen, dft_sdi_1;
  wire [7:0] tx_parallel_data_in;
  wire uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error, dft_sdo;
  wire [7:0] rx_parallel_data_out;
  wire n_30;
  rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100
       ins_rx_wrapper(.clk (clk), .reset (reset), .rx_data
       (uart_hw_rx_pin), .data_parallel_out (rx_parallel_data_out),
       .data_parallel_rd_enable (rx_data_rd_enable_in), .rx_buffer_full
       (rx_full), .parity_error (rx_parity_error), .stop_bit_error
       (rx_stop_bit_error), .dft_sdi (dft_sdi), .dft_sen (dft_sen),
       .dft_sdo (dft_sdo), .dft_sdi_1 (dft_sdi_1), .dft_sdo_2 (n_30));
  tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100
       ins_tx_wrapper(.clk (clk), .reset (reset), .data_parallel_in
       (tx_parallel_data_in), .data_parallel_wr_enable
       (tx_data_wr_enable_in), .tx_busy (tx_busy_out), .tx_data
       (uart_hw_tx_pin), .dft_sdi (n_30), .dft_sen (dft_sen));
endmodule

module rx_buffer_WORD_SIZE8_NO_OF_WORDS1_1(clk, reset,
     data_serial_wr_en, data_serial_in, data_parallel_rd_enable,
     data_parallel_out, buffer_full, dft_sdi, dft_sen, dft_sdo);
  input clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable, dft_sdi, dft_sen;
  output [7:0] data_parallel_out;
  output buffer_full, dft_sdo;
  wire clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable, dft_sdi, dft_sen;
  wire [7:0] data_parallel_out;
  wire buffer_full, dft_sdo;
  wire [4:0] buffer_full_counter;
  wire [7:0] memory;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51;
  AND2X6 g480__2391(.A (n_49), .B (n_50), .Y (n_51));
  NOR2BX1 g481__7675(.AN (buffer_full_counter[3]), .B
       (buffer_full_counter[0]), .Y (n_50));
  NOR2XL g482__7118(.A (buffer_full_counter[1]), .B
       (buffer_full_counter[2]), .Y (n_49));
  CLKBUFX20 drc_bufs(.A (n_51), .Y (buffer_full));
  SDFFQX2 \buffer_full_counter_reg[2] (.CK (clk), .D (n_39), .SI
       (buffer_full_counter[1]), .SE (dft_sen), .Q
       (buffer_full_counter[2]));
  SDFFQX1 \buffer_full_counter_reg[3] (.CK (clk), .D (n_40), .SI
       (buffer_full_counter[2]), .SE (dft_sen), .Q
       (buffer_full_counter[3]));
  NOR2X1 g720__8757(.A (reset), .B (n_36), .Y (n_40));
  NOR2X1 g721__1786(.A (reset), .B (n_37), .Y (n_39));
  AOI22X1 g722__5953(.A0 (n_0), .A1 (n_35), .B0
       (buffer_full_counter[2]), .B1 (n_11), .Y (n_37));
  AOI22X1 g723__5703(.A0 (n_0), .A1 (n_34), .B0
       (buffer_full_counter[3]), .B1 (n_11), .Y (n_36));
  SDFFQX2 \buffer_full_counter_reg[1] (.CK (clk), .D (n_33), .SI
       (buffer_full_counter[0]), .SE (dft_sen), .Q
       (buffer_full_counter[1]));
  ADDHX1 g725__7114(.A (buffer_full_counter[2]), .B (n_28), .CO (n_34),
       .S (n_35));
  SDFFQX1 \buffer_full_counter_reg[0] (.CK (clk), .D (n_32), .SI
       (dft_sdi), .SE (dft_sen), .Q (buffer_full_counter[0]));
  NOR2X1 g727__5266(.A (reset), .B (n_31), .Y (n_33));
  NOR2X1 g728__2250(.A (reset), .B (n_30), .Y (n_32));
  AOI22X1 g729__6083(.A0 (n_0), .A1 (n_29), .B0
       (buffer_full_counter[1]), .B1 (n_11), .Y (n_31));
  SDFFHQX8 \data_parallel_out_reg[2] (.CK (clk), .D (n_24), .SI (n_42),
       .SE (dft_sen), .Q (n_43));
  SDFFQX1 \memory_reg[0] (.CK (clk), .D (n_23), .SI (n_48), .SE
       (dft_sen), .Q (memory[0]));
  SDFFHQX8 \data_parallel_out_reg[0] (.CK (clk), .D (n_26), .SI
       (buffer_full_counter[3]), .SE (dft_sen), .Q (n_41));
  SDFFHQX8 \data_parallel_out_reg[1] (.CK (clk), .D (n_25), .SI (n_41),
       .SE (dft_sen), .Q (n_42));
  SDFFHQX8 \data_parallel_out_reg[7] (.CK (clk), .D (n_15), .SI (n_47),
       .SE (dft_sen), .Q (n_48));
  SDFFHQX8 \data_parallel_out_reg[3] (.CK (clk), .D (n_27), .SI (n_43),
       .SE (dft_sen), .Q (n_44));
  SDFFHQX8 \data_parallel_out_reg[4] (.CK (clk), .D (n_22), .SI (n_44),
       .SE (dft_sen), .Q (n_45));
  SDFFHQX8 \data_parallel_out_reg[5] (.CK (clk), .D (n_21), .SI (n_45),
       .SE (dft_sen), .Q (n_46));
  MXI2XL g738__2703(.A (n_0), .B (n_11), .S0 (buffer_full_counter[0]),
       .Y (n_30));
  SDFFHQX8 \data_parallel_out_reg[6] (.CK (clk), .D (n_20), .SI (n_46),
       .SE (dft_sen), .Q (n_47));
  SDFFQX1 \memory_reg[3] (.CK (clk), .D (n_19), .SI (memory[2]), .SE
       (dft_sen), .Q (memory[3]));
  SDFFQX1 \memory_reg[4] (.CK (clk), .D (n_14), .SI (memory[3]), .SE
       (dft_sen), .Q (memory[4]));
  SDFFQX1 \memory_reg[5] (.CK (clk), .D (n_13), .SI (memory[4]), .SE
       (dft_sen), .Q (memory[5]));
  SDFFQX1 \memory_reg[2] (.CK (clk), .D (n_16), .SI (memory[1]), .SE
       (dft_sen), .Q (memory[2]));
  SDFFQX1 \memory_reg[7] (.CK (clk), .D (n_12), .SI (memory[6]), .SE
       (dft_sen), .Q (dft_sdo));
  SDFFQX1 \memory_reg[6] (.CK (clk), .D (n_18), .SI (memory[5]), .SE
       (dft_sen), .Q (memory[6]));
  SDFFQX1 \memory_reg[1] (.CK (clk), .D (n_17), .SI (memory[0]), .SE
       (dft_sen), .Q (memory[1]));
  ADDHX1 g747__5795(.A (buffer_full_counter[1]), .B
       (buffer_full_counter[0]), .CO (n_28), .S (n_29));
  NOR2X1 g748__7344(.A (reset), .B (n_8), .Y (n_27));
  NOR2X1 g749__1840(.A (reset), .B (n_9), .Y (n_26));
  NOR2X1 g750__5019(.A (reset), .B (n_10), .Y (n_25));
  NOR2X1 g751__1857(.A (reset), .B (n_7), .Y (n_24));
  NOR2X1 g752__9906(.A (reset), .B (n_2), .Y (n_23));
  NOR2X1 g753__8780(.A (reset), .B (n_4), .Y (n_22));
  NOR2X1 g754__4296(.A (reset), .B (n_5), .Y (n_21));
  NOR2X1 g755__3772(.A (reset), .B (n_6), .Y (n_20));
  MX2X1 g756__1474(.A (memory[3]), .B (memory[4]), .S0 (n_1), .Y
       (n_19));
  MX2X1 g757__4547(.A (memory[6]), .B (dft_sdo), .S0 (n_1), .Y (n_18));
  MX2X1 g758__9682(.A (memory[1]), .B (memory[2]), .S0 (n_1), .Y
       (n_17));
  MX2X1 g759__2683(.A (memory[2]), .B (memory[3]), .S0 (n_1), .Y
       (n_16));
  NOR2X1 g760__1309(.A (reset), .B (n_3), .Y (n_15));
  MX2X1 g761__6877(.A (memory[4]), .B (memory[5]), .S0 (n_1), .Y
       (n_14));
  MX2X1 g762__2900(.A (memory[5]), .B (memory[6]), .S0 (n_1), .Y
       (n_13));
  MX2X1 g763__2391(.A (dft_sdo), .B (data_serial_in), .S0 (n_1), .Y
       (n_12));
  MXI2XL g764__7675(.A (n_42), .B (memory[1]), .S0
       (data_parallel_rd_enable), .Y (n_10));
  MXI2XL g765__7118(.A (n_41), .B (memory[0]), .S0
       (data_parallel_rd_enable), .Y (n_9));
  MXI2XL g766__8757(.A (n_44), .B (memory[3]), .S0
       (data_parallel_rd_enable), .Y (n_8));
  MXI2XL g767__1786(.A (n_43), .B (memory[2]), .S0
       (data_parallel_rd_enable), .Y (n_7));
  NOR2X1 g768__5953(.A (n_0), .B (data_parallel_rd_enable), .Y (n_11));
  MXI2XL g769__5703(.A (n_47), .B (memory[6]), .S0
       (data_parallel_rd_enable), .Y (n_6));
  MXI2XL g770__7114(.A (n_46), .B (memory[5]), .S0
       (data_parallel_rd_enable), .Y (n_5));
  MXI2XL g771__5266(.A (n_45), .B (memory[4]), .S0
       (data_parallel_rd_enable), .Y (n_4));
  MXI2XL g772__2250(.A (n_48), .B (dft_sdo), .S0
       (data_parallel_rd_enable), .Y (n_3));
  MXI2XL g773__6083(.A (memory[0]), .B (memory[1]), .S0
       (data_serial_wr_en), .Y (n_2));
  NOR2BX2 g774__2703(.AN (data_serial_wr_en), .B (reset), .Y (n_1));
  NOR2BX2 g775__5795(.AN (data_serial_wr_en), .B
       (buffer_full_counter[3]), .Y (n_0));
  CLKBUFX20 drc_bufs778(.A (n_48), .Y (data_parallel_out[7]));
  CLKBUFX20 drc_bufs781(.A (n_41), .Y (data_parallel_out[0]));
  CLKBUFX20 drc_bufs784(.A (n_42), .Y (data_parallel_out[1]));
  CLKBUFX20 drc_bufs787(.A (n_43), .Y (data_parallel_out[2]));
  CLKBUFX20 drc_bufs790(.A (n_44), .Y (data_parallel_out[3]));
  CLKBUFX20 drc_bufs793(.A (n_45), .Y (data_parallel_out[4]));
  CLKBUFX20 drc_bufs796(.A (n_46), .Y (data_parallel_out[5]));
  CLKBUFX20 drc_bufs799(.A (n_47), .Y (data_parallel_out[6]));
endmodule

module
     rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1(clk,
     reset, sampling_tick_middle, sampling_tick_end, tick_start,
     rx_data, data_out_to_buffer, data_valid_to_buffer, parity_error,
     stop_bit_error, dft_sdi, dft_sen);
  input clk, reset, sampling_tick_middle, sampling_tick_end, rx_data,
       dft_sdi, dft_sen;
  output tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire clk, reset, sampling_tick_middle, sampling_tick_end, rx_data,
       dft_sdi, dft_sen;
  wire tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire [3:0] state;
  wire [2:0] data_bit_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, parity;
  SDFFHQX8 parity_error_reg(.CK (clk), .D (n_59), .SI
       (data_valid_to_buffer), .SE (dft_sen), .Q (n_62));
  SDFFHQX4 \state_reg[0] (.CK (clk), .D (n_60), .SI (parity), .SE
       (dft_sen), .Q (state[0]));
  SDFFQX1 \data_bit_counter_reg[2] (.CK (clk), .D (n_57), .SI
       (data_bit_counter[1]), .SE (dft_sen), .Q (data_bit_counter[2]));
  SDFFQX4 stop_bit_error_reg(.CK (clk), .D (n_58), .SI (state[2]), .SE
       (dft_sen), .Q (n_61));
  NOR2X1 g2806__7344(.A (reset), .B (n_55), .Y (n_60));
  OAI33X1 g2807__1840(.A0 (reset), .A1 (n_2), .A2 (n_43), .B0 (n_19),
       .B1 (reset), .B2 (n_29), .Y (n_59));
  SDFFQX1 \data_bit_counter_reg[1] (.CK (clk), .D (n_56), .SI
       (data_bit_counter[0]), .SE (dft_sen), .Q (data_bit_counter[1]));
  NOR2X1 g2809__5019(.A (reset), .B (n_51), .Y (n_58));
  SDFFQX2 \data_bit_counter_reg[0] (.CK (clk), .D (n_53), .SI
       (dft_sdi), .SE (dft_sen), .Q (data_bit_counter[0]));
  NOR2X1 g2811__1857(.A (reset), .B (n_54), .Y (n_57));
  NOR2X1 g2812__9906(.A (reset), .B (n_52), .Y (n_56));
  NOR4BX1 g2813__8780(.AN (n_40), .B (n_17), .C (n_30), .D (n_27), .Y
       (n_55));
  SDFFQX1 data_out_to_buffer_reg(.CK (clk), .D (n_49), .SI
       (data_bit_counter[2]), .SE (dft_sen), .Q (data_out_to_buffer));
  SDFFQX1 data_valid_to_buffer_reg(.CK (clk), .D (n_50), .SI
       (data_out_to_buffer), .SE (dft_sen), .Q (data_valid_to_buffer));
  SDFFHQX4 \state_reg[2] (.CK (clk), .D (n_48), .SI (state[1]), .SE
       (dft_sen), .Q (state[2]));
  SDFFHQX4 \state_reg[1] (.CK (clk), .D (n_44), .SI (state[0]), .SE
       (dft_sen), .Q (state[1]));
  AOI31X1 g2818__4296(.A0 (data_bit_counter[1]), .A1
       (data_bit_counter[0]), .A2 (n_14), .B0 (n_46), .Y (n_54));
  NOR2X1 g2819__3772(.A (reset), .B (n_42), .Y (n_53));
  AOI22X1 g2820__1474(.A0 (data_bit_counter[1]), .A1 (n_39), .B0 (n_9),
       .B1 (n_14), .Y (n_52));
  AOI21X1 g2821__4547(.A0 (n_61), .A1 (n_35), .B0 (n_45), .Y (n_51));
  SDFFQX1 parity_reg(.CK (clk), .D (n_47), .SI (n_62), .SE (dft_sen),
       .Q (parity));
  NOR2X1 g2823__9682(.A (reset), .B (n_36), .Y (n_50));
  NOR2X1 g2824__2683(.A (reset), .B (n_38), .Y (n_49));
  AOI31X1 g2825__1309(.A0 (n_5), .A1 (n_15), .A2 (n_29), .B0 (reset),
       .Y (n_48));
  NOR2X1 g2826__6877(.A (reset), .B (n_37), .Y (n_47));
  SDFFQX1 tick_start_reg(.CK (clk), .D (n_41), .SI (n_61), .SE
       (dft_sen), .Q (tick_start));
  OA21X1 g2828__2900(.A0 (state[1]), .A1 (n_34), .B0
       (data_bit_counter[2]), .Y (n_46));
  AOI221X1 g2829__2391(.A0 (n_7), .A1 (n_31), .B0 (n_22), .B1 (n_24),
       .C0 (rx_data), .Y (n_45));
  AOI21X1 g2830__7675(.A0 (n_11), .A1 (n_32), .B0 (reset), .Y (n_44));
  NOR3X1 g2831__7118(.A (n_10), .B (n_6), .C (n_33), .Y (n_43));
  MXI2XL g2832__8757(.A (n_14), .B (n_34), .S0 (data_bit_counter[0]),
       .Y (n_42));
  AOI2BB1X1 g2833__1786(.A0N (tick_start), .A1N (n_27), .B0 (reset), .Y
       (n_41));
  OAI211X1 g2834__5953(.A0 (state[2]), .A1 (n_16), .B0
       (sampling_tick_middle), .C0 (n_10), .Y (n_40));
  AO21X1 g2835__5703(.A0 (n_4), .A1 (state[1]), .B0 (n_34), .Y (n_39));
  AOI22X1 g2836__7114(.A0 (rx_data), .A1 (n_14), .B0
       (data_out_to_buffer), .B1 (n_26), .Y (n_38));
  AOI22X1 g2837__5266(.A0 (n_19), .A1 (n_14), .B0 (parity), .B1 (n_26),
       .Y (n_37));
  AOI21X1 g2838__2250(.A0 (data_valid_to_buffer), .A1 (n_25), .B0
       (n_14), .Y (n_36));
  OAI211X1 g2839__6083(.A0 (state[2]), .A1 (n_11), .B0 (n_21), .C0
       (n_28), .Y (n_35));
  AO21X1 g2840__2703(.A0 (state[1]), .A1 (n_16), .B0 (n_26), .Y (n_34));
  OAI211X1 g2841__5795(.A0 (n_3), .A1 (n_12), .B0 (n_18), .C0 (n_24),
       .Y (n_33));
  MXI2XL g2842__7344(.A (state[1]), .B (n_6), .S0 (n_20), .Y (n_32));
  INVX1 g2843(.A (n_30), .Y (n_31));
  NAND2X1 g2844__1840(.A (state[0]), .B (n_15), .Y (n_28));
  NOR2X1 g2845__5019(.A (n_3), .B (n_15), .Y (n_30));
  OR3X1 g2846__1857(.A (n_3), .B (n_1), .C (n_8), .Y (n_29));
  OR2X1 g2847__9906(.A (n_6), .B (n_23), .Y (n_25));
  NOR4X2 g2848__8780(.A (state[2]), .B (rx_data), .C (state[0]), .D
       (state[1]), .Y (n_27));
  NAND2X1 g2849__4296(.A (n_3), .B (n_13), .Y (n_26));
  NOR2BX1 g2850__3772(.AN (state[2]), .B (n_7), .Y (n_23));
  OR2X1 g2851__1474(.A (state[1]), .B (n_12), .Y (n_22));
  NAND2BX1 g2852__4547(.AN (n_5), .B (n_7), .Y (n_21));
  NAND2BX1 g2853__9682(.AN (n_5), .B (sampling_tick_middle), .Y (n_24));
  NAND2X1 g2854__2683(.A (n_12), .B (n_8), .Y (n_20));
  INVX1 g2855(.A (n_17), .Y (n_18));
  AOI2BB1X1 g2856__1309(.A0N (sampling_tick_middle), .A1N (n_1), .B0
       (state[2]), .Y (n_13));
  CLKXOR2X1 g2857__6877(.A (parity), .B (rx_data), .Y (n_19));
  NOR3X1 g2858__2900(.A (sampling_tick_middle), .B (state[2]), .C
       (n_3), .Y (n_17));
  AND3XL g2859__2391(.A (data_bit_counter[2]), .B
       (data_bit_counter[1]), .C (data_bit_counter[0]), .Y (n_16));
  OAI2BB1X1 g2860__7675(.A0N (sampling_tick_end), .A1N (state[1]), .B0
       (state[2]), .Y (n_15));
  NOR2X2 g2861__7118(.A (n_8), .B (n_11), .Y (n_14));
  INVX1 g2862(.A (n_11), .Y (n_10));
  NOR2X1 g2863__8757(.A (data_bit_counter[1]), .B (n_4), .Y (n_9));
  NAND2X1 g2864__1786(.A (sampling_tick_end), .B (state[2]), .Y (n_12));
  OR2X1 g2865__5953(.A (state[0]), .B (n_1), .Y (n_11));
  NAND2BX2 g2866__5703(.AN (state[2]), .B (sampling_tick_middle), .Y
       (n_8));
  NOR2X1 g2867__7114(.A (sampling_tick_middle), .B (state[1]), .Y
       (n_7));
  NOR2X1 g2868__5266(.A (n_3), .B (state[1]), .Y (n_6));
  NAND2X1 g2869__2250(.A (state[2]), .B (n_3), .Y (n_5));
  INVX1 g2870(.A (data_bit_counter[0]), .Y (n_4));
  INVX1 g2871(.A (state[0]), .Y (n_3));
  INVX1 g2872(.A (n_62), .Y (n_2));
  INVX1 g2873(.A (state[1]), .Y (n_1));
  BUFX6 drc_bufs2876(.A (n_61), .Y (n_0));
  CLKBUFX20 drc_bufs2879(.A (n_62), .Y (parity_error));
  CLKBUFX20 drc_bufs(.A (n_0), .Y (stop_bit_error));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_2(clk, reset,
     start, tick_16_8, tick_16_16, dft_sen, dft_sdo, dft_sdi);
  input clk, reset, start, dft_sen, dft_sdi;
  output tick_16_8, tick_16_16, dft_sdo;
  wire clk, reset, start, dft_sen, dft_sdi;
  wire tick_16_8, tick_16_16, dft_sdo;
  wire [10:0] counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_61, n_63, n_64;
  wire n_65;
  SDFFQX1 tick_16_16_reg(.CK (clk), .D (n_36), .SI (tick_16_8), .SE
       (dft_sen), .Q (tick_16_16));
  NAND2BX1 g868__6083(.AN (n_63), .B (start), .Y (n_64));
  NOR3BX1 g869__2703(.AN (start), .B (reset), .C (n_63), .Y (n_36));
  OR2X1 g870__5795(.A (n_33), .B (n_35), .Y (n_63));
  AOI21X1 g871__7344(.A0 (counter[6]), .A1 (n_34), .B0 (counter[7]), .Y
       (n_35));
  OAI2BB1X1 g872__1840(.A0N (counter[5]), .A1N (n_61), .B0 (n_65), .Y
       (n_34));
  NAND2X1 g873__5019(.A (counter[4]), .B (counter[5]), .Y (n_65));
  NAND2X1 g874__1857(.A (dft_sdo), .B (counter[9]), .Y (n_33));
  OR2X1 g875__9906(.A (counter[3]), .B (counter[2]), .Y (n_61));
  SDFFQX1 \counter_reg[9] (.CK (clk), .D (n_32), .SI (dft_sdi), .SE
       (dft_sen), .Q (counter[9]));
  SDFFQX1 \counter_reg[8] (.CK (clk), .D (n_31), .SI (counter[7]), .SE
       (dft_sen), .Q (dft_sdo));
  NOR3X1 g1417__8780(.A (reset), .B (n_1), .C (n_30), .Y (n_32));
  NOR3BX1 g1418__4296(.AN (n_29), .B (reset), .C (n_1), .Y (n_31));
  NOR2X1 g1419__3772(.A (counter[9]), .B (n_28), .Y (n_30));
  ADDHX1 g1420__1474(.A (dft_sdo), .B (n_25), .CO (n_28), .S (n_29));
  SDFFQX1 \counter_reg[7] (.CK (clk), .D (n_27), .SI (counter[6]), .SE
       (dft_sen), .Q (counter[7]));
  NOR3BX1 g1422__4547(.AN (n_26), .B (reset), .C (n_1), .Y (n_27));
  SDFFQX1 \counter_reg[5] (.CK (clk), .D (n_24), .SI (counter[4]), .SE
       (dft_sen), .Q (counter[5]));
  ADDHX1 g1424__9682(.A (counter[7]), .B (n_19), .CO (n_25), .S (n_26));
  SDFFQX1 \counter_reg[6] (.CK (clk), .D (n_23), .SI (counter[5]), .SE
       (dft_sen), .Q (counter[6]));
  NOR3X1 g1426__2683(.A (reset), .B (n_21), .C (n_1), .Y (n_24));
  SDFFQX1 \counter_reg[4] (.CK (clk), .D (n_22), .SI (counter[3]), .SE
       (dft_sen), .Q (counter[4]));
  NOR3BX1 g1428__1309(.AN (n_20), .B (reset), .C (n_1), .Y (n_23));
  NOR3BX1 g1429__6877(.AN (n_18), .B (reset), .C (n_1), .Y (n_22));
  XNOR2X1 g1430__2900(.A (counter[5]), .B (n_17), .Y (n_21));
  ADDHX1 g1431__2391(.A (counter[6]), .B (n_15), .CO (n_19), .S (n_20));
  ADDHX1 g1432__7675(.A (counter[4]), .B (n_14), .CO (n_17), .S (n_18));
  SDFFQX1 \counter_reg[3] (.CK (clk), .D (n_16), .SI (counter[2]), .SE
       (dft_sen), .Q (counter[3]));
  NOR3BX1 g1434__7118(.AN (n_13), .B (reset), .C (n_1), .Y (n_16));
  SDFFQX1 tick_16_8_reg(.CK (clk), .D (n_12), .SI (counter[9]), .SE
       (dft_sen), .Q (tick_16_8));
  NOR2BX1 g1436__8757(.AN (n_14), .B (n_65), .Y (n_15));
  ADDHX1 g1437__1786(.A (counter[3]), .B (n_8), .CO (n_14), .S (n_13));
  SDFFQX1 \counter_reg[2] (.CK (clk), .D (n_10), .SI (counter[1]), .SE
       (dft_sen), .Q (counter[2]));
  NOR2X1 g1439__5953(.A (reset), .B (n_11), .Y (n_12));
  AOI31X1 g1440__5703(.A0 (dft_sdo), .A1 (counter[7]), .A2 (n_7), .B0
       (n_0), .Y (n_11));
  NOR3BX1 g1441__7114(.AN (n_9), .B (reset), .C (n_1), .Y (n_10));
  ADDHX1 g1442__5266(.A (counter[2]), .B (n_4), .CO (n_8), .S (n_9));
  SDFFQX1 \counter_reg[1] (.CK (clk), .D (n_6), .SI (counter[0]), .SE
       (dft_sen), .Q (counter[1]));
  NOR4BBX1 g1444__2250(.AN (counter[1]), .BN (n_3), .C (counter[6]), .D
       (counter[0]), .Y (n_7));
  NOR3BX1 g1445__6083(.AN (n_5), .B (reset), .C (n_1), .Y (n_6));
  ADDHX1 g1446__2703(.A (counter[1]), .B (counter[0]), .CO (n_4), .S
       (n_5));
  SDFFQX1 \counter_reg[0] (.CK (clk), .D (n_2), .SI (start), .SE
       (dft_sen), .Q (counter[0]));
  NOR4BBX1 g1448__5795(.AN (start), .BN (n_64), .C (n_65), .D (n_61),
       .Y (n_3));
  NOR3X1 g1449__7344(.A (reset), .B (counter[0]), .C (n_1), .Y (n_2));
  NAND2X4 g1450__1840(.A (start), .B (n_63), .Y (n_1));
  NOR2BX1 g1451__5019(.AN (tick_16_8), .B (n_64), .Y (n_0));
endmodule

module
     rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1(clk,
     reset, rx_data, data_parallel_out, data_parallel_rd_enable,
     rx_buffer_full, parity_error, stop_bit_error, dft_sdi, dft_sen,
     dft_sdo, dft_sdi_1, dft_sdo_2);
  input clk, reset, rx_data, data_parallel_rd_enable, dft_sdi, dft_sen,
       dft_sdi_1;
  output [7:0] data_parallel_out;
  output rx_buffer_full, parity_error, stop_bit_error, dft_sdo,
       dft_sdo_2;
  wire clk, reset, rx_data, data_parallel_rd_enable, dft_sdi, dft_sen,
       dft_sdi_1;
  wire [7:0] data_parallel_out;
  wire rx_buffer_full, parity_error, stop_bit_error, dft_sdo, dft_sdo_2;
  wire data_out_to_buffer, data_valid_to_buffer, n_17,
       sampling_tick_middle, tick_start;
  rx_buffer_WORD_SIZE8_NO_OF_WORDS1_1 ins_rx_buffer(.clk (clk), .reset
       (reset), .data_serial_wr_en (data_valid_to_buffer),
       .data_serial_in (data_out_to_buffer), .data_parallel_rd_enable
       (data_parallel_rd_enable), .data_parallel_out
       (data_parallel_out), .buffer_full (rx_buffer_full), .dft_sdi
       (dft_sdi), .dft_sen (dft_sen), .dft_sdo (n_17));
  rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1
       ins_rx_fsm(.clk (clk), .reset (reset), .sampling_tick_middle
       (sampling_tick_middle), .sampling_tick_end (dft_sdo_2),
       .tick_start (tick_start), .rx_data (rx_data),
       .data_out_to_buffer (data_out_to_buffer), .data_valid_to_buffer
       (data_valid_to_buffer), .parity_error (parity_error),
       .stop_bit_error (stop_bit_error), .dft_sdi (n_17), .dft_sen
       (dft_sen));
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_2
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (dft_sdo_2), .dft_sen (dft_sen), .dft_sdo (dft_sdo), .dft_sdi
       (dft_sdi_1));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_3(clk, reset,
     start, tick_16_8, tick_16_16, dft_sdi, dft_sen);
  input clk, reset, start, dft_sdi, dft_sen;
  output tick_16_8, tick_16_16;
  wire clk, reset, start, dft_sdi, dft_sen;
  wire tick_16_8, tick_16_16;
  wire [10:0] counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37;
  SDFFQX1 \counter_reg[9] (.CK (clk), .D (n_37), .SI (counter[8]), .SE
       (dft_sen), .Q (counter[9]));
  SDFFQX1 \counter_reg[8] (.CK (clk), .D (n_36), .SI (counter[7]), .SE
       (dft_sen), .Q (counter[8]));
  NOR3X1 g1458__1857(.A (reset), .B (n_0), .C (n_35), .Y (n_37));
  NOR3BX1 g1459__9906(.AN (n_34), .B (reset), .C (n_0), .Y (n_36));
  NOR2X1 g1460__8780(.A (counter[9]), .B (n_33), .Y (n_35));
  ADDHX1 g1461__4296(.A (counter[8]), .B (n_30), .CO (n_33), .S (n_34));
  SDFFQX1 \counter_reg[7] (.CK (clk), .D (n_32), .SI (counter[6]), .SE
       (dft_sen), .Q (counter[7]));
  NOR3BX1 g1463__3772(.AN (n_31), .B (reset), .C (n_0), .Y (n_32));
  SDFFQX1 \counter_reg[5] (.CK (clk), .D (n_29), .SI (counter[4]), .SE
       (dft_sen), .Q (counter[5]));
  ADDHX1 g1465__1474(.A (counter[7]), .B (n_23), .CO (n_30), .S (n_31));
  SDFFQX1 \counter_reg[6] (.CK (clk), .D (n_27), .SI (counter[5]), .SE
       (dft_sen), .Q (counter[6]));
  NOR3X1 g1467__4547(.A (reset), .B (n_25), .C (n_0), .Y (n_29));
  SDFFQX2 tick_16_8_reg(.CK (clk), .D (n_28), .SI (counter[9]), .SE
       (dft_sen), .Q (tick_16_8));
  SDFFQX1 \counter_reg[4] (.CK (clk), .D (n_26), .SI (counter[3]), .SE
       (dft_sen), .Q (counter[4]));
  NOR3BX1 g1470__9682(.AN (start), .B (reset), .C (n_22), .Y (n_28));
  NOR3BX1 g1471__2683(.AN (n_24), .B (reset), .C (n_0), .Y (n_27));
  NOR3BX1 g1472__1309(.AN (n_21), .B (reset), .C (n_0), .Y (n_26));
  XNOR2X1 g1473__6877(.A (counter[5]), .B (n_20), .Y (n_25));
  ADDHX1 g1474__2900(.A (counter[6]), .B (n_17), .CO (n_23), .S (n_24));
  AOI22X1 g1475__2391(.A0 (counter[8]), .A1 (n_19), .B0 (tick_16_8),
       .B1 (n_10), .Y (n_22));
  ADDHX1 g1476__7675(.A (counter[4]), .B (n_16), .CO (n_20), .S (n_21));
  SDFFQX1 \counter_reg[3] (.CK (clk), .D (n_18), .SI (counter[2]), .SE
       (dft_sen), .Q (counter[3]));
  NOR4BX1 g1478__7118(.AN (counter[7]), .B (counter[0]), .C
       (counter[6]), .D (n_11), .Y (n_19));
  NOR3BX1 g1479__8757(.AN (n_15), .B (reset), .C (n_0), .Y (n_18));
  SDFFQX1 \counter_reg[1] (.CK (clk), .D (n_13), .SI (counter[0]), .SE
       (dft_sen), .Q (counter[1]));
  SDFFQX1 \counter_reg[2] (.CK (clk), .D (n_12), .SI (counter[1]), .SE
       (dft_sen), .Q (counter[2]));
  NOR2BX1 g1482__1786(.AN (n_16), .B (n_3), .Y (n_17));
  SDFFQX1 \counter_reg[0] (.CK (clk), .D (n_14), .SI (dft_sdi), .SE
       (dft_sen), .Q (counter[0]));
  ADDHX1 g1484__5953(.A (counter[3]), .B (n_8), .CO (n_16), .S (n_15));
  NOR3X1 g1485__5703(.A (reset), .B (counter[0]), .C (n_0), .Y (n_14));
  NOR3BX1 g1486__7114(.AN (n_6), .B (reset), .C (n_0), .Y (n_13));
  NOR3BX1 g1487__5266(.AN (n_9), .B (reset), .C (n_0), .Y (n_12));
  OR4X1 g1489__2250(.A (n_1), .B (n_3), .C (n_2), .D (n_10), .Y (n_11));
  AND3XL g1490__6083(.A (counter[9]), .B (counter[8]), .C (n_7), .Y
       (n_10));
  ADDHX1 g1491__2703(.A (counter[2]), .B (n_5), .CO (n_8), .S (n_9));
  AO21X1 g1492__5795(.A0 (counter[6]), .A1 (n_4), .B0 (counter[7]), .Y
       (n_7));
  ADDHX1 g1493__7344(.A (counter[1]), .B (counter[0]), .CO (n_5), .S
       (n_6));
  OAI2BB1X1 g1494__1840(.A0N (counter[5]), .A1N (n_2), .B0 (n_3), .Y
       (n_4));
  NAND2X1 g1495__5019(.A (counter[4]), .B (counter[5]), .Y (n_3));
  OR2X1 g1496__1857(.A (counter[3]), .B (counter[2]), .Y (n_2));
  INVX1 g1498(.A (counter[1]), .Y (n_1));
  NAND2BX4 g2__9906(.AN (n_10), .B (start), .Y (n_0));
endmodule

module tx_buffer_WORD_SIZE8_NO_OF_WORDS1_1(clk, reset,
     data_parallel_in, data_parallel_wr_enable, data_serial_rd_enable,
     data_serial_out, empty, dft_sdi, dft_sen, dft_sdo);
  input clk, reset, data_parallel_wr_enable, data_serial_rd_enable,
       dft_sdi, dft_sen;
  input [7:0] data_parallel_in;
  output data_serial_out, empty, dft_sdo;
  wire clk, reset, data_parallel_wr_enable, data_serial_rd_enable,
       dft_sdi, dft_sen;
  wire [7:0] data_parallel_in;
  wire data_serial_out, empty, dft_sdo;
  wire [4:0] buffer_empty_counter;
  wire [7:0] memory;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_61, n_62;
  NOR2X1 g824__8780(.A (buffer_empty_counter[0]), .B (n_61), .Y
       (empty));
  OR2X1 g825__4296(.A (buffer_empty_counter[1]), .B (n_62), .Y (n_61));
  OR2X1 g826__3772(.A (buffer_empty_counter[3]), .B
       (buffer_empty_counter[2]), .Y (n_62));
  SDFFQX1 \buffer_empty_counter_reg[2] (.CK (clk), .D (n_37), .SI
       (buffer_empty_counter[1]), .SE (dft_sen), .Q
       (buffer_empty_counter[2]));
  SDFFQX1 \buffer_empty_counter_reg[3] (.CK (clk), .D (n_36), .SI
       (buffer_empty_counter[2]), .SE (dft_sen), .Q
       (buffer_empty_counter[3]));
  NOR3X1 g1291__1474(.A (reset), .B (n_31), .C
       (data_parallel_wr_enable), .Y (n_37));
  SDFFQX1 \buffer_empty_counter_reg[1] (.CK (clk), .D (n_35), .SI
       (buffer_empty_counter[0]), .SE (dft_sen), .Q
       (buffer_empty_counter[1]));
  SDFFQX1 \memory_reg[7] (.CK (clk), .D (n_34), .SI (memory[6]), .SE
       (dft_sen), .Q (dft_sdo));
  SDFFQX1 \buffer_empty_counter_reg[0] (.CK (clk), .D (n_33), .SI
       (dft_sdi), .SE (dft_sen), .Q (buffer_empty_counter[0]));
  NAND2BX1 g1295__4547(.AN (data_parallel_wr_enable), .B (n_32), .Y
       (n_36));
  NOR3X1 g1296__9682(.A (reset), .B (n_22), .C
       (data_parallel_wr_enable), .Y (n_35));
  SDFFQX1 \memory_reg[2] (.CK (clk), .D (n_28), .SI (memory[1]), .SE
       (dft_sen), .Q (memory[2]));
  SDFFQX1 \memory_reg[1] (.CK (clk), .D (n_30), .SI (memory[0]), .SE
       (dft_sen), .Q (memory[1]));
  SDFFQX1 \memory_reg[0] (.CK (clk), .D (n_29), .SI (data_serial_out),
       .SE (dft_sen), .Q (memory[0]));
  SDFFQX1 \memory_reg[3] (.CK (clk), .D (n_24), .SI (memory[2]), .SE
       (dft_sen), .Q (memory[3]));
  SDFFQX1 \memory_reg[4] (.CK (clk), .D (n_26), .SI (memory[3]), .SE
       (dft_sen), .Q (memory[4]));
  AO22X1 g1302__2683(.A0 (n_18), .A1 (dft_sdo), .B0
       (data_parallel_in[7]), .B1 (n_2), .Y (n_34));
  NOR3X1 g1303__1309(.A (reset), .B (n_14), .C
       (data_parallel_wr_enable), .Y (n_33));
  AOI21X1 g1304__6877(.A0 (buffer_empty_counter[3]), .A1 (n_21), .B0
       (reset), .Y (n_32));
  AOI22X1 g1305__2900(.A0 (buffer_empty_counter[3]), .A1 (n_20), .B0
       (buffer_empty_counter[2]), .B1 (n_9), .Y (n_31));
  SDFFQX1 \memory_reg[5] (.CK (clk), .D (n_27), .SI (memory[4]), .SE
       (dft_sen), .Q (memory[5]));
  SDFFQX1 \memory_reg[6] (.CK (clk), .D (n_23), .SI (memory[5]), .SE
       (dft_sen), .Q (memory[6]));
  OAI2BB1X1 g1308__2391(.A0N (n_0), .A1N (memory[1]), .B0 (n_17), .Y
       (n_30));
  OAI2BB1X1 g1309__7675(.A0N (n_0), .A1N (memory[0]), .B0 (n_16), .Y
       (n_29));
  OAI2BB1X1 g1310__7118(.A0N (n_0), .A1N (memory[2]), .B0 (n_15), .Y
       (n_28));
  SDFFQX1 data_serial_out_reg(.CK (clk), .D (n_19), .SI
       (buffer_empty_counter[3]), .SE (dft_sen), .Q (data_serial_out));
  OAI2BB1X1 g1312__8757(.A0N (n_0), .A1N (memory[5]), .B0 (n_10), .Y
       (n_27));
  OAI2BB1X1 g1313__1786(.A0N (n_0), .A1N (memory[4]), .B0 (n_12), .Y
       (n_26));
  OAI2BB1X1 g1314__5953(.A0N (n_0), .A1N (memory[3]), .B0 (n_13), .Y
       (n_24));
  OAI2BB1X1 g1315__5703(.A0N (n_0), .A1N (memory[6]), .B0 (n_11), .Y
       (n_23));
  AOI22X1 g1316__7114(.A0 (n_62), .A1 (n_8), .B0
       (buffer_empty_counter[1]), .B1 (n_4), .Y (n_22));
  INVX1 g1317(.A (n_20), .Y (n_21));
  MX2X1 g1318__5266(.A (n_6), .B (memory[0]), .S0
       (data_serial_rd_enable), .Y (n_19));
  OAI21X1 g1319__2250(.A0 (reset), .A1 (n_1), .B0 (n_7), .Y (n_18));
  AOI22X1 g1320__6083(.A0 (data_parallel_in[1]), .A1 (n_2), .B0
       (memory[2]), .B1 (data_serial_rd_enable), .Y (n_17));
  AOI22X1 g1321__2703(.A0 (data_parallel_in[0]), .A1 (n_2), .B0
       (memory[1]), .B1 (data_serial_rd_enable), .Y (n_16));
  NOR2X1 g1322__5795(.A (buffer_empty_counter[2]), .B (n_9), .Y (n_20));
  AOI22X1 g1323__7344(.A0 (data_parallel_in[2]), .A1 (n_2), .B0
       (memory[3]), .B1 (data_serial_rd_enable), .Y (n_15));
  AOI22X1 g1324__1840(.A0 (n_3), .A1 (n_61), .B0
       (buffer_empty_counter[0]), .B1 (n_1), .Y (n_14));
  AOI22X1 g1325__5019(.A0 (data_parallel_in[3]), .A1 (n_2), .B0
       (memory[4]), .B1 (data_serial_rd_enable), .Y (n_13));
  AOI22X1 g1326__1857(.A0 (data_parallel_in[4]), .A1 (n_2), .B0
       (memory[5]), .B1 (data_serial_rd_enable), .Y (n_12));
  AOI22X1 g1327__9906(.A0 (data_parallel_in[6]), .A1 (n_2), .B0
       (dft_sdo), .B1 (data_serial_rd_enable), .Y (n_11));
  AOI22X1 g1328__8780(.A0 (data_parallel_in[5]), .A1 (n_2), .B0
       (memory[6]), .B1 (data_serial_rd_enable), .Y (n_10));
  INVX1 g1329(.A (n_8), .Y (n_9));
  NOR2X1 g1330__4296(.A (buffer_empty_counter[1]), .B (n_4), .Y (n_8));
  INVX1 g1331(.A (n_0), .Y (n_7));
  NOR2BX1 g1333__3772(.AN (data_serial_out), .B (reset), .Y (n_6));
  NOR2X1 g1334__1474(.A (reset), .B (data_serial_rd_enable), .Y (n_5));
  INVX1 g1335(.A (n_3), .Y (n_4));
  NOR2X1 g1336__4547(.A (buffer_empty_counter[0]), .B (n_1), .Y (n_3));
  AND2X1 g1337__9682(.A (data_parallel_wr_enable), .B (n_1), .Y (n_2));
  INVX1 g1343(.A (data_serial_rd_enable), .Y (n_1));
  NOR2BX2 g2__2683(.AN (n_5), .B (data_parallel_wr_enable), .Y (n_0));
endmodule

module
     tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1(clk,
     reset, empty, sampling_tick_middle, sampling_tick_end, tick_start,
     data_parallel_wr_enable, tx_busy, tx_data, buffer_rd_enable,
     buffer_data, dft_sdi, dft_sen);
  input clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data, dft_sdi, dft_sen;
  output tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data, dft_sdi, dft_sen;
  wire tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire [2:0] data_bit_counter;
  wire [3:0] state;
  wire delay_data_parallel_wr_enable, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, parity, tem_buffer_data;
  SDFFHQX4 buffer_rd_enable_reg(.CK (clk), .D (n_68), .SI (dft_sdi),
       .SE (dft_sen), .Q (buffer_rd_enable));
  SDFFQX2 \data_bit_counter_reg[0] (.CK (clk), .D (n_74), .SI
       (buffer_rd_enable), .SE (dft_sen), .Q (data_bit_counter[0]));
  SDFFQX1 \data_bit_counter_reg[1] (.CK (clk), .D (n_77), .SI
       (data_bit_counter[0]), .SE (dft_sen), .Q (data_bit_counter[1]));
  SDFFQX1 \data_bit_counter_reg[2] (.CK (clk), .D (n_67), .SI
       (data_bit_counter[1]), .SE (dft_sen), .Q (data_bit_counter[2]));
  SDFFQX1 delay_data_parallel_wr_enable_reg(.CK (clk), .D
       (data_parallel_wr_enable), .SI (data_bit_counter[2]), .SE
       (dft_sen), .Q (delay_data_parallel_wr_enable));
  SDFFQX1 parity_reg(.CK (clk), .D (n_80), .SI
       (delay_data_parallel_wr_enable), .SE (dft_sen), .Q (parity));
  SDFFQX2 \state_reg[0] (.CK (clk), .D (n_78), .SI (parity), .SE
       (dft_sen), .Q (state[0]));
  SDFFQX1 \state_reg[1] (.CK (clk), .D (n_56), .SI (state[0]), .SE
       (dft_sen), .Q (state[1]));
  SDFFHQX4 \state_reg[2] (.CK (clk), .D (n_76), .SI (state[1]), .SE
       (dft_sen), .Q (state[2]));
  SDFFQX1 \state_reg[3] (.CK (clk), .D (n_53), .SI (state[2]), .SE
       (dft_sen), .Q (state[3]));
  SDFFQX1 tem_buffer_data_reg(.CK (clk), .D (n_79), .SI (state[3]), .SE
       (dft_sen), .Q (tem_buffer_data));
  SDFFQX1 tick_start_reg(.CK (clk), .D (n_71), .SI (tem_buffer_data),
       .SE (dft_sen), .Q (tick_start));
  SDFFHQX8 tx_busy_reg(.CK (clk), .D (n_63), .SI (tick_start), .SE
       (dft_sen), .Q (n_81));
  SDFFQX1 tx_data_reg(.CK (clk), .D (n_73), .SI (n_81), .SE (dft_sen),
       .Q (tx_data));
  NOR2X1 g2725__1309(.A (reset), .B (n_75), .Y (n_80));
  AOI21X1 g2728__6877(.A0 (n_48), .A1 (n_70), .B0 (reset), .Y (n_79));
  OAI221X1 g2731__2900(.A0 (reset), .A1 (n_30), .B0 (n_62), .B1
       (state[0]), .C0 (n_72), .Y (n_78));
  AOI21X1 g2732__2391(.A0 (n_51), .A1 (n_69), .B0 (reset), .Y (n_77));
  AOI31X1 g2733__7675(.A0 (n_28), .A1 (n_38), .A2 (n_58), .B0 (reset),
       .Y (n_76));
  MX2X1 g2734__7118(.A (n_48), .B (n_66), .S0 (parity), .Y (n_75));
  NOR2X1 g2737__8757(.A (reset), .B (n_65), .Y (n_74));
  NAND3X1 g2738__1786(.A (n_64), .B (n_32), .C (n_37), .Y (n_73));
  NAND2BX1 g2740__5953(.AN (reset), .B (n_57), .Y (n_72));
  AOI31X1 g2741__5703(.A0 (n_46), .A1 (n_37), .A2 (n_47), .B0 (reset),
       .Y (n_71));
  NAND2X1 g2742__7114(.A (tem_buffer_data), .B (n_60), .Y (n_70));
  OAI2BB1X1 g2745__5266(.A0N (n_17), .A1N (n_55), .B0
       (data_bit_counter[1]), .Y (n_69));
  NOR2X1 g2746__2250(.A (reset), .B (n_59), .Y (n_68));
  NOR2X1 g2747__6083(.A (reset), .B (n_61), .Y (n_67));
  AOI2BB1X1 g2748__2703(.A0N (buffer_data), .A1N (n_1), .B0 (n_60), .Y
       (n_66));
  AOI222X1 g2749__5795(.A0 (n_5), .A1 (n_35), .B0 (state[2]), .B1
       (n_21), .C0 (data_bit_counter[0]), .C1 (n_54), .Y (n_65));
  AOI211X1 g2750__7344(.A0 (tx_data), .A1 (n_24), .B0 (reset), .C0
       (n_49), .Y (n_64));
  AOI21X1 g2751__1840(.A0 (n_45), .A1 (n_47), .B0 (reset), .Y (n_63));
  AO21X1 g2752__5019(.A0 (n_22), .A1 (n_39), .B0 (reset), .Y (n_62));
  AOI31X1 g2753__1857(.A0 (data_bit_counter[0]), .A1
       (data_bit_counter[1]), .A2 (n_35), .B0 (n_52), .Y (n_61));
  AOI222X1 g2755__9906(.A0 (n_20), .A1 (n_35), .B0 (buffer_rd_enable),
       .B1 (n_22), .C0 (n_3), .C1 (n_36), .Y (n_59));
  OA21X1 g2756__8780(.A0 (state[0]), .A1 (n_9), .B0 (n_50), .Y (n_58));
  OAI221X1 g2757__4296(.A0 (n_2), .A1 (n_28), .B0
       (sampling_tick_middle), .B1 (n_27), .C0 (n_44), .Y (n_57));
  OAI22X1 g2758__3772(.A0 (reset), .A1 (n_40), .B0 (reset), .B1 (n_41),
       .Y (n_56));
  OR3X1 g2759__1474(.A (state[2]), .B (n_0), .C (n_43), .Y (n_60));
  INVX1 g2760(.A (n_54), .Y (n_55));
  NOR2X1 g2761__4547(.A (reset), .B (n_42), .Y (n_53));
  OA21X1 g2762__9682(.A0 (n_7), .A1 (n_34), .B0 (data_bit_counter[2]),
       .Y (n_52));
  NAND3X2 g2763__2683(.A (n_1), .B (n_28), .C (n_33), .Y (n_54));
  NAND3BX1 g2764__1309(.AN (data_bit_counter[1]), .B
       (data_bit_counter[0]), .C (n_35), .Y (n_51));
  OAI211X1 g2765__6877(.A0 (state[0]), .A1 (n_21), .B0 (n_1), .C0
       (state[2]), .Y (n_50));
  OAI33X1 g2766__2900(.A0 (state[0]), .A1 (n_16), .A2 (n_18), .B0
       (n_15), .B1 (parity), .B2 (n_27), .Y (n_49));
  NAND2X1 g2767__2391(.A (tick_start), .B (n_32), .Y (n_46));
  NAND2X1 g2768__7675(.A (n_81), .B (n_32), .Y (n_45));
  NAND2X1 g2769__7118(.A (n_21), .B (n_35), .Y (n_44));
  NAND2BX1 g2770__8757(.AN (n_38), .B (buffer_data), .Y (n_48));
  NAND2BX1 g2771__1786(.AN (n_32), .B (delay_data_parallel_wr_enable),
       .Y (n_47));
  OAI211X1 g2772__5953(.A0 (state[0]), .A1 (n_14), .B0 (n_11), .C0
       (n_6), .Y (n_43));
  AOI22X1 g2773__5703(.A0 (state[3]), .A1 (n_19), .B0 (state[0]), .B1
       (n_26), .Y (n_42));
  AOI211X1 g2774__7114(.A0 (state[1]), .A1 (n_2), .B0 (n_10), .C0
       (n_25), .Y (n_41));
  AOI21X1 g2775__5266(.A0 (n_20), .A1 (n_23), .B0 (n_36), .Y (n_40));
  AOI31X1 g2776__2250(.A0 (delay_data_parallel_wr_enable), .A1 (n_4),
       .A2 (n_3), .B0 (n_31), .Y (n_39));
  OR2X1 g2777__6083(.A (n_2), .B (n_22), .Y (n_38));
  OR2X1 g2778__2703(.A (n_7), .B (n_29), .Y (n_37));
  AND2X1 g2779__5795(.A (n_0), .B (sampling_tick_middle), .Y (n_36));
  AND2X1 g2780__7344(.A (n_23), .B (n_2), .Y (n_35));
  INVX1 g2781(.A (n_33), .Y (n_34));
  NOR3BX1 g2782__1840(.AN (sampling_tick_middle), .B (n_4), .C (n_7),
       .Y (n_31));
  OA21X1 g2783__5019(.A0 (n_2), .A1 (n_11), .B0 (n_29), .Y (n_30));
  MX2X1 g2784__1857(.A (n_12), .B (n_2), .S0 (n_4), .Y (n_33));
  OR3X1 g2785__9906(.A (state[0]), .B (state[2]), .C (n_13), .Y (n_32));
  NOR2X1 g2787__8780(.A (n_1), .B (n_15), .Y (n_26));
  NOR2X1 g2788__4296(.A (sampling_tick_middle), .B (n_9), .Y (n_25));
  NAND2X1 g2789__3772(.A (sampling_tick_middle), .B (n_14), .Y (n_24));
  NAND2X1 g2790__1474(.A (state[3]), .B (n_12), .Y (n_29));
  NAND2X2 g2791__4547(.A (state[2]), .B (n_16), .Y (n_28));
  NAND2X1 g2792__9682(.A (state[0]), .B (n_14), .Y (n_27));
  INVX1 g2793(.A (n_21), .Y (n_20));
  OR2X1 g2794__2683(.A (n_2), .B (n_7), .Y (n_19));
  AOI21X1 g2795__1309(.A0 (tem_buffer_data), .A1 (state[2]), .B0 (n_8),
       .Y (n_18));
  OAI21X1 g2796__6877(.A0 (data_bit_counter[2]), .A1 (n_5), .B0
       (state[2]), .Y (n_17));
  NOR2X1 g2797__2900(.A (n_15), .B (n_13), .Y (n_23));
  OR3X1 g2798__2391(.A (n_1), .B (state[3]), .C (state[2]), .Y (n_22));
  AND3XL g2799__7675(.A (data_bit_counter[2]), .B
       (data_bit_counter[1]), .C (data_bit_counter[0]), .Y (n_21));
  INVX1 g2800(.A (n_14), .Y (n_13));
  NAND2X1 g2801__7118(.A (sampling_tick_middle), .B (n_4), .Y (n_16));
  NAND2X1 g2803__8757(.A (sampling_tick_middle), .B (state[2]), .Y
       (n_15));
  AND2X1 g2804__1786(.A (n_4), .B (n_1), .Y (n_14));
  INVX1 g2805(.A (n_11), .Y (n_10));
  INVX1 g2806(.A (n_8), .Y (n_9));
  NAND2X1 g2807__5953(.A (state[3]), .B (empty), .Y (n_6));
  NOR2X1 g2808__5703(.A (n_2), .B (empty), .Y (n_12));
  NAND2X1 g2809__7114(.A (state[1]), .B (state[3]), .Y (n_11));
  NOR2X1 g2810__5266(.A (n_1), .B (n_3), .Y (n_8));
  OR2X1 g2811__2250(.A (state[1]), .B (state[2]), .Y (n_7));
  INVX1 g2812(.A (data_bit_counter[0]), .Y (n_5));
  INVX1 g2813(.A (state[3]), .Y (n_4));
  INVX1 g2814(.A (state[2]), .Y (n_3));
  INVX1 g2815(.A (state[0]), .Y (n_2));
  INVX1 g2816(.A (state[1]), .Y (n_1));
  CLKBUFX20 drc_bufs2819(.A (n_81), .Y (tx_busy));
  INVX1 drc_bufs2825(.A (n_27), .Y (n_0));
endmodule

module
     tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1(clk,
     reset, data_parallel_in, data_parallel_wr_enable, tx_busy,
     tx_data, dft_sdi, dft_sen);
  input clk, reset, data_parallel_wr_enable, dft_sdi, dft_sen;
  input [7:0] data_parallel_in;
  output tx_busy, tx_data;
  wire clk, reset, data_parallel_wr_enable, dft_sdi, dft_sen;
  wire [7:0] data_parallel_in;
  wire tx_busy, tx_data;
  wire UNCONNECTED_HIER_Z0, data_serial_out, data_serial_rd_enable,
       empty, n_15, sampling_tick_end, sampling_tick_middle, tick_start;
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_3
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (sampling_tick_end), .dft_sdi (dft_sdi), .dft_sen (dft_sen));
  tx_buffer_WORD_SIZE8_NO_OF_WORDS1_1 ins_tx_buffer(.clk (clk), .reset
       (reset), .data_parallel_in (data_parallel_in),
       .data_parallel_wr_enable (data_parallel_wr_enable),
       .data_serial_rd_enable (data_serial_rd_enable), .data_serial_out
       (data_serial_out), .empty (empty), .dft_sdi
       (sampling_tick_middle), .dft_sen (dft_sen), .dft_sdo (n_15));
  tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1
       ins_tx_fsm(.clk (clk), .reset (reset), .empty (empty),
       .sampling_tick_middle (sampling_tick_middle), .sampling_tick_end
       (UNCONNECTED_HIER_Z0), .tick_start (tick_start),
       .data_parallel_wr_enable (data_parallel_wr_enable), .tx_busy
       (tx_busy), .tx_data (tx_data), .buffer_rd_enable
       (data_serial_rd_enable), .buffer_data (data_serial_out),
       .dft_sdi (n_15), .dft_sen (dft_sen));
endmodule

module
     uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1_1(clk,
     reset, uart_hw_rx_pin, uart_hw_tx_pin, tx_parallel_data_in,
     tx_data_wr_enable_in, tx_busy_out, rx_full, rx_parallel_data_out,
     rx_data_rd_enable_in, rx_parity_error, rx_stop_bit_error, dft_sdi,
     dft_sen, dft_sdo, dft_sdi_1);
  input clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in, dft_sdi, dft_sen, dft_sdi_1;
  input [7:0] tx_parallel_data_in;
  output uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error, dft_sdo;
  output [7:0] rx_parallel_data_out;
  wire clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in, dft_sdi, dft_sen, dft_sdi_1;
  wire [7:0] tx_parallel_data_in;
  wire uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error, dft_sdo;
  wire [7:0] rx_parallel_data_out;
  wire n_30;
  rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1
       ins_rx_wrapper(.clk (clk), .reset (reset), .rx_data
       (uart_hw_rx_pin), .data_parallel_out (rx_parallel_data_out),
       .data_parallel_rd_enable (rx_data_rd_enable_in), .rx_buffer_full
       (rx_full), .parity_error (rx_parity_error), .stop_bit_error
       (rx_stop_bit_error), .dft_sdi (dft_sdi), .dft_sen (dft_sen),
       .dft_sdo (dft_sdo), .dft_sdi_1 (dft_sdi_1), .dft_sdo_2 (n_30));
  tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1
       ins_tx_wrapper(.clk (clk), .reset (reset), .data_parallel_in
       (tx_parallel_data_in), .data_parallel_wr_enable
       (tx_data_wr_enable_in), .tx_busy (tx_busy_out), .tx_data
       (uart_hw_tx_pin), .dft_sdi (n_30), .dft_sen (dft_sen));
endmodule

module uart_top(clk_a, reset_a, tx_parallel_data_in_a,
     tx_data_wr_enable_in_a, tx_busy_out_a, rx_full_a,
     rx_parallel_data_out_a, rx_data_rd_enable_in_a, rx_parity_error_a,
     rx_stop_bit_error_a, clk_b, reset_b, tx_parallel_data_in_b,
     tx_data_wr_enable_in_b, tx_busy_out_b, rx_full_b,
     rx_parallel_data_out_b, rx_data_rd_enable_in_b, rx_parity_error_b,
     rx_stop_bit_error_b, SE, scan_in_a1, scan_out_a1, scan_in_a2,
     scan_out_a2, scan_in_b1, scan_out_b1, scan_in_b2, scan_out_b2);
  input clk_a, reset_a, tx_data_wr_enable_in_a, rx_data_rd_enable_in_a,
       clk_b, reset_b, tx_data_wr_enable_in_b, rx_data_rd_enable_in_b,
       SE, scan_in_a1, scan_in_a2, scan_in_b1, scan_in_b2;
  input [7:0] tx_parallel_data_in_a, tx_parallel_data_in_b;
  output tx_busy_out_a, rx_full_a, rx_parity_error_a,
       rx_stop_bit_error_a, tx_busy_out_b, rx_full_b,
       rx_parity_error_b, rx_stop_bit_error_b, scan_out_a1,
       scan_out_a2, scan_out_b1, scan_out_b2;
  output [7:0] rx_parallel_data_out_a, rx_parallel_data_out_b;
  wire clk_a, reset_a, tx_data_wr_enable_in_a, rx_data_rd_enable_in_a,
       clk_b, reset_b, tx_data_wr_enable_in_b, rx_data_rd_enable_in_b,
       SE, scan_in_a1, scan_in_a2, scan_in_b1, scan_in_b2;
  wire [7:0] tx_parallel_data_in_a, tx_parallel_data_in_b;
  wire tx_busy_out_a, rx_full_a, rx_parity_error_a,
       rx_stop_bit_error_a, tx_busy_out_b, rx_full_b,
       rx_parity_error_b, rx_stop_bit_error_b, scan_out_a1,
       scan_out_a2, scan_out_b1, scan_out_b2;
  wire [7:0] rx_parallel_data_out_a, rx_parallel_data_out_b;
  uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1
       ins_uart_transceiver_A(.clk (clk_a), .reset (reset_a),
       .uart_hw_rx_pin (scan_out_b2), .uart_hw_tx_pin (scan_out_a2),
       .tx_parallel_data_in (tx_parallel_data_in_a),
       .tx_data_wr_enable_in (tx_data_wr_enable_in_a), .tx_busy_out
       (tx_busy_out_a), .rx_full (rx_full_a), .rx_parallel_data_out
       (rx_parallel_data_out_a), .rx_data_rd_enable_in
       (rx_data_rd_enable_in_a), .rx_parity_error (rx_parity_error_a),
       .rx_stop_bit_error (rx_stop_bit_error_a), .dft_sdi (scan_in_a1),
       .dft_sen (SE), .dft_sdo (scan_out_a1), .dft_sdi_1 (scan_in_a2));
  uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1_1
       ins_uart_transceiver_B(.clk (clk_b), .reset (reset_b),
       .uart_hw_rx_pin (scan_out_a2), .uart_hw_tx_pin (scan_out_b2),
       .tx_parallel_data_in (tx_parallel_data_in_b),
       .tx_data_wr_enable_in (tx_data_wr_enable_in_b), .tx_busy_out
       (tx_busy_out_b), .rx_full (rx_full_b), .rx_parallel_data_out
       (rx_parallel_data_out_b), .rx_data_rd_enable_in
       (rx_data_rd_enable_in_b), .rx_parity_error (rx_parity_error_b),
       .rx_stop_bit_error (rx_stop_bit_error_b), .dft_sdi (scan_in_b1),
       .dft_sen (SE), .dft_sdo (scan_out_b1), .dft_sdi_1 (scan_in_b2));
endmodule

